// packages-js/bpmn-vue/src/web-component/useElementSource.ts
/**
 * Data source of the web component in Vue: XML, profile and ports from the
 * element properties, resolved by the framework-free `elementSource`
 * functions of the UI core and reloaded when an input changes.
 */

import { computed, ref, shallowRef, watch } from 'vue'
import { loadSource, persistSource, sourcePorts, sourceRest, sourceStorage, type ElementSourceInput } from '@auditcore/bpmn-flowaudit/ui'
import type { ProfileData } from '@auditcore/bpmn-flowaudit'

export type ElementSourceProps = ElementSourceInput

export function useElementSource(props: ElementSourceProps, onError: (message: string) => void) {
  const xml = ref('')
  const profile = shallowRef<ProfileData | null>(null)
  const rest = computed(() => sourceRest(props))
  const storage = computed(() => sourceStorage(props, rest.value))
  const ports = computed(() => sourcePorts(props, rest.value))

  async function reload(): Promise<void> {
    try {
      const next = await loadSource(props)
      profile.value = next.profile
      if (next.xml) xml.value = next.xml
    } catch (error) {
      onError((error as Error).message)
    }
  }

  watch(() => [props.xml, props.src, props.apiBase, props.diagramId, props.profile, props.profileData, props.storage], reload, { immediate: true })

  return { xml, profile, ports, storage, persist: (content: string) => persistSource(props, content), reload }
}

// packages-js/bpmn-react/src/element/useElementSource.ts
/**
 * Data source of the embeddable editor in React: XML, profile and ports from
 * the props, resolved by the framework-free `elementSource` functions of the
 * UI core (same rules as the Vue web component) and reloaded on change.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { loadSource, persistSource, sourcePorts, sourceRest, type ElementSourceInput } from '@auditcore/bpmn-flowaudit/ui'
import type { ProfileData } from '@auditcore/bpmn-flowaudit'

export function useElementSource(input: ElementSourceInput, onError: (message: string) => void) {
  const [xml, setXml] = useState('')
  const [profile, setProfile] = useState<ProfileData | null>(null)
  const latest = useRef({ input, onError })
  useEffect(() => {
    latest.current = { input, onError }
  })

  const reload = useCallback(async (): Promise<void> => {
    try {
      const next = await loadSource(latest.current.input)
      setProfile(next.profile)
      if (next.xml) setXml(next.xml)
    } catch (error) {
      latest.current.onError((error as Error).message)
    }
  }, [])

  const { xml: givenXml, src, apiBase, diagramId, profile: profileId, profileData, storage } = input
  useEffect(() => {
    void reload()
  }, [reload, givenXml, src, apiBase, diagramId, profileId, profileData, storage])

  const ports = useMemo(() => sourcePorts({ apiBase, ports: input.ports }, sourceRest({ apiBase })), [apiBase, input.ports])
  const persist = useCallback((content: string) => persistSource(latest.current.input, content), [])
  return { xml, setXml, profile, ports, persist, reload }
}
