// packages-js/ui/src/dataprotection/components/VvtActivityDetail.vue
<script setup lang="ts">
import { computed } from 'vue'
import FaButton from '../../base/FaButton.vue'
import { useI18n } from '../../i18n'
import { dataprotectionMessages } from '../core'
import { displayValue, fieldIssues } from '../core'
import type { Activity, RegisterColumn, FieldValue, Issue } from '../core'
import VvtField from './VvtField.vue'

const props = withDefaults(defineProps<{
  activity: Activity
  columns?: RegisterColumn[]
  issues?: Issue[]
  departments?: string[]
  editing?: boolean
}>(), { columns: () => [], issues: () => [], departments: () => [], editing: false })

const emit = defineEmits<{ 'field-change': [key: string, value: FieldValue]; remove: [] }>()
const { t } = useI18n(dataprotectionMessages)
const title = computed(() => (typeof props.activity.name === 'string' && props.activity.name.trim()) || t('unnamed'))
const texts = computed(() => ({ yes: t('yes'), no: t('no'), empty: t('empty') }))
</script>

<template>
  <article class="fa-dataprotection__panel" data-testid="vvt-detail" :aria-label="title">
    <div class="fa-dataprotection__bar">
      <h3>{{ title }}</h3>
      <span v-if="activity.id" class="fa-dataprotection__muted">{{ activity.id }}</span>
      <div v-if="editing" class="fa-dataprotection__actions">
        <FaButton variant="ghost" size="sm" icon="trash" :label="t('removeActivity')" @click="emit('remove')" />
      </div>
    </div>
    <div v-if="editing" class="fa-dataprotection__grid">
      <VvtField
        v-for="column in columns"
        :key="column.key"
        :column="column"
        :value="activity[column.key] ?? null"
        :issues="fieldIssues(issues, activity, column.key)"
        :departments="departments"
        @value-change="emit('field-change', column.key, $event)"
      />
    </div>
    <dl v-else class="fa-dataprotection__dl">
      <template v-for="column in columns" :key="column.key">
        <dt>{{ column.title }}<br /><span class="fa-dataprotection__ref">{{ column.reference }}</span></dt>
        <dd>
          {{ displayValue(activity[column.key], texts) }}
          <span v-for="issue in fieldIssues(issues, activity, column.key)" :key="issue.message" class="fa-dataprotection__note" :class="{ 'fa-dataprotection__note--blocking': issue.blocking }">
            <br />{{ issue.message }}
          </span>
        </dd>
      </template>
    </dl>
  </article>
</template>

// packages-js/ui-react/src/dataprotection/vvt/VvtActivityDetail.tsx
import { Fragment } from 'react'
import { displayValue, fieldIssues, type Activity, type FieldValue, type RegisterColumn, type RegisterIssue } from '@auditcore/ui-core'
import { Button } from '../../base/Button'
import { classes } from '../../store'
import { useDataProtectionText } from '../shared'
import { VvtField } from './VvtField'

export interface VvtActivityDetailProps {
  activity: Activity
  columns?: readonly RegisterColumn[]
  issues?: readonly RegisterIssue[]
  departments?: readonly string[]
  editing?: boolean
  onFieldChange: (key: string, value: FieldValue) => void
  onRemove: () => void
}

function ReadView({ activity, columns = [], issues = [] }: VvtActivityDetailProps) {
  const { t } = useDataProtectionText()
  const texts = { yes: t('yes'), no: t('no'), empty: t('empty') }
  return (
    <dl className="fa-dataprotection__dl">
      {columns.map((column) => (
        <Fragment key={column.key}>
          <dt>
            {column.title}
            <br />
            <span className="fa-dataprotection__ref">{column.reference}</span>
          </dt>
          <dd>
            {displayValue(activity[column.key], texts)}
            {fieldIssues(issues, activity, column.key).map((issue) => (
              <span key={issue.message} className={classes('fa-dataprotection__note', issue.blocking && 'fa-dataprotection__note--blocking')}>
                <br />
                {issue.message}
              </span>
            ))}
          </dd>
        </Fragment>
      ))}
    </dl>
  )
}

/** Eine Tätigkeit: Felder bearbeiten oder lesen (wie VvtActivityDetail.vue). */
export function VvtActivityDetail(props: VvtActivityDetailProps) {
  const { t } = useDataProtectionText()
  const { activity, columns = [], issues = [], departments = [], editing = false } = props
  const title = (typeof activity.name === 'string' && activity.name.trim()) || t('unnamed')
  return (
    <article className="fa-dataprotection__panel" data-testid="vvt-detail" aria-label={title}>
      <div className="fa-dataprotection__bar">
        <h3>{title}</h3>
        {activity.id ? <span className="fa-dataprotection__muted">{activity.id}</span> : null}
        {editing ? (
          <div className="fa-dataprotection__actions">
            <Button variant="ghost" size="sm" icon="trash" label={t('removeActivity')} onClick={props.onRemove} />
          </div>
        ) : null}
      </div>
      {editing ? (
        <div className="fa-dataprotection__grid">
          {columns.map((column) => (
            <VvtField
              key={column.key}
              column={column}
              value={activity[column.key] ?? null}
              issues={fieldIssues(issues, activity, column.key)}
              departments={departments}
              onValueChange={(value) => props.onFieldChange(column.key, value)}
            />
          ))}
        </div>
      ) : (
        <ReadView {...props} />
      )}
    </article>
  )
}
