// packages-js/ui/src/screening/components/ScreeningReviewTrail.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from '../../i18n'
import { screeningMessages } from '../core'
import type { ReviewView } from '../core'

const props = defineProps<{ review: ReviewView; formatDate: (value: string | null | undefined) => string }>()
const { t } = useI18n(screeningMessages)

const decision = computed(() => {
  const entry = props.review.decision
  if (!entry) return ''
  const line = t('lastDecision', { outcome: t(`status_${entry.outcome}`), actor: entry.actor.display_name, date: props.formatDate(entry.at) })
  const marker = entry.four_eyes ? ` ${t(entry.four_eyes_source === 'policy' ? 'fourEyesMarkerPolicy' : 'fourEyesMarker')}` : ''
  return `${line}${marker} – „${entry.reason}“`
})

const second = computed(() => {
  const entry = props.review.second_review
  if (!entry) return ''
  const result = t(entry.approve ? 'approved' : 'rejected')
  return `${t('secondReviewDone', { result, actor: entry.actor.display_name, date: props.formatDate(entry.at) })} – „${entry.reason}“`
})
</script>

<template>
  <div v-if="decision" class="fa-screening__muted">{{ decision }}</div>
  <div v-if="second" class="fa-screening__muted">{{ second }}</div>
</template>

// packages-js/ui-react/src/screening/ScreeningReviewTrail.tsx
import { formatScreeningDate as formatDate, type ReviewView, type ScreeningTranslate } from '@flowaudit/ui-core'
import { codeKey, useScreeningText } from './shared'

function decisionLine(review: ReviewView, t: ScreeningTranslate): string {
  const entry = review.decision
  if (!entry) return ''
  const line = t('lastDecision', { outcome: t(codeKey('status', entry.outcome)), actor: entry.actor.display_name, date: formatDate(entry.at) })
  const marker = entry.four_eyes ? ` ${t(entry.four_eyes_source === 'policy' ? 'fourEyesMarkerPolicy' : 'fourEyesMarker')}` : ''
  return `${line}${marker} – „${entry.reason}“`
}

function secondLine(review: ReviewView, t: ScreeningTranslate): string {
  const entry = review.second_review
  if (!entry) return ''
  const result = t(entry.approve ? 'approved' : 'rejected')
  return `${t('secondReviewDone', { result, actor: entry.actor.display_name, date: formatDate(entry.at) })} – „${entry.reason}“`
}

/** Letzte Entscheidung und Zweitprüfung eines Treffers. */
export function ScreeningReviewTrail({ review }: { review: ReviewView }) {
  const { t } = useScreeningText()
  const decision = decisionLine(review, t)
  const second = secondLine(review, t)
  return (
    <>
      {decision ? <div className="fa-screening__muted">{decision}</div> : null}
      {second ? <div className="fa-screening__muted">{second}</div> : null}
    </>
  )
}
