// packages-js/bpmn-vue/src/components/dialogs/EsiDialog.vue
<script setup lang="ts">
/** ESI requirements per element (legacy `EsiRequirementsDialog`), loaded through the ESI port. */
import { computed, ref, watch } from 'vue'
import { groupByElement, summarize, type EsiPort, type EsiRequirementResult } from '@auditcore/bpmn-flowaudit'
import { ESI_STATUS as STATUS, loadEsi } from '@auditcore/bpmn-flowaudit/ui'
import BaseDialog from '../base/BaseDialog.vue'
import FaIcon from '../base/FaIcon.vue'
import { useI18n } from '../../i18n/useI18n'

const props = defineProps<{ open: boolean; port?: EsiPort; xml: () => Promise<string>; diagramId?: string }>()
const emit = defineEmits<{ (e: 'update:open', value: boolean): void; (e: 'jump', elementId: string): void }>()
const { t } = useI18n()
const list = ref<EsiRequirementResult[]>([])
const loading = ref(false)
const error = ref<string | null>(null)

const groups = computed(() => groupByElement(list.value))
const summary = computed(() => summarize(list.value))

async function load(): Promise<void> {
  if (!props.port) return
  loading.value = true
  error.value = null
  try {
    list.value = await loadEsi(props.port, props.xml, props.diagramId)
  } catch (caught) {
    error.value = (caught as Error).message
  } finally {
    loading.value = false
  }
}

watch(
  () => props.open,
  (open) => open && load(),
  { immediate: true },
)
</script>

<template>
  <BaseDialog :open="open" :title="t('esi.title')" :subtitle="t('esi.subtitle')" width="760px" @update:open="emit('update:open', $event)">
    <p v-if="!port" class="fa-help">{{ t('esi.noPort') }}</p>
    <template v-else>
      <div class="fa-esi__summary">
        <span class="fa-badge">{{ t('esi.total') }} {{ summary.total }}</span>
        <span class="fa-badge fa-badge--success">{{ t('esi.fulfilled') }} {{ summary.fulfilled }}</span>
        <span class="fa-badge fa-badge--warning">{{ t('esi.unclear') }} {{ summary.unclear }}</span>
        <span class="fa-badge fa-badge--danger">{{ t('esi.missing') }} {{ summary.missing }}</span>
        <button type="button" class="fa-btn fa-btn--ghost" :disabled="loading" @click="load">{{ loading ? t('common.loading') : t('esi.reload') }}</button>
      </div>
      <p v-if="error" class="fa-badge fa-badge--danger">{{ error }}</p>
      <p v-else-if="!loading && !groups.length" class="fa-help">{{ t('esi.none') }}</p>
      <section v-for="group in groups" :key="group.elementId" class="fa-card fa-esi__group">
        <header class="fa-esi__head">
          <div>
            <strong>{{ group.elementName }}</strong>
            <span class="fa-help"> · {{ group.elementId }} · {{ group.fulfilledCount }}/{{ group.totalCount }}</span>
          </div>
          <button type="button" class="fa-btn fa-btn--ghost" @click="(emit('jump', group.elementId), emit('update:open', false))">{{ t('issues.jump') }}</button>
        </header>
        <ul class="fa-esi__list">
          <li v-for="item in group.requirements" :key="item.requirementId">
            <span class="fa-badge" :class="STATUS[item.status].badge"><FaIcon :name="STATUS[item.status].icon" :size="12" />{{ t(STATUS[item.status].label) }}</span>
            <span>{{ item.description }}</span>
            <span v-if="item.expected !== null" class="fa-help">{{ t('esi.expected') }}: {{ item.expected }}</span>
            <span v-if="item.actual !== null" class="fa-help">{{ t('esi.actual') }}: {{ item.actual }}</span>
            <span v-else-if="item.expected !== null" class="fa-help">{{ t('esi.actualMissing') }}</span>
          </li>
        </ul>
      </section>
    </template>
  </BaseDialog>
</template>

// packages-js/bpmn-react/src/dialogs/EsiDialog.tsx
/** ESI requirements per element (legacy `EsiRequirementsDialog`), loaded through the ESI port. */

import { useCallback, useEffect, useMemo, useState } from 'react'
import { groupByElement, summarize, type EsiPort, type EsiRequirementResult } from '@auditcore/bpmn-flowaudit'
import { ESI_STATUS, loadEsi } from '@auditcore/bpmn-flowaudit/ui'
import { BaseDialog } from '../base/BaseDialog'
import { FaIcon } from '../base/FaIcon'
import { useI18n } from '../i18n'

export interface EsiDialogProps {
  open: boolean
  port?: EsiPort
  xml: () => Promise<string>
  diagramId?: string
  onOpenChange: (open: boolean) => void
  onJump: (elementId: string) => void
}

function Requirement({ item }: { item: EsiRequirementResult }) {
  const { t } = useI18n()
  const status = ESI_STATUS[item.status]
  return (
    <li>
      <span className={`fa-badge ${status.badge}`}><FaIcon name={status.icon} size={12} />{t(status.label)}</span>
      <span>{item.description}</span>
      {item.expected !== null ? <span className="fa-help">{t('esi.expected')}: {item.expected}</span> : null}
      {item.actual !== null ? <span className="fa-help">{t('esi.actual')}: {item.actual}</span> : item.expected !== null ? <span className="fa-help">{t('esi.actualMissing')}</span> : null}
    </li>
  )
}

type Group = ReturnType<typeof groupByElement>[number]

function EsiGroup({ group, onJump }: { group: Group; onJump: () => void }) {
  const { t } = useI18n()
  return (
    <section className="fa-card fa-esi__group">
      <header className="fa-esi__head">
        <div>
          <strong>{group.elementName}</strong>
          <span className="fa-help"> · {group.elementId} · {group.fulfilledCount}/{group.totalCount}</span>
        </div>
        <button type="button" className="fa-btn fa-btn--ghost" onClick={onJump}>{t('issues.jump')}</button>
      </header>
      <ul className="fa-esi__list">
        {group.requirements.map((item) => <Requirement key={item.requirementId} item={item} />)}
      </ul>
    </section>
  )
}

function useEsi(open: boolean, port: EsiPort | undefined, xml: () => Promise<string>, diagramId?: string) {
  const [list, setList] = useState<EsiRequirementResult[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => {
    if (!port) return
    setLoading(true)
    setError(null)
    try {
      setList(await loadEsi(port, xml, diagramId))
    } catch (caught) {
      setError((caught as Error).message)
    } finally {
      setLoading(false)
    }
  }, [port, xml, diagramId])
  useEffect(() => {
    if (open) void load()
  }, [open, load])
  return { list, loading, error, load }
}

export function EsiDialog({ open, port, xml, diagramId, onOpenChange, onJump }: EsiDialogProps) {
  const { t } = useI18n()
  const { list, loading, error, load } = useEsi(open, port, xml, diagramId)
  const groups = useMemo(() => groupByElement(list), [list])
  const summary = useMemo(() => summarize(list), [list])
  const jump = (id: string) => {
    onJump(id)
    onOpenChange(false)
  }

  return (
    <BaseDialog open={open} title={t('esi.title')} subtitle={t('esi.subtitle')} width="760px" onOpenChange={onOpenChange}>
      {!port ? (
        <p className="fa-help">{t('esi.noPort')}</p>
      ) : (
        <>
          <div className="fa-esi__summary">
            <span className="fa-badge">{t('esi.total')} {summary.total}</span>
            <span className="fa-badge fa-badge--success">{t('esi.fulfilled')} {summary.fulfilled}</span>
            <span className="fa-badge fa-badge--warning">{t('esi.unclear')} {summary.unclear}</span>
            <span className="fa-badge fa-badge--danger">{t('esi.missing')} {summary.missing}</span>
            <button type="button" className="fa-btn fa-btn--ghost" disabled={loading} onClick={() => void load()}>{loading ? t('common.loading') : t('esi.reload')}</button>
          </div>
          {error ? <p className="fa-badge fa-badge--danger">{error}</p> : !loading && !groups.length ? <p className="fa-help">{t('esi.none')}</p> : null}
          {groups.map((group) => <EsiGroup key={group.elementId} group={group} onJump={() => jump(group.elementId)} />)}
        </>
      )}
    </BaseDialog>
  )
}
