// packages-js/bpmn-vue/src/components/dialogs/ShortcutHelp.vue
<script setup lang="ts">
/** Keyboard shortcut help (declarative table). */
import BaseDialog from '../base/BaseDialog.vue'
import { SHORTCUTS } from '@auditcore/bpmn-flowaudit/ui'
import { useI18n } from '../../i18n/useI18n'

defineProps<{ open: boolean }>()
const emit = defineEmits<{ (e: 'update:open', value: boolean): void }>()
const { t } = useI18n()

</script>

<template>
  <BaseDialog :open="open" :title="t('shortcuts.title')" width="480px" @update:open="emit('update:open', $event)">
    <table class="fa-table">
      <tbody>
        <tr v-for="[keys, label] in SHORTCUTS" :key="label">
          <td class="fa-shortcut__keys">
            <kbd v-for="(key, index) in keys" :key="index" class="fa-kbd">{{ key.startsWith('@') ? t(`key.${key.slice(1)}`) : key }}</kbd>
          </td>
          <td>{{ t(label) }}</td>
        </tr>
      </tbody>
    </table>
  </BaseDialog>
</template>

// packages-js/bpmn-react/src/dialogs/ShortcutHelp.tsx
/** Keyboard shortcut help (declarative table). */

import { SHORTCUTS } from '@auditcore/bpmn-flowaudit/ui'
import { BaseDialog } from '../base/BaseDialog'
import { useI18n } from '../i18n'

export function ShortcutHelp({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const { t } = useI18n()
  return (
    <BaseDialog open={open} title={t('shortcuts.title')} width="480px" onOpenChange={onOpenChange}>
      <table className="fa-table">
        <tbody>
          {SHORTCUTS.map(([keys, label]) => (
            <tr key={label}>
              <td className="fa-shortcut__keys">
                {keys.map((key, index) => <kbd key={index} className="fa-kbd">{key.startsWith('@') ? t(`key.${key.slice(1)}`) : key}</kbd>)}
              </td>
              <td>{t(label)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </BaseDialog>
  )
}
