// packages-js/bpmn-vue/src/components/toolbar/EditorToolbar.vue
<script setup lang="ts">
/**
 * Toolbar in one row with groups File · Edit · View · Check · Modes (legacy
 * `BpmnToolbar`): name, unsaved/readonly state, save, colour menu, flow
 * direction, page view and panel toggles. Actions are emitted as `action`.
 */
import { PALETTE_COLORS, type PaletteColor } from '@auditcore/bpmn-flowaudit'
import { actionDisabled, CHECK_ACTIONS, EDIT_ACTIONS, FILE_ACTIONS, MODE_ACTIONS, PAGE_OPTIONS as pageOptions, VIEW_ACTIONS, type ToolbarAction } from '@auditcore/bpmn-flowaudit/ui'
import ColorSwatches from '../base/ColorSwatches.vue'
import FaIcon from '../base/FaIcon.vue'
import ToolbarMenu from '../base/ToolbarMenu.vue'
import { useI18n } from '../../i18n/useI18n'

const props = defineProps<{
  name: string
  dirty: boolean
  saving: boolean
  readonly: boolean
  canUndo: boolean
  canRedo: boolean
  direction: 'waagerecht' | 'senkrecht'
  pageView: string
  active: Partial<Record<ToolbarAction, boolean>>
  hidden?: ToolbarAction[]
  palette?: readonly PaletteColor[]
}>()
const emit = defineEmits<{
  (e: 'action', action: ToolbarAction): void
  (e: 'update:name', value: string): void
  (e: 'color', color: PaletteColor | null): void
  (e: 'direction', value: 'waagerecht' | 'senkrecht'): void
  (e: 'page-view', value: string): void
  (e: 'import-file', file: File): void
}>()
const { t } = useI18n()


const visible = (id: ToolbarAction) => !props.hidden?.includes(id)
const disabled = (id: ToolbarAction, writes?: boolean) => actionDisabled(id, writes, props)

function onFile(event: Event): void {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  if (file) emit('import-file', file)
  input.value = ''
}
</script>

<template>
  <div class="fa-toolbar" role="toolbar" :aria-label="t('toolbar.label')">
    <button type="button" class="fa-icon-btn" :aria-pressed="active['left-panel']" :aria-label="t('toolbar.leftPanel')" :title="t('toolbar.leftPanel')" @click="emit('action', 'left-panel')">
      <FaIcon name="panel-left" />
    </button>
    <input class="fa-input fa-toolbar__name" :value="name" :aria-label="t('props.name')" :readonly="readonly" @change="emit('update:name', ($event.target as HTMLInputElement).value)" />
    <span v-if="dirty" class="fa-badge fa-badge--warning">{{ t('editor.unsaved') }}</span>
    <span v-if="readonly" class="fa-badge fa-badge--info"><FaIcon name="lock" :size="12" />{{ t('editor.readonly') }}</span>
    <button type="button" class="fa-btn fa-btn--primary" :disabled="saving || readonly" @click="emit('action', 'save')">
      <FaIcon name="save" :size="16" />{{ t('toolbar.save') }}
    </button>
    <span class="fa-toolbar__sep" />
    <template v-for="entry in FILE_ACTIONS" :key="entry.id">
      <label v-if="entry.id === 'import' && visible('import')" class="fa-icon-btn" :title="t(entry.label)" :aria-disabled="readonly">
        <FaIcon :name="entry.icon" /><span class="fa-sr-only">{{ t(entry.label) }}</span>
        <input type="file" accept=".bpmn,.xml" class="fa-sr-only" :disabled="readonly" @change="onFile" />
      </label>
      <button v-else-if="visible(entry.id)" type="button" class="fa-icon-btn" :aria-label="t(entry.label)" :title="t(entry.label)" @click="emit('action', entry.id)">
        <FaIcon :name="entry.icon" />
      </button>
    </template>
    <span class="fa-toolbar__sep" />
    <button v-for="entry in EDIT_ACTIONS" :key="entry.id" type="button" class="fa-icon-btn" :disabled="disabled(entry.id, entry.writes)" :aria-label="t(entry.label)" :title="t(entry.label)" @click="emit('action', entry.id)">
      <FaIcon :name="entry.icon" />
    </button>
    <ToolbarMenu v-slot="{ close }" :label="t('toolbar.color')" icon="color">
      <p class="fa-menu-hint">{{ t('toolbar.colorHint') }}</p>
      <ColorSwatches :colors="palette ?? PALETTE_COLORS" :disabled="readonly" @choose="(color) => (emit('color', color), close())" />
    </ToolbarMenu>
    <div class="fa-segmented" role="group" :aria-label="t('toolbar.direction')">
      <button type="button" class="fa-icon-btn" :aria-pressed="direction === 'waagerecht'" :title="t('toolbar.horizontal')" :aria-label="t('toolbar.horizontal')" :disabled="readonly" @click="emit('direction', 'waagerecht')"><FaIcon name="horizontal" /></button>
      <button type="button" class="fa-icon-btn" :aria-pressed="direction === 'senkrecht'" :title="t('toolbar.vertical')" :aria-label="t('toolbar.vertical')" :disabled="readonly" @click="emit('direction', 'senkrecht')"><FaIcon name="vertical" /></button>
    </div>
    <span class="fa-toolbar__sep" />
    <button v-for="entry in VIEW_ACTIONS" :key="entry.id" type="button" class="fa-icon-btn" :aria-label="t(entry.label)" :title="t(entry.label)" @click="emit('action', entry.id)">
      <FaIcon :name="entry.icon" />
    </button>
    <select class="fa-select fa-toolbar__page" :value="pageView" :aria-label="t('toolbar.pageView')" @change="emit('page-view', ($event.target as HTMLSelectElement).value)">
      <option value="aus">{{ t('toolbar.pageOff') }}</option>
      <option v-for="option in pageOptions" :key="option.value" :value="option.value">{{ option.label }}</option>
    </select>
    <span class="fa-toolbar__sep" />
    <ToolbarMenu v-slot="{ close }" :label="t('toolbar.check')" icon="validate" show-label>
      <template v-for="entry in CHECK_ACTIONS" :key="entry.id">
        <button v-if="visible(entry.id)" type="button" role="menuitem" class="fa-menu-item" :disabled="disabled(entry.id, entry.writes)" @click="(emit('action', entry.id), close())">
          <FaIcon :name="entry.icon" />
          <span>{{ t(entry.label) }}<span v-if="entry.hint" class="fa-menu-hint">{{ t(entry.hint) }}</span></span>
        </button>
      </template>
    </ToolbarMenu>
    <div class="fa-toolbar__modes">
      <template v-for="entry in MODE_ACTIONS" :key="entry.id">
        <button v-if="visible(entry.id)" type="button" class="fa-icon-btn" :aria-pressed="Boolean(active[entry.id])" :aria-label="t(entry.label)" :title="t(entry.label)" @click="emit('action', entry.id)">
          <FaIcon :name="entry.icon" />
        </button>
      </template>
    </div>
    <span class="fa-toolbar__spacer" />
    <button type="button" class="fa-icon-btn" :aria-label="t('toolbar.theme')" :title="t('toolbar.theme')" @click="emit('action', 'theme')"><FaIcon name="moon" /></button>
    <button type="button" class="fa-icon-btn" :aria-pressed="active['right-panel']" :aria-label="t('toolbar.rightPanel')" :title="t('toolbar.rightPanel')" @click="emit('action', 'right-panel')">
      <FaIcon name="panel-right" />
    </button>
  </div>
</template>

// packages-js/bpmn-react/src/toolbar/EditorToolbar.tsx
/**
 * Toolbar in one row with groups File · Edit · View · Check · Modes (legacy
 * `BpmnToolbar`): name, unsaved/readonly state, save, colour menu, flow
 * direction, page view and panel toggles. Actions are reported as `onAction`.
 */

import type { ChangeEvent } from 'react'
import { PALETTE_COLORS, type Direction, type PaletteColor } from '@auditcore/bpmn-flowaudit'
import { actionDisabled, FILE_ACTIONS, PAGE_OPTIONS, VIEW_ACTIONS, type ToolbarAction } from '@auditcore/bpmn-flowaudit/ui'
import { ColorSwatches } from '../base/ColorSwatches'
import { FaIcon } from '../base/FaIcon'
import { ToolbarMenu } from '../base/ToolbarMenu'
import { useI18n } from '../i18n'
import { CheckMenu, EditButtons, ModeButtons, NameField } from './ToolbarParts'

export interface EditorToolbarProps {
  name: string
  dirty: boolean
  saving: boolean
  readonly: boolean
  canUndo: boolean
  canRedo: boolean
  direction: Direction
  pageView: string
  active: Partial<Record<ToolbarAction, boolean>>
  hidden?: ToolbarAction[]
  palette?: readonly PaletteColor[]
  onAction: (action: ToolbarAction) => void
  onNameChange?: (value: string) => void
  onColor?: (color: PaletteColor | null) => void
  onDirection?: (value: Direction) => void
  onPageView?: (value: string) => void
  onImportFile?: (file: File) => void
}

function FileActions({ props }: { props: EditorToolbarProps }) {
  const { t } = useI18n()
  const visible = (id: ToolbarAction) => !props.hidden?.includes(id)
  const onFile = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (file) props.onImportFile?.(file)
    event.target.value = ''
  }
  return FILE_ACTIONS.map((entry) => {
    if (entry.id === 'import') {
      return visible('import') ? (
        <label key={entry.id} className="fa-icon-btn" title={t(entry.label)} aria-disabled={props.readonly}>
          <FaIcon name={entry.icon} />
          <span className="fa-sr-only">{t(entry.label)}</span>
          <input type="file" accept=".bpmn,.xml" className="fa-sr-only" disabled={props.readonly} onChange={onFile} />
        </label>
      ) : null
    }
    return visible(entry.id) ? (
      <button key={entry.id} type="button" className="fa-icon-btn" aria-label={t(entry.label)} title={t(entry.label)} onClick={() => props.onAction(entry.id)}>
        <FaIcon name={entry.icon} />
      </button>
    ) : null
  })
}

function DirectionGroup({ props }: { props: EditorToolbarProps }) {
  const { t } = useI18n()
  const button = (value: Direction, icon: string, label: string) => (
    <button type="button" className="fa-icon-btn" aria-pressed={props.direction === value} title={t(label)} aria-label={t(label)} disabled={props.readonly} onClick={() => props.onDirection?.(value)}>
      <FaIcon name={icon} />
    </button>
  )
  return (
    <div className="fa-segmented" role="group" aria-label={t('toolbar.direction')}>
      {button('waagerecht', 'horizontal', 'toolbar.horizontal')}
      {button('senkrecht', 'vertical', 'toolbar.vertical')}
    </div>
  )
}

function ViewGroup({ props }: { props: EditorToolbarProps }) {
  const { t } = useI18n()
  return (
    <>
      {VIEW_ACTIONS.map((entry) => (
        <button key={entry.id} type="button" className="fa-icon-btn" aria-label={t(entry.label)} title={t(entry.label)} onClick={() => props.onAction(entry.id)}>
          <FaIcon name={entry.icon} />
        </button>
      ))}
      <select className="fa-select fa-toolbar__page" value={props.pageView} aria-label={t('toolbar.pageView')} onChange={(event) => props.onPageView?.(event.target.value)}>
        <option value="aus">{t('toolbar.pageOff')}</option>
        {PAGE_OPTIONS.map((option) => (
          <option key={option.value} value={option.value}>{option.label}</option>
        ))}
      </select>
    </>
  )
}

export function EditorToolbar(props: EditorToolbarProps) {
  const { t } = useI18n()
  const disabled = (id: ToolbarAction, writes?: boolean) => actionDisabled(id, writes, props)
  return (
    <div className="fa-toolbar" role="toolbar" aria-label={t('toolbar.label')}>
      <button type="button" className="fa-icon-btn" aria-pressed={props.active['left-panel']} aria-label={t('toolbar.leftPanel')} title={t('toolbar.leftPanel')} onClick={() => props.onAction('left-panel')}>
        <FaIcon name="panel-left" />
      </button>
      <NameField name={props.name} readonly={props.readonly} onNameChange={props.onNameChange} />
      {props.dirty ? <span className="fa-badge fa-badge--warning">{t('editor.unsaved')}</span> : null}
      {props.readonly ? <span className="fa-badge fa-badge--info"><FaIcon name="lock" size={12} />{t('editor.readonly')}</span> : null}
      <button type="button" className="fa-btn fa-btn--primary" disabled={props.saving || props.readonly} onClick={() => props.onAction('save')}>
        <FaIcon name="save" size={16} />
        {t('toolbar.save')}
      </button>
      <span className="fa-toolbar__sep" />
      <FileActions props={props} />
      <span className="fa-toolbar__sep" />
      <EditButtons disabled={disabled} onAction={props.onAction} />
      <ToolbarMenu label={t('toolbar.color')} icon="color">
        {(close) => (
          <>
            <p className="fa-menu-hint">{t('toolbar.colorHint')}</p>
            <ColorSwatches colors={props.palette ?? PALETTE_COLORS} disabled={props.readonly} onChoose={(color) => (props.onColor?.(color), close())} />
          </>
        )}
      </ToolbarMenu>
      <DirectionGroup props={props} />
      <span className="fa-toolbar__sep" />
      <ViewGroup props={props} />
      <span className="fa-toolbar__sep" />
      <CheckMenu hidden={props.hidden} disabled={disabled} onAction={props.onAction} />
      <ModeButtons hidden={props.hidden} active={props.active} onAction={props.onAction} />
      <span className="fa-toolbar__spacer" />
      <button type="button" className="fa-icon-btn" aria-label={t('toolbar.theme')} title={t('toolbar.theme')} onClick={() => props.onAction('theme')}>
        <FaIcon name="moon" />
      </button>
      <button type="button" className="fa-icon-btn" aria-pressed={props.active['right-panel']} aria-label={t('toolbar.rightPanel')} title={t('toolbar.rightPanel')} onClick={() => props.onAction('right-panel')}>
        <FaIcon name="panel-right" />
      </button>
    </div>
  )
}
