// packages-js/ui-react/src/dataprotection/dsfa/DsfaScreening.tsx
import { blockProgress, screeningTone, withAnswer, withJustification, type BlockView, type DataProtectionProfile, type Proposal, type SurveyInput } from '@flowaudit/ui-core'
import { Badge } from '../../base/Badge'
import { prefixedLabel, useDataProtectionText } from '../shared'
import { DsfaQuestion } from './DsfaQuestion'

export interface DsfaSurveyProps {
  profile: DataProtectionProfile
  survey: SurveyInput
  proposal?: Proposal | null
  preview?: boolean
  readonly?: boolean
  onSurveyChange: (survey: SurveyInput) => void
}

function Result({ screening, preview }: { screening: Proposal['screening']; preview: boolean }) {
  const { t } = useDataProtectionText()
  const open = screening.unanswered.length + screening.unknown.length
  const summary = [
    t('hardTriggers', { count: screening.hard_triggers.length }),
    t('points', { points: screening.points, threshold: screening.points_threshold }),
    t('openAnswers', { count: open }),
  ].join(' · ')
  return (
    <section className="fa-dataprotection__panel" aria-label={t('screeningResult')}>
      <div className="fa-dataprotection__bar">
        <h3>{t('screeningResult')}</h3>
        <Badge tone={screeningTone(screening.outcome)}>{prefixedLabel(t, 'outcome', screening.outcome)}</Badge>
        {preview ? <Badge tone="accent">{t('preview')}</Badge> : null}
      </div>
      <p aria-live="polite">{screening.reasoning}</p>
      <p className="fa-dataprotection__muted">{summary}</p>
    </section>
  )
}

function Block({ block, props }: { block: BlockView; props: DsfaSurveyProps }) {
  const { t } = useDataProtectionText()
  const { survey, onSurveyChange } = props
  return (
    <section className="fa-dataprotection__panel" aria-label={block.title}>
      <div className="fa-dataprotection__bar">
        <h3>{block.title}</h3>
        <span className="fa-dataprotection__muted">{t('progress', { ...blockProgress(block, survey) })}</span>
      </div>
      {block.questions.map((question) => (
        <DsfaQuestion
          key={question.key}
          question={question}
          answer={survey.answers[question.key] ?? null}
          readonly={props.readonly}
          onAnswer={(value) => onSurveyChange(withAnswer(survey, question.key, value))}
          onJustify={(text) => onSurveyChange(withJustification(survey, question.key, text))}
        />
      ))}
    </section>
  )
}

/** Schwellwertanalyse: Ergebnis der Bibliothek und Fragen je Block. */
export function DsfaScreening(props: DsfaSurveyProps) {
  const screening = props.proposal?.screening ?? null
  return (
    <div data-testid="dsfa-screening">
      {screening ? <Result screening={screening} preview={!!props.preview} /> : null}
      {props.profile.screening.blocks.map((block) => <Block key={block.key} block={block} props={props} />)}
    </div>
  )
}

// packages-js/ui/src/dataprotection/components/DsfaScreening.vue
<script setup lang="ts">
import { computed } from 'vue'
import FaBadge from '../../base/FaBadge.vue'
import { useI18n } from '../../i18n'
import { blockProgress, screeningTone, withAnswer, withJustification } from '../core'
import { dataprotectionMessages } from '../core'
import { prefixedLabel } from '../core'
import type { DataProtectionProfile, Proposal, SurveyInput } from '../core'
import DsfaQuestion from './DsfaQuestion.vue'

const props = withDefaults(defineProps<{
  profile: DataProtectionProfile
  survey: SurveyInput
  proposal?: Proposal | null
  preview?: boolean
  readonly?: boolean
}>(), { proposal: null, preview: false, readonly: false })

const emit = defineEmits<{ 'survey-change': [survey: SurveyInput] }>()
const { t } = useI18n(dataprotectionMessages)
const screening = computed(() => props.proposal?.screening ?? null)
const open = computed(() => (screening.value ? screening.value.unanswered.length + screening.value.unknown.length : 0))
</script>

<template>
  <div data-testid="dsfa-screening">
    <section v-if="screening" class="fa-dataprotection__panel" :aria-label="t('screeningResult')">
      <div class="fa-dataprotection__bar">
        <h3>{{ t('screeningResult') }}</h3>
        <FaBadge :tone="screeningTone(screening.outcome)">{{ prefixedLabel(t, 'outcome', screening.outcome) }}</FaBadge>
        <FaBadge v-if="preview" tone="accent">{{ t('preview') }}</FaBadge>
      </div>
      <p aria-live="polite">{{ screening.reasoning }}</p>
      <p class="fa-dataprotection__muted">
        {{ t('hardTriggers', { count: screening.hard_triggers.length }) }} ·
        {{ t('points', { points: screening.points, threshold: screening.points_threshold }) }} ·
        {{ t('openAnswers', { count: open }) }}
      </p>
    </section>
    <section v-for="block in profile.screening.blocks" :key="block.key" class="fa-dataprotection__panel" :aria-label="block.title">
      <div class="fa-dataprotection__bar">
        <h3>{{ block.title }}</h3>
        <span class="fa-dataprotection__muted">{{ t('progress', { ...blockProgress(block, survey) }) }}</span>
      </div>
      <DsfaQuestion
        v-for="question in block.questions"
        :key="question.key"
        :question="question"
        :answer="survey.answers[question.key] ?? null"
        :readonly="readonly"
        @answer="emit('survey-change', withAnswer(survey, question.key, $event))"
        @justify="emit('survey-change', withJustification(survey, question.key, $event))"
      />
    </section>
  </div>
</template>
