// packages-js/ui-react/src/dataprotection/dsfa/DsfaScenario.tsx
import type { ChangeEvent } from 'react'
import { bandTone, toggleMeasure, type DataProtectionProfile, type LevelView, type ScenarioInput, type ScenarioResult } from '@flowaudit/ui-core'
import { Badge } from '../../base/Badge'
import { Button } from '../../base/Button'
import { classes, useElementId } from '../../store'
import { useDataProtectionText } from '../shared'

export interface DsfaScenarioProps {
  profile: DataProtectionProfile
  scenario: ScenarioInput
  index: number
  result?: ScenarioResult | null
  readonly?: boolean
  onScenarioChange: (scenario: ScenarioInput) => void
  onRemove: () => void
}

type Risk = DataProtectionProfile['risk']

const level = (event: ChangeEvent<HTMLSelectElement>): number | null => (event.target.value === '' ? null : Number(event.target.value))

function Levels({ levels }: { levels: readonly LevelView[] }) {
  return <>{levels.map((entry) => <option key={entry.value} value={entry.value}>{`${entry.value} – ${entry.label}`}</option>)}</>
}

function Base({ id, risk, props, patch }: { id: string; risk: Risk; props: DsfaScenarioProps; patch: (changes: Partial<ScenarioInput>) => void }) {
  const { t } = useDataProtectionText()
  const { scenario } = props
  return (
    <div className="fa-dataprotection__grid">
      <div className="fa-dataprotection__field">
        <label htmlFor={`${id}-dim`}>{t('dimension')}</label>
        <select id={`${id}-dim`} value={scenario.dimension} onChange={(event) => patch({ dimension: event.target.value })}>
          {risk.dimensions.map((dimension) => <option key={dimension.key} value={dimension.key}>{dimension.title}</option>)}
        </select>
      </div>
      <div className="fa-dataprotection__field fa-dataprotection__field--required">
        <label htmlFor={`${id}-text`}>{t('description')}</label>
        <textarea id={`${id}-text`} rows={2} value={scenario.description} onChange={(event) => patch({ description: event.target.value })} />
      </div>
      <div className="fa-dataprotection__field">
        <label htmlFor={`${id}-sev`}>{t('severity')}</label>
        <select id={`${id}-sev`} value={scenario.severity} onChange={(event) => patch({ severity: level(event) ?? scenario.severity })}>
          <Levels levels={risk.severity_levels} />
        </select>
      </div>
      <div className="fa-dataprotection__field">
        <label htmlFor={`${id}-lik`}>{t('likelihood')}</label>
        <select id={`${id}-lik`} value={scenario.likelihood} onChange={(event) => patch({ likelihood: level(event) ?? scenario.likelihood })}>
          <Levels levels={risk.likelihood_levels} />
        </select>
      </div>
    </div>
  )
}

function Measures({ risk, props }: { risk: Risk; props: DsfaScenarioProps }) {
  const { t } = useDataProtectionText()
  return (
    <fieldset className="fa-dataprotection__field">
      <legend>{t('measures')}</legend>
      <ul className="fa-dsfa__measures">
        {risk.measures.map((measure) => (
          <li key={measure.key}>
            <label className="fa-dataprotection__choice">
              <input type="checkbox" checked={props.scenario.measures.includes(measure.key)} onChange={() => props.onScenarioChange(toggleMeasure(props.scenario, measure.key))} /> {measure.title}
            </label>
          </li>
        ))}
      </ul>
    </fieldset>
  )
}

function Residual({ id, risk, scenario, patch }: { id: string; risk: Risk; scenario: ScenarioInput; patch: (changes: Partial<ScenarioInput>) => void }) {
  const { t } = useDataProtectionText()
  const residual = scenario.residual_severity !== null || scenario.residual_likelihood !== null
  return (
    <details open={residual}>
      <summary>{t('residual')}</summary>
      <div className="fa-dataprotection__grid">
        <div className="fa-dataprotection__field">
          <label htmlFor={`${id}-rsev`}>{t('residualSeverity')}</label>
          <select id={`${id}-rsev`} value={scenario.residual_severity ?? ''} onChange={(event) => patch({ residual_severity: level(event) })}>
            <option value="">{t('computed')}</option>
            <Levels levels={risk.severity_levels} />
          </select>
        </div>
        <div className="fa-dataprotection__field">
          <label htmlFor={`${id}-rlik`}>{t('residualLikelihood')}</label>
          <select id={`${id}-rlik`} value={scenario.residual_likelihood ?? ''} onChange={(event) => patch({ residual_likelihood: level(event) })}>
            <option value="">{t('computed')}</option>
            <Levels levels={risk.likelihood_levels} />
          </select>
        </div>
      </div>
      <div className={classes('fa-dataprotection__field', residual && 'fa-dataprotection__field--required')}>
        <label htmlFor={`${id}-why`}>{t('residualJustification')}</label>
        <textarea id={`${id}-why`} rows={2} value={scenario.residual_justification} onChange={(event) => patch({ residual_justification: event.target.value })} />
      </div>
    </details>
  )
}

function Result({ risk, props }: { risk: Risk; props: DsfaScenarioProps }) {
  const { t } = useDataProtectionText()
  const { result } = props
  return (
    <div className="fa-dsfa__result">
      {result ? (
        <>
          <Badge tone={bandTone(result.gross_band, risk.bands)}>{result.gross_band}</Badge>
          <span aria-hidden="true">→</span>
          <Badge tone={bandTone(result.net_band, risk.bands)}>{result.net_band}</Badge>
          <span>{t('scenarioResult', { gross: result.gross, grossBand: result.gross_band, net: result.net, netBand: result.net_band })}</span>
        </>
      ) : null}
      {props.readonly ? null : (
        <Button className="fa-dataprotection__actions" variant="ghost" size="sm" icon="trash" label={t('removeScenario', { index: props.index + 1 })} onClick={props.onRemove} />
      )}
    </div>
  )
}

/** Ein Risikoszenario mit Schwere, Wahrscheinlichkeit, Maßnahmen und optionalem Restrisiko. */
export function DsfaScenario(props: DsfaScenarioProps) {
  const { t } = useDataProtectionText()
  const id = useElementId('fa-dsfa-s')
  const risk = props.profile.risk
  const patch = (changes: Partial<ScenarioInput>): void => props.onScenarioChange({ ...props.scenario, ...changes })
  return (
    <fieldset className="fa-dsfa__scenario" disabled={!!props.readonly} data-scenario={props.index}>
      <legend className="fa-dataprotection__label">{t('scenario', { index: props.index + 1 })}</legend>
      <Base id={id} risk={risk} props={props} patch={patch} />
      <Measures risk={risk} props={props} />
      <Residual id={id} risk={risk} scenario={props.scenario} patch={patch} />
      <Result risk={risk} props={props} />
    </fieldset>
  )
}

// packages-js/ui/src/dataprotection/components/DsfaScenario.vue
<script setup lang="ts">
import { computed } from 'vue'
import FaBadge from '../../base/FaBadge.vue'
import FaButton from '../../base/FaButton.vue'
import { useId } from '../../composables/useId'
import { useI18n } from '../../i18n'
import { bandTone, toggleMeasure } from '../core'
import { dataprotectionMessages } from '../core'
import type { DataProtectionProfile, ScenarioInput, ScenarioResult } from '../core'

const props = withDefaults(defineProps<{
  profile: DataProtectionProfile
  scenario: ScenarioInput
  index: number
  result?: ScenarioResult | null
  readonly?: boolean
}>(), { result: null, readonly: false })

const emit = defineEmits<{ 'scenario-change': [scenario: ScenarioInput]; remove: [] }>()
const { t } = useI18n(dataprotectionMessages)
const id = useId('fa-dsfa-s')
const risk = computed(() => props.profile.risk)
const residual = computed(() => props.scenario.residual_severity !== null || props.scenario.residual_likelihood !== null)

function patch(changes: Partial<ScenarioInput>): void {
  emit('scenario-change', { ...props.scenario, ...changes })
}

function level(event: Event): number | null {
  const raw = (event.target as HTMLSelectElement).value
  return raw === '' ? null : Number(raw)
}
</script>

<template>
  <fieldset class="fa-dsfa__scenario" :disabled="readonly" :data-scenario="index">
    <legend class="fa-dataprotection__label">{{ t('scenario', { index: index + 1 }) }}</legend>
    <div class="fa-dataprotection__grid">
      <div class="fa-dataprotection__field">
        <label :for="`${id}-dim`">{{ t('dimension') }}</label>
        <select :id="`${id}-dim`" :value="scenario.dimension" @change="patch({ dimension: ($event.target as HTMLSelectElement).value })">
          <option v-for="dimension in risk.dimensions" :key="dimension.key" :value="dimension.key">{{ dimension.title }}</option>
        </select>
      </div>
      <div class="fa-dataprotection__field fa-dataprotection__field--required">
        <label :for="`${id}-text`">{{ t('description') }}</label>
        <textarea :id="`${id}-text`" rows="2" :value="scenario.description" @input="patch({ description: ($event.target as HTMLTextAreaElement).value })" />
      </div>
      <div class="fa-dataprotection__field">
        <label :for="`${id}-sev`">{{ t('severity') }}</label>
        <select :id="`${id}-sev`" :value="scenario.severity" @change="patch({ severity: level($event) ?? scenario.severity })">
          <option v-for="entry in risk.severity_levels" :key="entry.value" :value="entry.value">{{ entry.value }} – {{ entry.label }}</option>
        </select>
      </div>
      <div class="fa-dataprotection__field">
        <label :for="`${id}-lik`">{{ t('likelihood') }}</label>
        <select :id="`${id}-lik`" :value="scenario.likelihood" @change="patch({ likelihood: level($event) ?? scenario.likelihood })">
          <option v-for="entry in risk.likelihood_levels" :key="entry.value" :value="entry.value">{{ entry.value }} – {{ entry.label }}</option>
        </select>
      </div>
    </div>
    <fieldset class="fa-dataprotection__field">
      <legend>{{ t('measures') }}</legend>
      <ul class="fa-dsfa__measures">
        <li v-for="measure in risk.measures" :key="measure.key">
          <label class="fa-dataprotection__choice">
            <input type="checkbox" :checked="scenario.measures.includes(measure.key)" @change="emit('scenario-change', toggleMeasure(scenario, measure.key))" />
            {{ measure.title }}
          </label>
        </li>
      </ul>
    </fieldset>
    <details :open="residual">
      <summary>{{ t('residual') }}</summary>
      <div class="fa-dataprotection__grid">
        <div class="fa-dataprotection__field">
          <label :for="`${id}-rsev`">{{ t('residualSeverity') }}</label>
          <select :id="`${id}-rsev`" :value="scenario.residual_severity ?? ''" @change="patch({ residual_severity: level($event) })">
            <option value="">{{ t('computed') }}</option>
            <option v-for="entry in risk.severity_levels" :key="entry.value" :value="entry.value">{{ entry.value }} – {{ entry.label }}</option>
          </select>
        </div>
        <div class="fa-dataprotection__field">
          <label :for="`${id}-rlik`">{{ t('residualLikelihood') }}</label>
          <select :id="`${id}-rlik`" :value="scenario.residual_likelihood ?? ''" @change="patch({ residual_likelihood: level($event) })">
            <option value="">{{ t('computed') }}</option>
            <option v-for="entry in risk.likelihood_levels" :key="entry.value" :value="entry.value">{{ entry.value }} – {{ entry.label }}</option>
          </select>
        </div>
      </div>
      <div class="fa-dataprotection__field" :class="{ 'fa-dataprotection__field--required': residual }">
        <label :for="`${id}-why`">{{ t('residualJustification') }}</label>
        <textarea :id="`${id}-why`" rows="2" :value="scenario.residual_justification" @input="patch({ residual_justification: ($event.target as HTMLTextAreaElement).value })" />
      </div>
    </details>
    <div class="fa-dsfa__result">
      <template v-if="result">
        <FaBadge :tone="bandTone(result.gross_band, risk.bands)">{{ result.gross_band }}</FaBadge>
        <span aria-hidden="true">→</span>
        <FaBadge :tone="bandTone(result.net_band, risk.bands)">{{ result.net_band }}</FaBadge>
        <span>{{ t('scenarioResult', { gross: result.gross, grossBand: result.gross_band, net: result.net, netBand: result.net_band }) }}</span>
      </template>
      <FaButton v-if="!readonly" class="fa-dataprotection__actions" variant="ghost" size="sm" icon="trash" :label="t('removeScenario', { index: index + 1 })" @click="emit('remove')" />
    </div>
  </fieldset>
</template>
