// packages-js/ui-react/src/dataprotection/vvt/VvtActivityList.tsx
import { Fragment, useState } from 'react'
import {
  completeness,
  completenessTone,
  groupByDepartment,
  issuesFor,
  type Activity,
  type Completeness,
  type DataProtectionTranslate,
  type RegisterContent,
  type RegisterIssue,
} from '@auditcore/ui-core'
import { Badge } from '../../base/Badge'
import { Button } from '../../base/Button'
import { TextField } from '../../base/TextField'
import { useElementId } from '../../store'
import { useDataProtectionText } from '../shared'

export interface VvtActivityListProps {
  content: RegisterContent
  issues?: readonly RegisterIssue[]
  selected?: number | null
  editing?: boolean
  onActivitySelect: (index: number) => void
  onAdd: (department: string) => void
}

function stateLabel(t: DataProtectionTranslate, value: Completeness): string {
  if (value.blocking) return value.blocking === 1 ? t('missingOne') : t('missing', { count: value.blocking })
  if (value.hints) return value.hints === 1 ? t('hintOne') : t('hints', { count: value.hints })
  return t('complete')
}

function name(t: DataProtectionTranslate, activity: Activity): string {
  return (typeof activity.name === 'string' && activity.name.trim()) || t('unnamed')
}

function AddActivity({ content, onAdd }: VvtActivityListProps) {
  const { t } = useDataProtectionText()
  const selectId = useElementId('fa-vvt-department')
  const [department, setDepartment] = useState('')
  return (
    <div className="fa-dataprotection__field">
      <label htmlFor={selectId}>{t('colDepartment')}</label>
      <select id={selectId} value={department} onChange={(event) => setDepartment(event.target.value)}>
        <option value="">{t('withoutDepartment')}</option>
        {content.referate.map((entry) => <option key={entry} value={entry}>{entry}</option>)}
      </select>
      <Button icon="plus" label={t('addActivity')} onClick={() => onAdd(department)} />
    </div>
  )
}

/** Tätigkeiten je Referat mit Suche und Vollständigkeit (wie VvtActivityList.vue). */
export function VvtActivityList(props: VvtActivityListProps) {
  const { t } = useDataProtectionText()
  const { content, issues = [], selected = null } = props
  const [query, setQuery] = useState('')
  const groups = groupByDepartment(content, query)
  const heading = t('activities', { count: content.taetigkeiten.length })
  const state = (activity: Activity): Completeness => completeness(issuesFor(issues, activity))
  return (
    <nav className="fa-dataprotection__panel" aria-label={heading} data-testid="vvt-list">
      <h3>{heading}</h3>
      <TextField value={query} onChange={setQuery} type="search" label={t('search')} hideLabel placeholder={t('search')} />
      {!content.taetigkeiten.length ? <p className="fa-dataprotection__muted">{t('noActivities')}</p> : null}
      {content.taetigkeiten.length && !groups.length ? <p className="fa-dataprotection__muted">{t('noMatches')}</p> : null}
      {groups.map((group) => (
        <Fragment key={group.department}>
          <h4>{group.department || t('withoutDepartment')}</h4>
          <ul className="fa-vvt__list">
            {group.items.map((item) => (
              <li key={item.index}>
                <button type="button" className="fa-vvt__item" aria-current={item.index === selected ? 'true' : undefined} onClick={() => props.onActivitySelect(item.index)}>
                  <span>{name(t, item.activity)}</span>
                  <Badge tone={completenessTone(state(item.activity))}>{stateLabel(t, state(item.activity))}</Badge>
                </button>
              </li>
            ))}
          </ul>
        </Fragment>
      ))}
      {props.editing ? <AddActivity {...props} /> : null}
    </nav>
  )
}

// packages-js/ui/src/dataprotection/components/VvtActivityList.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import FaBadge from '../../base/FaBadge.vue'
import FaButton from '../../base/FaButton.vue'
import FaTextField from '../../base/FaTextField.vue'
import { useId } from '../../composables/useId'
import { useI18n } from '../../i18n'
import { dataprotectionMessages } from '../core'
import { completeness, completenessTone, groupByDepartment, issuesFor, type Completeness } from '../core'
import type { Activity, Issue, RegisterContent } from '../core'

const props = withDefaults(defineProps<{
  content: RegisterContent
  issues?: Issue[]
  selected?: number | null
  editing?: boolean
}>(), { issues: () => [], selected: null, editing: false })

const emit = defineEmits<{ 'activity-select': [index: number]; add: [department: string] }>()
const { t } = useI18n(dataprotectionMessages)
const query = ref('')
const department = ref('')
const selectId = useId('fa-vvt-department')
const groups = computed(() => groupByDepartment(props.content, query.value))

function state(activity: Activity): Completeness {
  return completeness(issuesFor(props.issues, activity))
}

function stateLabel(value: Completeness): string {
  if (value.blocking) return value.blocking === 1 ? t('missingOne') : t('missing', { count: value.blocking })
  if (value.hints) return value.hints === 1 ? t('hintOne') : t('hints', { count: value.hints })
  return t('complete')
}

function name(activity: Activity): string {
  return (typeof activity.name === 'string' && activity.name.trim()) || t('unnamed')
}
</script>

<template>
  <nav class="fa-dataprotection__panel" :aria-label="t('activities', { count: content.taetigkeiten.length })" data-testid="vvt-list">
    <h3>{{ t('activities', { count: content.taetigkeiten.length }) }}</h3>
    <FaTextField v-model="query" type="search" :label="t('search')" hide-label :placeholder="t('search')" />
    <p v-if="!content.taetigkeiten.length" class="fa-dataprotection__muted">{{ t('noActivities') }}</p>
    <p v-else-if="!groups.length" class="fa-dataprotection__muted">{{ t('noMatches') }}</p>
    <template v-for="group in groups" :key="group.department">
      <h4>{{ group.department || t('withoutDepartment') }}</h4>
      <ul class="fa-vvt__list">
        <li v-for="item in group.items" :key="item.index">
          <button
            type="button"
            class="fa-vvt__item"
            :aria-current="item.index === selected ? 'true' : undefined"
            @click="emit('activity-select', item.index)"
          >
            <span>{{ name(item.activity) }}</span>
            <FaBadge :tone="completenessTone(state(item.activity))">{{ stateLabel(state(item.activity)) }}</FaBadge>
          </button>
        </li>
      </ul>
    </template>
    <div v-if="editing" class="fa-dataprotection__field">
      <label :for="selectId">{{ t('colDepartment') }}</label>
      <select :id="selectId" v-model="department">
        <option value="">{{ t('withoutDepartment') }}</option>
        <option v-for="entry in content.referate" :key="entry" :value="entry">{{ entry }}</option>
      </select>
      <FaButton icon="plus" :label="t('addActivity')" @click="emit('add', department)" />
    </div>
  </nav>
</template>
