// packages-js/ui-react/src/dataprotection/vvt/VvtField.tsx
import { useEffect, useState, type ChangeEvent } from 'react'
import { parseCount, type FieldValue, type RegisterColumn, type RegisterIssue } from '@auditcore/ui-core'
import { classes, useElementId } from '../../store'
import { useDataProtectionText } from '../shared'

export interface VvtFieldProps {
  column: RegisterColumn
  value?: FieldValue
  issues?: readonly RegisterIssue[]
  departments?: readonly string[]
  onValueChange: (value: FieldValue) => void
}

const SHORT_FIELDS = ['name', 'referat', 'ansprechperson']
const CHOICES = ['yes', 'no', 'open'] as const

function flagValue(choice: (typeof CHOICES)[number]): boolean | null {
  return choice === 'yes' ? true : choice === 'no' ? false : null
}

function Notes({ id, issues, countError }: { id: string; issues: readonly RegisterIssue[]; countError?: boolean }) {
  const { t } = useDataProtectionText()
  if (!issues.length && !countError) return null
  return (
    <div id={id}>
      {countError ? <p className="fa-dataprotection__note fa-dataprotection__note--blocking">{t('invalidCount')}</p> : null}
      {issues.map((issue) => (
        <p key={issue.code + issue.message} className={classes('fa-dataprotection__note', issue.blocking && 'fa-dataprotection__note--blocking')}>{issue.message}</p>
      ))}
    </div>
  )
}

function FlagField({ column, value = null, issues = [], onValueChange }: VvtFieldProps) {
  const { t } = useDataProtectionText()
  const id = useElementId('fa-vvt-field')
  const blocking = issues.some((issue) => issue.blocking)
  return (
    <fieldset className={classes('fa-dataprotection__field', column.required && 'fa-dataprotection__field--required')} aria-describedby={issues.length ? `${id}-note` : undefined}>
      <legend>{column.title}</legend>
      <div className="fa-dataprotection__choices">
        {CHOICES.map((choice) => (
          <label key={choice} className="fa-dataprotection__choice">
            <input type="radio" name={id} checked={value === flagValue(choice)} aria-invalid={blocking ? 'true' : undefined} onChange={() => onValueChange(flagValue(choice))} /> {t(choice)}
          </label>
        ))}
      </div>
      {column.reference ? <span className="fa-dataprotection__ref">{column.reference}</span> : null}
      <Notes id={`${id}-note`} issues={issues} />
    </fieldset>
  )
}

function useCount(value: FieldValue, onValueChange: (value: FieldValue) => void) {
  const [text, setText] = useState(value === null || value === undefined ? '' : String(value))
  const [error, setError] = useState(false)
  useEffect(() => {
    setText(value === null || value === undefined ? '' : String(value))
    setError(false)
  }, [value])
  function change(event: ChangeEvent<HTMLInputElement>): void {
    setText(event.target.value)
    const parsed = parseCount(event.target.value)
    setError(parsed === undefined)
    if (parsed !== undefined) onValueChange(parsed)
  }
  return { text, error, change }
}

function Control({ id, column, value, blocking, described, count, departments, onText }: {
  id: string; column: RegisterColumn; value: FieldValue; blocking: boolean; described: string | undefined
  count: ReturnType<typeof useCount>; departments: readonly string[]; onText: (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void
}) {
  const text = typeof value === 'string' ? value : ''
  if (column.kind === 'count') {
    return <input id={id} type="text" inputMode="numeric" value={count.text} aria-invalid={blocking || count.error ? 'true' : undefined} aria-describedby={described} onChange={count.change} />
  }
  if (!SHORT_FIELDS.includes(column.key)) {
    return <textarea id={id} rows={2} value={text} required={column.required} aria-invalid={blocking ? 'true' : undefined} aria-describedby={described} onChange={onText} />
  }
  const isDepartment = column.key === 'referat'
  return (
    <>
      <input id={id} type="text" value={text} list={isDepartment ? `${id}-list` : undefined} required={column.required} aria-invalid={blocking ? 'true' : undefined} aria-describedby={described} onChange={onText} />
      {isDepartment ? <datalist id={`${id}-list`}>{departments.map((department) => <option key={department} value={department} />)}</datalist> : null}
    </>
  )
}

function InputField(props: VvtFieldProps) {
  const { column, value = null, issues = [], departments = [], onValueChange } = props
  const id = useElementId('fa-vvt-field')
  const count = useCount(value, onValueChange)
  const blocking = issues.some((issue) => issue.blocking)
  const described = issues.length || count.error ? `${id}-note` : undefined
  return (
    <div className={classes('fa-dataprotection__field', column.required && 'fa-dataprotection__field--required')}>
      <label htmlFor={id}>{column.title}</label>
      <Control id={id} column={column} value={value} blocking={blocking} described={described} count={count} departments={departments} onText={(event) => onValueChange(event.target.value)} />
      {column.reference ? <span className="fa-dataprotection__ref">{column.reference}</span> : null}
      <Notes id={`${id}-note`} issues={issues} countError={count.error} />
    </div>
  )
}

/** Ein Feld einer Tätigkeit je nach Spaltenart (Text, Ja/Nein/offen, Anzahl) wie VvtField.vue. */
export function VvtField(props: VvtFieldProps) {
  return props.column.kind === 'flag' ? <FlagField {...props} /> : <InputField {...props} />
}

// packages-js/ui/src/dataprotection/components/VvtField.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useId } from '../../composables/useId'
import { useI18n } from '../../i18n'
import { dataprotectionMessages } from '../core'
import { parseCount } from '../core'
import type { RegisterColumn, FieldValue, Issue } from '../core'

const props = withDefaults(defineProps<{
  column: RegisterColumn
  value?: FieldValue
  issues?: Issue[]
  departments?: string[]
}>(), { value: null, issues: () => [], departments: () => [] })

const emit = defineEmits<{ 'value-change': [value: FieldValue] }>()
const { t } = useI18n(dataprotectionMessages)
const id = useId('fa-vvt-field')
const noteId = `${id}-note`
const countText = ref('')
const countError = ref(false)
const long = computed(() => !['name', 'referat', 'ansprechperson'].includes(props.column.key))
const blocking = computed(() => props.issues.some((issue) => issue.blocking))
const described = computed(() => (props.issues.length || countError.value ? noteId : undefined))

watch(() => props.value, (value) => {
  countText.value = value === null || value === undefined ? '' : String(value)
  countError.value = false
}, { immediate: true })

function onText(event: Event): void {
  emit('value-change', (event.target as HTMLInputElement | HTMLTextAreaElement).value)
}

function onCount(event: Event): void {
  countText.value = (event.target as HTMLInputElement).value
  const parsed = parseCount(countText.value)
  countError.value = parsed === undefined
  if (parsed !== undefined) emit('value-change', parsed)
}

function flagValue(choice: 'yes' | 'no' | 'open'): boolean | null {
  return choice === 'yes' ? true : choice === 'no' ? false : null
}
</script>

<template>
  <fieldset v-if="column.kind === 'flag'" class="fa-dataprotection__field" :class="{ 'fa-dataprotection__field--required': column.required }" :aria-describedby="described">
    <legend>{{ column.title }}</legend>
    <div class="fa-dataprotection__choices">
      <label v-for="choice in (['yes', 'no', 'open'] as const)" :key="choice" class="fa-dataprotection__choice">
        <input
          type="radio"
          :name="id"
          :checked="value === flagValue(choice)"
          :aria-invalid="blocking ? 'true' : undefined"
          @change="emit('value-change', flagValue(choice))"
        />
        {{ t(choice) }}
      </label>
    </div>
    <span v-if="column.reference" class="fa-dataprotection__ref">{{ column.reference }}</span>
    <div v-if="issues.length" :id="noteId">
      <p v-for="issue in issues" :key="issue.code + issue.message" class="fa-dataprotection__note" :class="{ 'fa-dataprotection__note--blocking': issue.blocking }">{{ issue.message }}</p>
    </div>
  </fieldset>
  <div v-else class="fa-dataprotection__field" :class="{ 'fa-dataprotection__field--required': column.required }">
    <label :for="id">{{ column.title }}</label>
    <input
      v-if="column.kind === 'count'"
      :id="id"
      type="text"
      inputmode="numeric"
      :value="countText"
      :aria-invalid="blocking || countError ? 'true' : undefined"
      :aria-describedby="described"
      @input="onCount"
    />
    <textarea
      v-else-if="long"
      :id="id"
      rows="2"
      :value="typeof value === 'string' ? value : ''"
      :required="column.required"
      :aria-invalid="blocking ? 'true' : undefined"
      :aria-describedby="described"
      @input="onText"
    />
    <input
      v-else
      :id="id"
      type="text"
      :value="typeof value === 'string' ? value : ''"
      :list="column.key === 'referat' ? `${id}-list` : undefined"
      :required="column.required"
      :aria-invalid="blocking ? 'true' : undefined"
      :aria-describedby="described"
      @input="onText"
    />
    <datalist v-if="column.key === 'referat'" :id="`${id}-list`">
      <option v-for="department in departments" :key="department" :value="department" />
    </datalist>
    <span v-if="column.reference" class="fa-dataprotection__ref">{{ column.reference }}</span>
    <div v-if="issues.length || countError" :id="noteId">
      <p v-if="countError" class="fa-dataprotection__note fa-dataprotection__note--blocking">{{ t('invalidCount') }}</p>
      <p v-for="issue in issues" :key="issue.code + issue.message" class="fa-dataprotection__note" :class="{ 'fa-dataprotection__note--blocking': issue.blocking }">{{ issue.message }}</p>
    </div>
  </div>
</template>
