// packages-js/ui-react/src/dataprotection/vvt/VvtStatusBar.tsx
import { statusTone, type DataProtectionTranslate, type RegisterState, type VersionView, type VvtExportFormat } from '@auditcore/ui-core'
import { Badge } from '../../base/Badge'
import { Button, type ButtonProps } from '../../base/Button'
import { statusLabel, useDataProtectionText } from '../shared'

export interface VvtStatusBarProps {
  state: RegisterState | null
  version: VersionView | null
  showing: 'draft' | 'released'
  editing: boolean
  editable: boolean
  dirty: boolean
  fourEyes: boolean
  busy: string | null
  history: boolean
  onSave: () => void
  onDiscard: () => void
  onRelease: () => void
  onNewDraft: () => void
  onShow: (which: 'draft' | 'released') => void
  onToggleHistory: () => void
  onExport: (format: VvtExportFormat) => void
}

function VersionInfo({ version, editing, hasDraft }: { version: VersionView | null; editing: boolean; hasDraft: boolean }) {
  const { t, when } = useDataProtectionText()
  if (version && !(editing && !hasDraft)) {
    return (
      <>
        <Badge tone={statusTone(version.status)}>{t('versionLabel', { version: version.version, status: statusLabel(t, version.status) })}</Badge>
        <span className="fa-dataprotection__muted">{t('createdBy', { person: version.created_by, date: when(version.created_at) })}</span>
        {version.released_by ? <span className="fa-dataprotection__muted">{t('releasedBy', { person: version.released_by, date: when(version.released_at) })}</span> : null}
        <span className="fa-dataprotection__muted">{t('revision', { revision: version.revision })}</span>
      </>
    )
  }
  if (editing) return <Badge tone="warning">{t('newDraft')}</Badge>
  return <span className="fa-dataprotection__muted">{t('noVersion')}</span>
}

interface Action {
  key: string
  show: boolean
  props: ButtonProps
}

/** Ansicht wechseln, Entwurf anlegen, Änderungen verwerfen. */
function viewActions(props: VvtStatusBarProps, t: DataProtectionTranslate): Action[] {
  const { state, showing, editing, editable, dirty } = props
  const draft = !!state?.draft
  const toReleased = showing === 'draft'
  return [
    { key: 'show', show: draft && !!state?.released, props: { variant: 'ghost', size: 'sm', label: toReleased ? t('showReleased') : t('showDraft'), onClick: () => props.onShow(toReleased ? 'released' : 'draft') } },
    { key: 'new', show: editable && !draft && !editing, props: { size: 'sm', icon: 'plus', label: t('newDraft'), onClick: props.onNewDraft } },
    { key: 'discard', show: editing && dirty, props: { size: 'sm', label: t('discard'), onClick: props.onDiscard } },
  ]
}

/** Speichern und Freigeben (Vier-Augen-Vorprüfung, maßgeblich bleibt der Server). */
function writeActions(props: VvtStatusBarProps, releaseHint: string, t: DataProtectionTranslate): Action[] {
  const { state, busy, dirty, editable } = props
  const draft = !!state?.draft
  const saving = busy === 'save'
  const canRelease = editable && props.showing === 'draft' && draft && !dirty && !props.fourEyes
  return [
    { key: 'save', show: props.editing, props: { variant: 'primary', size: 'sm', loading: saving, disabled: !dirty, label: saving ? t('saving') : t('save'), onClick: props.onSave } },
    { key: 'release', show: editable && draft, props: { size: 'sm', icon: 'lock', label: t('release'), disabled: !canRelease, loading: busy === 'release', title: releaseHint || undefined, onClick: props.onRelease } },
  ]
}

function EditButtons(props: VvtStatusBarProps & { releaseHint: string }) {
  const { t } = useDataProtectionText()
  return (
    <>
      {[...viewActions(props, t), ...writeActions(props, props.releaseHint, t)].filter((action) => action.show).map((action) => <Button key={action.key} {...action.props} />)}
    </>
  )
}

/** Fassung, Bearbeitungsstand und Aktionen des Verzeichnisses (wie VvtStatusBar.vue). */
export function VvtStatusBar(props: VvtStatusBarProps) {
  const { t } = useDataProtectionText()
  const draft = props.state?.draft ?? null
  const releaseHint = props.dirty ? t('saveFirst') : props.fourEyes ? t('fourEyesHint') : ''
  return (
    <div className="fa-dataprotection__panel fa-dataprotection__bar" data-testid="vvt-status">
      <VersionInfo version={props.version} editing={props.editing} hasDraft={!!draft} />
      {props.dirty ? <Badge tone="accent">{t('unsaved')}</Badge> : null}
      <div className="fa-dataprotection__actions">
        <EditButtons {...props} releaseHint={releaseHint} />
        <Button variant="ghost" size="sm" icon="clock" pressed={props.history} label={props.history ? t('hideHistory') : t('history')} onClick={props.onToggleHistory} />
        <Button variant="ghost" size="sm" label={t('exportPrint')} onClick={() => props.onExport('print')} />
        <Button variant="ghost" size="sm" label={t('exportMarkdown')} onClick={() => props.onExport('markdown')} />
        <Button variant="ghost" size="sm" label={t('exportCsv')} onClick={() => props.onExport('csv')} />
      </div>
      {props.editable && draft && releaseHint ? <p className="fa-dataprotection__muted" data-testid="vvt-release-hint">{releaseHint}</p> : null}
    </div>
  )
}

// packages-js/ui/src/dataprotection/components/VvtStatusBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import FaBadge from '../../base/FaBadge.vue'
import FaButton from '../../base/FaButton.vue'
import { formatDate, useI18n } from '../../i18n'
import { dataprotectionMessages } from '../core'
import { statusTone } from '../core'
import { statusLabel } from '../core'
import type { RegisterState, VersionView } from '../core'
import type { VvtExportFormat } from '../useVvt'

const props = withDefaults(defineProps<{
  state: RegisterState | null
  version: VersionView | null
  showing: 'draft' | 'released'
  editing?: boolean
  editable?: boolean
  dirty?: boolean
  fourEyes?: boolean
  busy?: string | null
  history?: boolean
}>(), { editing: false, editable: true, dirty: false, fourEyes: false, busy: null, history: false })

const emit = defineEmits<{
  save: []
  discard: []
  release: []
  'new-draft': []
  show: [which: 'draft' | 'released']
  'toggle-history': []
  export: [format: VvtExportFormat]
}>()
const { t, locale } = useI18n(dataprotectionMessages)
const draft = computed(() => props.state?.draft ?? null)
const released = computed(() => props.state?.released ?? null)
const canRelease = computed(() => props.editable && props.showing === 'draft' && !!draft.value && !props.dirty && !props.fourEyes)
const releaseHint = computed(() => (props.dirty ? t('saveFirst') : props.fourEyes ? t('fourEyesHint') : ''))
const when = (value: string | null): string => formatDate(value, locale.value, true)
</script>

<template>
  <div class="fa-dataprotection__panel fa-dataprotection__bar" data-testid="vvt-status">
    <template v-if="version && !(editing && !draft)">
      <FaBadge :tone="statusTone(version.status)">{{ t('versionLabel', { version: version.version, status: statusLabel(t, version.status) }) }}</FaBadge>
      <span class="fa-dataprotection__muted">{{ t('createdBy', { person: version.created_by, date: when(version.created_at) }) }}</span>
      <span v-if="version.released_by" class="fa-dataprotection__muted">{{ t('releasedBy', { person: version.released_by, date: when(version.released_at) }) }}</span>
      <span class="fa-dataprotection__muted">{{ t('revision', { revision: version.revision }) }}</span>
    </template>
    <FaBadge v-else-if="editing" tone="warning">{{ t('newDraft') }}</FaBadge>
    <span v-else class="fa-dataprotection__muted">{{ t('noVersion') }}</span>
    <FaBadge v-if="dirty" tone="accent">{{ t('unsaved') }}</FaBadge>
    <div class="fa-dataprotection__actions">
      <FaButton v-if="draft && released" variant="ghost" size="sm" :label="showing === 'draft' ? t('showReleased') : t('showDraft')" @click="emit('show', showing === 'draft' ? 'released' : 'draft')" />
      <FaButton v-if="editable && !draft && !editing" size="sm" icon="plus" :label="t('newDraft')" @click="emit('new-draft')" />
      <FaButton v-if="editing && dirty" size="sm" :label="t('discard')" @click="emit('discard')" />
      <FaButton v-if="editing" variant="primary" size="sm" :loading="busy === 'save'" :disabled="!dirty" :label="busy === 'save' ? t('saving') : t('save')" @click="emit('save')" />
      <FaButton
        v-if="editable && draft"
        size="sm"
        icon="lock"
        :label="t('release')"
        :disabled="!canRelease"
        :loading="busy === 'release'"
        :title="releaseHint || undefined"
        @click="emit('release')"
      />
      <FaButton variant="ghost" size="sm" icon="clock" :pressed="history" :label="history ? t('hideHistory') : t('history')" @click="emit('toggle-history')" />
      <FaButton variant="ghost" size="sm" :label="t('exportPrint')" @click="emit('export', 'print')" />
      <FaButton variant="ghost" size="sm" :label="t('exportMarkdown')" @click="emit('export', 'markdown')" />
      <FaButton variant="ghost" size="sm" :label="t('exportCsv')" @click="emit('export', 'csv')" />
    </div>
    <p v-if="editable && draft && releaseHint" class="fa-dataprotection__muted" data-testid="vvt-release-hint">{{ releaseHint }}</p>
  </div>
</template>
