// packages-js/ui/src/kanban/CardReferences.vue
<script setup lang="ts">
import type { Attachment, CardLink } from '@auditcore/kanban-core'
import FaIcon from '../base/FaIcon.vue'
import { formatNumber, useI18n, type Locale } from '../i18n'
import { fileSize } from './cardView'
import { kanbanDialogMessages } from './messages'

const props = withDefaults(defineProps<{ links: readonly CardLink[]; attachments: readonly Attachment[]; locale?: Locale }>(), { locale: undefined })
const emit = defineEmits<{ navigate: [link: CardLink]; attachment: [attachment: Attachment] }>()
const { t, locale: active } = useI18n(kanbanDialogMessages, () => props.locale)

function size(bytes: number): string {
  const { value, unit } = fileSize(bytes)
  return unit === 'B' ? `${value} B` : `${formatNumber(value, active.value, { maximumFractionDigits: 1 })} ${unit}`
}
</script>

<template>
  <div v-if="links.length" class="fa-kanban-detail__section">
    <span class="fa-kanban-detail__label">{{ t('links') }}</span>
    <ul class="fa-kanban-detail__list">
      <li v-for="link in links" :key="`${link.kind}:${link.target}`" class="fa-kanban-detail__item">
        <FaIcon name="share" :size="14" />
        <button type="button" class="fa-kanban-toolbar__rename" :aria-label="t('openLink', { title: link.title || link.target })" @click="emit('navigate', link)">
          {{ link.title || link.target }}
        </button>
        <span class="fa-badge">{{ link.kind }}</span>
      </li>
    </ul>
  </div>
  <div class="fa-kanban-detail__section">
    <span class="fa-kanban-detail__label">{{ t('attachments') }}</span>
    <ul v-if="attachments.length" class="fa-kanban-detail__list">
      <li v-for="file in attachments" :key="file.id" class="fa-kanban-detail__item">
        <FaIcon name="paperclip" :size="14" />
        <button type="button" class="fa-kanban-toolbar__rename" @click="emit('attachment', file)">{{ file.filename }}</button>
        <span class="fa-kanban-detail__meta-inline">{{ size(file.size) }}</span>
      </li>
    </ul>
    <p v-else class="fa-kanban-settings__hint">{{ t('noAttachments') }}</p>
    <slot name="attachments" />
  </div>
</template>

// packages-js/ui-react/src/kanban/CardReferences.tsx
import { intlFormatNumber } from '@auditcore/common'
import { fileSize, type Attachment, type CardLink } from '@auditcore/kanban-core'
import type { Locale } from '@auditcore/ui-core'
import type { ReactNode } from 'react'
import { Icon } from '../base/Icon'
import { useKanbanDialogText } from './text'

export interface CardReferencesProps {
  links: readonly CardLink[]
  attachments: readonly Attachment[]
  locale?: Locale
  /** Zusätzlicher Inhalt unter den Anhängen (Slot `attachments` in Vue). */
  attachmentsExtra?: ReactNode
  onNavigate?: (link: CardLink) => void
  onAttachment?: (attachment: Attachment) => void
}

function sizeText(bytes: number, locale: Locale): string {
  const { value, unit } = fileSize(bytes)
  return unit === 'B' ? `${value} B` : `${intlFormatNumber(value, locale, { maximumFractionDigits: 1 })} ${unit}`
}

/** Verknüpfungen und Anhänge einer Karte wie `CardReferences.vue`. */
export function CardReferences(props: CardReferencesProps) {
  const { t, locale } = useKanbanDialogText(props.locale)
  return (
    <>
      {props.links.length ? (
        <div className="fa-kanban-detail__section">
          <span className="fa-kanban-detail__label">{t('links')}</span>
          <ul className="fa-kanban-detail__list">
            {props.links.map((link) => (
              <li key={`${link.kind}:${link.target}`} className="fa-kanban-detail__item">
                <Icon name="share" size={14} />
                <button type="button" className="fa-kanban-toolbar__rename" aria-label={t('openLink', { title: link.title || link.target })} onClick={() => props.onNavigate?.(link)}>
                  {link.title || link.target}
                </button>
                <span className="fa-badge">{link.kind}</span>
              </li>
            ))}
          </ul>
        </div>
      ) : null}
      <div className="fa-kanban-detail__section">
        <span className="fa-kanban-detail__label">{t('attachments')}</span>
        {props.attachments.length ? (
          <ul className="fa-kanban-detail__list">
            {props.attachments.map((file) => (
              <li key={file.id} className="fa-kanban-detail__item">
                <Icon name="paperclip" size={14} />
                <button type="button" className="fa-kanban-toolbar__rename" onClick={() => props.onAttachment?.(file)}>{file.filename}</button>
                <span className="fa-kanban-detail__meta-inline">{sizeText(file.size, locale)}</span>
              </li>
            ))}
          </ul>
        ) : <p className="fa-kanban-settings__hint">{t('noAttachments')}</p>}
        {props.attachmentsExtra}
      </div>
    </>
  )
}
