// packages-js/ui/src/kanban/CardAppearance.vue
<script setup lang="ts">
import { ref } from 'vue'
import FaButton from '../base/FaButton.vue'
import { useI18n, type Locale } from '../i18n'
import { CARD_COLORS, MAX_CARD_IMAGE_BYTES } from './cardView'
import { kanbanDialogMessages } from './messages'

const props = withDefaults(defineProps<{ color: string | null; image: string | null; readOnly?: boolean; locale?: Locale }>(), { readOnly: false, locale: undefined })
const emit = defineEmits<{ change: [patch: { color?: string; image?: string }] }>()
const { t } = useI18n(kanbanDialogMessages, () => props.locale)
const problem = ref('')

/** Bild als Data-URI (höchstens 2 MB, wie im Original). */
function pickImage(event: Event): void {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  input.value = ''
  problem.value = ''
  if (!file) return
  if (file.size > MAX_CARD_IMAGE_BYTES) {
    problem.value = t('imageTooLarge')
    return
  }
  const reader = new FileReader()
  reader.onload = () => emit('change', { image: String(reader.result) })
  reader.readAsDataURL(file)
}
</script>

<template>
  <div class="fa-kanban-detail__section">
    <span class="fa-kanban-detail__label">{{ t('appearance') }}</span>
    <div class="fa-kanban-detail__row" role="group" :aria-label="t('appearance')">
      <button
        v-for="swatch in CARD_COLORS"
        :key="swatch.value"
        type="button"
        class="fa-kanban-detail__swatch"
        :style="{ background: swatch.value }"
        :title="swatch.label"
        :aria-label="swatch.label"
        :aria-pressed="color === swatch.value"
        :disabled="readOnly"
        @click="emit('change', { color: color === swatch.value ? '' : swatch.value })"
      />
      <label v-if="!readOnly" class="fa-kanban-detail__swatch" :title="t('customColor')" :style="{ background: 'conic-gradient(red, yellow, lime, aqua, blue, magenta, red)' }">
        <input type="color" class="fa-sr-only" :value="color ?? '#7c3aed'" :aria-label="t('customColor')" @change="emit('change', { color: ($event.target as HTMLInputElement).value })" />
      </label>
      <FaButton v-if="color && !readOnly" size="sm" variant="ghost" icon="close" icon-only :label="t('clearColor')" @click="emit('change', { color: '' })" />
    </div>
    <img v-if="image" class="fa-kanban-detail__image" :src="image" :alt="t('image')" />
    <div v-if="!readOnly" class="fa-kanban-detail__row">
      <label class="fa-button fa-button--secondary fa-button--sm">
        {{ t('uploadImage') }}
        <input type="file" accept="image/*" class="fa-sr-only" @change="pickImage" />
      </label>
      <FaButton v-if="image" size="sm" variant="ghost" icon="trash" @click="emit('change', { image: '' })">{{ t('removeImage') }}</FaButton>
    </div>
    <p v-if="problem" class="fa-field__note" role="alert">{{ problem }}</p>
  </div>
</template>

// packages-js/ui-react/src/kanban/CardAppearance.tsx
import { CARD_COLORS, MAX_CARD_IMAGE_BYTES } from '@auditcore/kanban-core'
import type { Locale } from '@auditcore/ui-core'
import { useState, type ChangeEvent } from 'react'
import { Button } from '../base/Button'
import { useKanbanDialogText } from './text'

export interface CardAppearanceProps {
  color: string | null
  image: string | null
  readOnly?: boolean
  locale?: Locale
  onChange: (patch: { color?: string; image?: string }) => void
}

const RAINBOW = { background: 'conic-gradient(red, yellow, lime, aqua, blue, magenta, red)' }

function Swatches({ color, readOnly = false, locale, onChange }: CardAppearanceProps) {
  const { t } = useKanbanDialogText(locale)
  return (
    <div className="fa-kanban-detail__row" role="group" aria-label={t('appearance')}>
      {CARD_COLORS.map((swatch) => (
        <button
          key={swatch.value}
          type="button"
          className="fa-kanban-detail__swatch"
          style={{ background: swatch.value }}
          title={swatch.label}
          aria-label={swatch.label}
          aria-pressed={color === swatch.value}
          disabled={readOnly}
          onClick={() => onChange({ color: color === swatch.value ? '' : swatch.value })}
        />
      ))}
      {readOnly ? null : (
        <label className="fa-kanban-detail__swatch" title={t('customColor')} style={RAINBOW}>
          <input type="color" className="fa-sr-only" value={color ?? '#7c3aed'} aria-label={t('customColor')} onChange={(event) => onChange({ color: event.target.value })} />
        </label>
      )}
      {color && !readOnly ? <Button size="sm" variant="ghost" icon="close" iconOnly label={t('clearColor')} onClick={() => onChange({ color: '' })} /> : null}
    </div>
  )
}

/** Kartendesign wie `CardAppearance.vue`: Farbe, eigene Farbe, Hintergrundbild (höchstens 2 MB). */
export function CardAppearance(props: CardAppearanceProps) {
  const { t } = useKanbanDialogText(props.locale)
  const [problem, setProblem] = useState('')
  const pickImage = (event: ChangeEvent<HTMLInputElement>): void => {
    const input = event.target
    const file = input.files?.[0]
    input.value = ''
    setProblem('')
    if (!file) return
    if (file.size > MAX_CARD_IMAGE_BYTES) {
      setProblem(t('imageTooLarge'))
      return
    }
    const reader = new FileReader()
    reader.onload = () => props.onChange({ image: String(reader.result) })
    reader.readAsDataURL(file)
  }
  return (
    <div className="fa-kanban-detail__section">
      <span className="fa-kanban-detail__label">{t('appearance')}</span>
      <Swatches {...props} />
      {props.image ? <img className="fa-kanban-detail__image" src={props.image} alt={t('image')} /> : null}
      {props.readOnly ? null : (
        <div className="fa-kanban-detail__row">
          <label className="fa-button fa-button--secondary fa-button--sm">
            {t('uploadImage')}
            <input type="file" accept="image/*" className="fa-sr-only" onChange={pickImage} />
          </label>
          {props.image ? <Button size="sm" variant="ghost" icon="trash" onClick={() => props.onChange({ image: '' })}>{t('removeImage')}</Button> : null}
        </div>
      )}
      {problem ? <p className="fa-field__note" role="alert">{problem}</p> : null}
    </div>
  )
}
