// packages-js/ui/src/kanban/KanbanSettingsDialog.vue
<script setup lang="ts">
import { watch } from 'vue'
import { DEFAULT_LIMITS, type Column } from '@flowaudit/kanban-core'
import FaButton from '../base/FaButton.vue'
import FaDialog from '../base/FaDialog.vue'
import { useI18n, type Locale } from '../i18n'
import ColumnEditorRow from './ColumnEditorRow.vue'
import { kanbanDialogMessages } from './messages'
import { useColumnEditor } from './useColumnEditor'

const props = withDefaults(defineProps<{ open: boolean; columns: readonly Column[]; locale?: Locale }>(), { locale: undefined })
const emit = defineEmits<{ close: []; save: [columns: Column[]] }>()
const { t } = useI18n(kanbanDialogMessages, () => props.locale)
const editor = useColumnEditor()
const { draft, problem, canAdd, canRemove, dirty, removed } = editor

watch(() => props.open, (open) => {
  if (open) editor.reset(props.columns)
}, { immediate: true })

function save(): void {
  const columns = editor.validated()
  if (columns) emit('save', columns)
}
</script>

<template>
  <FaDialog :open="open" :title="t('settingsTitle')" :description="t('settingsDescription')" size="lg" :locale="locale" @close="emit('close')">
    <p class="fa-kanban-detail__label">{{ t('columns', { count: draft.length, max: DEFAULT_LIMITS.columns_max }) }}</p>
    <ol class="fa-kanban-settings__list">
      <ColumnEditorRow
        v-for="(column, index) in draft"
        :key="column.id"
        :column="column"
        :first="index === 0"
        :last="index === draft.length - 1"
        :can-remove="canRemove"
        :locale="locale"
        @update="editor.update(index, $event)"
        @remove="editor.remove(index)"
        @move="editor.move(index, $event)"
      />
    </ol>
    <p v-if="removed.length" class="fa-kanban-settings__hint">{{ t('removedHint') }}</p>
    <p v-if="problem" class="fa-field__note" role="alert" style="color: var(--fa-color-danger)">{{ problem }}</p>
    <template #footer>
      <FaButton icon="plus" :disabled="!canAdd" @click="editor.add(t('newColumn'))">{{ t('addColumn') }}</FaButton>
      <span style="flex: 1" />
      <FaButton @click="emit('close')">{{ t('cancel') }}</FaButton>
      <FaButton variant="primary" :disabled="!dirty" data-testid="kanban-settings-save" @click="save">{{ t('save') }}</FaButton>
    </template>
  </FaDialog>
</template>

// packages-js/ui-react/src/kanban/KanbanSettingsDialog.tsx
import { createColumnEditor, selectColumnEditor, type Column } from '@flowaudit/kanban-core'
import type { Locale } from '@flowaudit/ui-core'
import { useLayoutEffect, useRef, useState } from 'react'
import { Button } from '../base/Button'
import { Dialog } from '../base/Dialog'
import { useStoreState } from '../store'
import { ColumnEditorRow } from './ColumnEditorRow'
import { useKanbanDialogText } from './text'

export interface KanbanSettingsDialogProps {
  open: boolean
  columns: readonly Column[]
  locale?: Locale
  onClose: () => void
  onSave: (columns: Column[]) => void
}

/** Spalten, Farben und WIP-Limits wie `KanbanSettingsDialog.vue` (Prüfung über die Kernlogik). */
export function KanbanSettingsDialog(props: KanbanSettingsDialogProps) {
  const { t } = useKanbanDialogText(props.locale)
  const [editor] = useState(() => createColumnEditor())
  const state = useStoreState(editor.store)
  const view = selectColumnEditor(state, editor.maxColumns)
  const columns = useRef(props.columns)
  columns.current = props.columns
  // Wie der Vue-watch auf `open`: beim Öffnen den Entwurf aus den Spalten neu belegen.
  useLayoutEffect(() => {
    if (props.open) editor.reset(columns.current)
  }, [props.open, editor])
  const save = (): void => {
    const columns = editor.validated()
    if (columns) props.onSave(columns)
  }
  const footer = (
    <>
      <Button icon="plus" disabled={!view.canAdd} onClick={() => editor.add(t('newColumn'))}>{t('addColumn')}</Button>
      <span style={{ flex: 1 }} />
      <Button onClick={props.onClose}>{t('cancel')}</Button>
      <Button variant="primary" disabled={!view.dirty} testId="kanban-settings-save" onClick={save}>{t('save')}</Button>
    </>
  )
  return (
    <Dialog open={props.open} title={t('settingsTitle')} description={t('settingsDescription')} size="lg" locale={props.locale} footer={footer} onClose={props.onClose}>
      <p className="fa-kanban-detail__label">{t('columns', { count: state.draft.length, max: editor.maxColumns })}</p>
      <ol className="fa-kanban-settings__list">
        {state.draft.map((column, index) => (
          <ColumnEditorRow
            key={column.id}
            column={column}
            first={index === 0}
            last={index === state.draft.length - 1}
            canRemove={view.canRemove}
            locale={props.locale}
            onUpdate={(patch) => editor.update(index, patch)}
            onRemove={() => editor.remove(index)}
            onMove={(step) => editor.move(index, step)}
          />
        ))}
      </ol>
      {view.removed.length ? <p className="fa-kanban-settings__hint">{t('removedHint')}</p> : null}
      {state.problem ? <p className="fa-field__note" role="alert" style={{ color: 'var(--fa-color-danger)' }}>{state.problem}</p> : null}
    </Dialog>
  )
}
