// packages-js/ui/src/dbkanban/DbKanbanColumn.vue
<script setup lang="ts">
import { dbKanbanMessages, type DbColumnView } from '@auditcore/ui-core'
import FaButton from '../base/FaButton.vue'
import { useId } from '../composables/useId'
import { useI18n } from '../i18n'
import DbKanbanCard from './DbKanbanCard.vue'

const props = withDefaults(defineProps<{
  column: DbColumnView
  editable?: boolean
  canAdd?: boolean
  dragging?: string | null
  over?: boolean
  hintId?: string
}>(), { editable: true, canAdd: false, dragging: null, over: false, hintId: undefined })

const emit = defineEmits<{
  'card-drag': [id: string | null]
  'card-step': [id: string, direction: 1 | -1]
  'card-drop': [id: string, column: string]
  'column-over': [column: string | null]
  'card-add': [column: string]
}>()
const { t } = useI18n(dbKanbanMessages)
const headingId = useId('fa-db-kanban-column')

function onDragOver(event: DragEvent): void {
  if (!props.editable) return
  event.preventDefault()
  if (!props.over) emit('column-over', props.column.value)
}

function onDrop(event: DragEvent): void {
  if (!props.editable) return
  event.preventDefault()
  const id = event.dataTransfer?.getData('text/plain') || props.dragging
  if (id) emit('card-drop', id, props.column.value)
}
</script>

<template>
  <section
    class="fa-db-kanban-column"
    :class="{ 'fa-db-kanban-column--over': over, 'fa-db-kanban-column--empty-value': column.value === '' }"
    :aria-labelledby="headingId"
    :data-column="column.value"
    @dragover="onDragOver"
    @dragleave.self="emit('column-over', null)"
    @drop="onDrop"
  >
    <header class="fa-db-kanban-column__head">
      <h3 :id="headingId" class="fa-db-kanban-column__name">{{ column.label }}</h3>
      <span class="fa-db-kanban-column__count">{{ column.countText }}</span>
    </header>
    <ul class="fa-db-kanban-column__list" :aria-labelledby="headingId">
      <DbKanbanCard
        v-for="card in column.cards"
        :key="card.id"
        :card="card"
        :column-label="column.label"
        :editable="editable"
        :dragging="dragging === card.id"
        :described-by="hintId"
        @card-drag="emit('card-drag', $event)"
        @card-step="(id, direction) => emit('card-step', id, direction)"
      />
    </ul>
    <p v-if="column.cards.length === 0" class="fa-db-kanban-column__empty">{{ t('columnEmpty') }}</p>
    <FaButton
      v-if="editable && canAdd"
      class="fa-db-kanban-column__add"
      size="sm"
      variant="ghost"
      icon="plus"
      :aria-label="t('addCardIn', { label: column.label })"
      @click="emit('card-add', column.value)"
    >{{ t('addCard') }}</FaButton>
  </section>
</template>

// packages-js/ui-react/src/dbkanban/DbKanbanColumn.tsx
import type { DragEvent } from 'react'
import type { DbColumnView, DbKanbanTranslate } from '@auditcore/ui-core'
import { Button } from '../base/Button'
import { classes, useElementId } from '../store'
import { DbKanbanCard } from './DbKanbanCard'

export interface DbKanbanColumnProps {
  column: DbColumnView
  t: DbKanbanTranslate
  editable?: boolean
  canAdd?: boolean
  dragging?: string | null
  over?: boolean
  hintId?: string
  onCardDrag: (id: string | null) => void
  onCardStep: (id: string, direction: 1 | -1) => void
  onCardDrop: (id: string, column: string) => void
  onColumnOver: (column: string | null) => void
  onCardAdd: (column: string) => void
}

/** Spalte der Datenbankansicht wie `DbKanbanColumn.vue` (Ablegen setzt den Wert). */
export function DbKanbanColumn(props: DbKanbanColumnProps) {
  const { column, t, editable = true, dragging = null } = props
  const headingId = useElementId('fa-db-kanban-column')
  const onDragOver = (event: DragEvent<HTMLElement>): void => {
    if (!editable) return
    event.preventDefault()
    if (!props.over) props.onColumnOver(column.value)
  }
  const onDrop = (event: DragEvent<HTMLElement>): void => {
    if (!editable) return
    event.preventDefault()
    const id = event.dataTransfer?.getData('text/plain') || dragging
    if (id) props.onCardDrop(id, column.value)
  }
  const onDragLeave = (event: DragEvent<HTMLElement>): void => {
    if (event.target === event.currentTarget) props.onColumnOver(null)
  }
  return (
    <section
      className={classes('fa-db-kanban-column', props.over && 'fa-db-kanban-column--over', column.value === '' && 'fa-db-kanban-column--empty-value')}
      aria-labelledby={headingId} data-column={column.value} onDragOver={onDragOver} onDragLeave={onDragLeave} onDrop={onDrop}
    >
      <header className="fa-db-kanban-column__head">
        <h3 id={headingId} className="fa-db-kanban-column__name">{column.label}</h3>
        <span className="fa-db-kanban-column__count">{column.countText}</span>
      </header>
      <ul className="fa-db-kanban-column__list" aria-labelledby={headingId}>
        {column.cards.map((card) => (
          <DbKanbanCard key={card.id} card={card} columnLabel={column.label} t={t} editable={editable} dragging={dragging === card.id} describedBy={props.hintId} onCardDrag={props.onCardDrag} onCardStep={props.onCardStep} />
        ))}
      </ul>
      {column.cards.length === 0 ? <p className="fa-db-kanban-column__empty">{t('columnEmpty')}</p> : null}
      {editable && props.canAdd ? (
        <Button className="fa-db-kanban-column__add" size="sm" variant="ghost" icon="plus" ariaLabel={t('addCardIn', { label: column.label })} onClick={() => props.onCardAdd(column.value)}>{t('addCard')}</Button>
      ) : null}
    </section>
  )
}
