// packages-js/bpmn-react/src/dialogs/DiagramInfoDialog.tsx
/**
 * Diagram info: all info fields incl. profile, funds, programming period,
 * status, validity, approval with hash, confidentiality and header colours.
 * Edits a copy; „apply“ writes one undo step.
 */

import { useEffect, useState } from 'react'
import { headerOf, type Approval, type DiagramInfo, type ProfileSummary } from '@auditcore/bpmn-flowaudit'
import { cloneInfo, INFO_SECTIONS } from '@auditcore/bpmn-flowaudit/ui'
import { BaseDialog } from '../base/BaseDialog'
import { FaIcon } from '../base/FaIcon'
import { useEditorContext } from '../context'
import { useI18n } from '../i18n'
import { FieldForm } from '../panels/FieldForm'
import { useOptions } from '../panels/useOptions'
import { HeaderSection, LegalSection, ScopeFields } from './infoSections'

export interface DiagramInfoDialogProps {
  open: boolean
  info: DiagramInfo | null
  profiles: ProfileSummary[]
  approvals?: Approval[]
  fallbackTitle: string
  onOpenChange: (open: boolean) => void
  onApply?: (info: DiagramInfo) => void
  onApprove?: (info: DiagramInfo) => void
  onNewVersion?: (info: DiagramInfo) => void
}

function ApprovalSection({ draft, approvals, onApprove, onNewVersion }: Pick<DiagramInfoDialogProps, 'approvals' | 'onApprove' | 'onNewVersion'> & { draft: DiagramInfo }) {
  const { t } = useI18n()
  const readonly = useEditorContext().readonly()
  const last = approvals?.[approvals.length - 1]
  return (
    <section className="fa-info-section">
      <h3 className="fa-section__title">{t('info.approval')}</h3>
      <p className="fa-help">{t('info.approveHelp')}</p>
      {last ? <p className="fa-info-hash"><FaIcon name="hash" size={14} />{t('info.approvedHash')} ({last.version}): <code>{last.sha256}</code></p> : null}
      <div className="fa-info-actions">
        <button type="button" className="fa-btn" disabled={readonly} onClick={() => onApprove?.(draft)}><FaIcon name="lock" size={16} />{t('info.approve')}</button>
        <button type="button" className="fa-btn" onClick={() => onNewVersion?.(draft)}><FaIcon name="new" size={16} />{t('info.newVersion')}</button>
      </div>
    </section>
  )
}

export function DiagramInfoDialog(props: DiagramInfoDialogProps) {
  const { open, info, profiles, fallbackTitle, onOpenChange, onApply } = props
  const { t } = useI18n()
  const readonly = useEditorContext().readonly()
  const optionsFor = useOptions()
  const [draft, setDraft] = useState<DiagramInfo>(() => cloneInfo(info))

  useEffect(() => {
    if (open) setDraft(cloneInfo(info))
  }, [open, info])

  const header = headerOf(draft, fallbackTitle)
  const apply = () => {
    onApply?.(draft)
    onOpenChange(false)
  }
  const footer = (
    <>
      <button type="button" className="fa-btn" onClick={() => onOpenChange(false)}>{t('common.cancel')}</button>
      <button type="button" className="fa-btn fa-btn--primary" disabled={readonly} onClick={apply}>{t('common.apply')}</button>
    </>
  )

  return (
    <BaseDialog open={open} title={t('info.title')} width="860px" onOpenChange={onOpenChange} footer={footer}>
      <div className="fa-info-preview" style={{ background: header.color, color: header.textColor }} aria-label={t('info.preview')}>
        <strong>{header.title}</strong><span>{header.subtitle}</span>
      </div>
      {INFO_SECTIONS.map((section) => (
        <section key={section.id} className="fa-info-section">
          <h3 className="fa-section__title">{t(section.title)}</h3>
          <FieldForm value={draft as Record<string, unknown>} fields={section.fields} optionsFor={optionsFor} disabled={readonly && section.id !== 'status'} onUpdate={(value) => setDraft({ ...(value as DiagramInfo) })} />
          {section.id === 'scope' ? <ScopeFields draft={draft} profiles={profiles} setDraft={setDraft} /> : null}
        </section>
      ))}
      <HeaderSection draft={draft} header={header} setDraft={setDraft} />
      <LegalSection draft={draft} setDraft={setDraft} optionsFor={optionsFor} />
      <ApprovalSection draft={draft} approvals={props.approvals} onApprove={props.onApprove} onNewVersion={props.onNewVersion} />
    </BaseDialog>
  )
}

// packages-js/bpmn-vue/src/components/dialogs/DiagramInfoDialog.vue
<script setup lang="ts">
/**
 * Diagram info: all info fields incl. profile, funds, programming period,
 * status, validity, approval with hash, confidentiality and header colours
 * (legacy columns header_title/…/header_color). Edits a copy; „apply“
 * writes one undo step.
 */
import { computed, ref, watch } from 'vue'
import { FUNDS, FUND_SHORT, headerOf, label, type Approval, type DiagramInfo, type ProfileSummary } from '@auditcore/bpmn-flowaudit'
import { cloneInfo, DIAGRAM_LISTS, INFO_SECTIONS, infoList, LISTS, toggleFund as toggled } from '@auditcore/bpmn-flowaudit/ui'
import BaseDialog from '../base/BaseDialog.vue'
import FaIcon from '../base/FaIcon.vue'
import FieldForm from '../../panels/FieldForm.vue'
import ListEditor from '../../panels/ListEditor.vue'
import LegalBasisEditor from '../../panels/legal/LegalBasisEditor.vue'
import { useOptions } from '../../panels/useOptions'
import { useI18n } from '../../i18n/useI18n'
import { useEditorContext } from '../../stores/context'

const props = defineProps<{ open: boolean; info: DiagramInfo | null; profiles: ProfileSummary[]; approvals?: Approval[]; fallbackTitle: string }>()
const emit = defineEmits<{ (e: 'update:open', value: boolean): void; (e: 'apply', info: DiagramInfo): void; (e: 'approve', info: DiagramInfo): void; (e: 'new-version', info: DiagramInfo): void }>()
const { t, locale } = useI18n()
const { ports, profile, readonly } = useEditorContext()
const { optionsFor } = useOptions({ profile, catalogue: ports.catalogue, locale })
const draft = ref<DiagramInfo>({})

watch(
  () => props.open,
  (open) => {
    if (open) draft.value = cloneInfo(props.info)
  },
  { immediate: true },
)

const header = computed(() => headerOf(draft.value, props.fallbackTitle))
const lastApproval = computed(() => props.approvals?.[props.approvals.length - 1])

function merge(value: Record<string, unknown>): void {
  draft.value = { ...(value as DiagramInfo) }
}

const toggleFund = (code: string) => (draft.value = toggled(draft.value, code))
const listItems = (key: string) => infoList(draft.value, key)
</script>

<template>
  <BaseDialog :open="open" :title="t('info.title')" width="860px" @update:open="emit('update:open', $event)">
    <div class="fa-info-preview" :style="{ background: header.color, color: header.textColor }" :aria-label="t('info.preview')">
      <strong>{{ header.title }}</strong><span>{{ header.subtitle }}</span>
    </div>
    <section v-for="section in INFO_SECTIONS" :key="section.id" class="fa-info-section">
      <h3 class="fa-section__title">{{ t(section.title) }}</h3>
      <FieldForm :value="draft" :fields="section.fields" :options-for="optionsFor" :disabled="readonly() && section.id !== 'status'" @update="merge" />
      <template v-if="section.id === 'scope'">
        <label class="fa-field fa-section">
          <span class="fa-label">{{ t('info.field.profile') }}</span>
          <select class="fa-select" :value="draft.profile ?? ''" :disabled="readonly()" @change="draft = { ...draft, profile: ($event.target as HTMLSelectElement).value || undefined }">
            <option value="">{{ t('common.none') }}</option>
            <option v-for="entry in profiles" :key="entry.id" :value="entry.id">{{ entry.title }} ({{ entry.version }})</option>
          </select>
        </label>
        <fieldset class="fa-info-funds">
          <legend class="fa-label">{{ t('info.field.funds') }}</legend>
          <button v-for="(text, code) in FUNDS" :key="code" type="button" class="fa-chip" :title="label(text, locale)" :aria-pressed="(draft.funds ?? []).includes(String(code))" :disabled="readonly()" @click="toggleFund(String(code))">
            {{ FUND_SHORT[code] ?? code }}
          </button>
        </fieldset>
      </template>
    </section>
    <section class="fa-info-section">
      <h3 class="fa-section__title">{{ t('info.section.header') }}</h3>
      <div class="fa-grid-2">
        <label class="fa-field"><span class="fa-label">{{ t('info.field.headerColor') }}</span><input type="color" class="fa-input" :value="header.color" :disabled="readonly()" @change="draft = { ...draft, headerColor: ($event.target as HTMLInputElement).value }" /></label>
        <label class="fa-field"><span class="fa-label">{{ t('info.field.headerTextColor') }}</span><input type="color" class="fa-input" :value="header.textColor" :disabled="readonly()" @change="draft = { ...draft, headerTextColor: ($event.target as HTMLInputElement).value }" /></label>
      </div>
    </section>
    <section class="fa-info-section">
      <h3 class="fa-section__title">{{ t('info.section.legal') }}</h3>
      <LegalBasisEditor :items="draft.legalBases ?? []" :port="ports.legalSearch" :profile-id="profile()?.id" :disabled="readonly()" @update="draft = { ...draft, legalBases: $event }" />
      <ListEditor v-for="key in DIAGRAM_LISTS" :key="key" class="fa-section" :descriptor="LISTS[key]" :items="listItems(key)" :options-for="optionsFor" :disabled="readonly()" @update="draft = { ...draft, [key]: $event }" />
    </section>
    <section class="fa-info-section">
      <h3 class="fa-section__title">{{ t('info.approval') }}</h3>
      <p class="fa-help">{{ t('info.approveHelp') }}</p>
      <p v-if="lastApproval" class="fa-info-hash"><FaIcon name="hash" :size="14" />{{ t('info.approvedHash') }} ({{ lastApproval.version }}): <code>{{ lastApproval.sha256 }}</code></p>
      <div class="fa-info-actions">
        <button type="button" class="fa-btn" :disabled="readonly()" @click="emit('approve', draft)"><FaIcon name="lock" :size="16" />{{ t('info.approve') }}</button>
        <button type="button" class="fa-btn" @click="emit('new-version', draft)"><FaIcon name="new" :size="16" />{{ t('info.newVersion') }}</button>
      </div>
    </section>
    <template #footer>
      <button type="button" class="fa-btn" @click="emit('update:open', false)">{{ t('common.cancel') }}</button>
      <button type="button" class="fa-btn fa-btn--primary" :disabled="readonly()" @click="(emit('apply', draft), emit('update:open', false))">{{ t('common.apply') }}</button>
    </template>
  </BaseDialog>
</template>
