// packages-js/ui-react/src/kanban/KanbanToolbar.tsx
import { DUE_STATES, PRIORITIES, type BoardStats, type KanbanFilterState } from '@auditcore/kanban-core'
import type { Locale } from '@auditcore/ui-core'
import { useLayoutEffect, useRef, useState, type KeyboardEvent, type Ref } from 'react'
import { Button } from '../base/Button'
import { TextField } from '../base/TextField'
import { useKanbanText } from './text'

export interface KanbanToolbarProps {
  title: string
  stats: BoardStats | null
  filter: KanbanFilterState
  filterActive?: boolean
  canRename?: boolean
  canShare?: boolean
  canConfigure?: boolean
  showFullscreen?: boolean
  locale?: Locale
  /** Suchfeld (Tastenkürzel „/“ fokussiert es). */
  searchRef?: Ref<HTMLInputElement>
  onRename?: (title: string) => void
  onShare?: () => void
  onSettings?: () => void
  onFullscreen?: () => void
  onResetFilter?: () => void
  onFilterChange?: (patch: Partial<KanbanFilterState>) => void
}

function TitleEditor({ props }: { props: KanbanToolbarProps }) {
  const { t } = useKanbanText(props.locale)
  const [draft, setDraft] = useState<string | null>(null)
  const input = useRef<HTMLInputElement | null>(null)
  const editing = draft !== null
  useLayoutEffect(() => {
    if (editing) input.current?.select()
  }, [editing])
  const commit = (): void => {
    if (draft === null) return
    setDraft(null)
    const value = draft.trim()
    if (value && value !== props.title) props.onRename?.(value)
  }
  const onKeyDown = (event: KeyboardEvent<HTMLInputElement>): void => {
    if (event.key === 'Enter') { event.preventDefault(); commit() }
    else if (event.key === 'Escape') { event.preventDefault(); setDraft(null) }
  }
  if (editing) {
    return <input ref={input} className="fa-kanban-toolbar__title-input" aria-label={t('renameLabel')} value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={commit} onKeyDown={onKeyDown} />
  }
  return (
    <h1 className="fa-kanban-toolbar__heading">
      {props.canRename ? <button type="button" className="fa-kanban-toolbar__rename" title={t('renameHint')} onClick={() => setDraft(props.title)}>{props.title}</button> : props.title}
    </h1>
  )
}

function Progress({ stats, locale }: { stats: BoardStats; locale?: Locale }) {
  const { t } = useKanbanText(locale)
  const label = t('progress', { done: stats.done, total: stats.total })
  return (
    <div className="fa-kanban-toolbar__progress">
      <span>{label}</span>
      <span className="fa-kanban-toolbar__bar" role="progressbar" aria-valuenow={stats.progress} aria-valuemin={0} aria-valuemax={100} aria-label={label}>
        <span style={{ width: `${stats.progress}%` }} />
      </span>
      <span>{stats.progress} %</span>
    </div>
  )
}

function FilterTools({ props }: { props: KanbanToolbarProps }) {
  const { t } = useKanbanText(props.locale)
  const change = (patch: Partial<KanbanFilterState>): void => props.onFilterChange?.(patch)
  return (
    <>
      <TextField inputRef={props.searchRef} value={props.filter.query} className="fa-kanban-toolbar__search" type="search" label={t('search')} placeholder={t('searchPlaceholder')} hideLabel onChange={(query) => change({ query })} />
      <select value={props.filter.priority} className="fa-kanban-select" aria-label={t('priorityFilter')} onChange={(event) => change({ priority: event.target.value as KanbanFilterState['priority'] })}>
        <option value="">{t('allPriorities')}</option>
        {PRIORITIES.map((priority) => <option key={priority} value={priority}>{t(`priority_${priority}`)}</option>)}
      </select>
      <select value={props.filter.due} className="fa-kanban-select" aria-label={t('dueFilter')} onChange={(event) => change({ due: event.target.value as KanbanFilterState['due'] })}>
        <option value="">{t('allDue')}</option>
        {DUE_STATES.map((state) => <option key={state} value={state}>{t(`due_${state}`)}</option>)}
      </select>
    </>
  )
}

/** Werkzeugleiste wie `KanbanToolbar.vue` (Titel, Fortschritt, Suche, Filter, Aktionen). */
export function KanbanToolbar(props: KanbanToolbarProps) {
  const { t } = useKanbanText(props.locale)
  return (
    <div className="fa-kanban-toolbar">
      <div className="fa-kanban-toolbar__title">
        <TitleEditor props={props} />
        {props.stats ? <Progress stats={props.stats} locale={props.locale} /> : null}
      </div>
      <div className="fa-kanban-toolbar__tools">
        <FilterTools props={props} />
        {props.filterActive ? <Button size="sm" variant="ghost" icon="close" onClick={props.onResetFilter}>{t('resetFilter')}</Button> : null}
        {props.showFullscreen ?? true ? <Button variant="ghost" icon="expand" iconOnly label={t('fullscreen')} onClick={props.onFullscreen} /> : null}
        {props.canShare ? <Button variant="ghost" icon="share" iconOnly label={t('share')} onClick={props.onShare} /> : null}
        {props.canConfigure ? <Button variant="ghost" icon="settings" iconOnly label={t('settings')} onClick={props.onSettings} /> : null}
      </div>
    </div>
  )
}

// packages-js/ui/src/kanban/KanbanToolbar.vue
<script setup lang="ts">
import { nextTick, ref } from 'vue'
import { DUE_STATES, PRIORITIES, type BoardStats } from '@auditcore/kanban-core'
import FaButton from '../base/FaButton.vue'
import FaTextField from '../base/FaTextField.vue'
import { useI18n, type Locale } from '../i18n'
import { kanbanMessages } from './messages'
import type { KanbanFilterState } from './useKanbanFilter'

const props = withDefaults(defineProps<{
  title: string
  stats: BoardStats | null
  filter: KanbanFilterState
  filterActive?: boolean
  canRename?: boolean
  canShare?: boolean
  canConfigure?: boolean
  showFullscreen?: boolean
  locale?: Locale
}>(), { filterActive: false, canRename: false, canShare: false, canConfigure: false, showFullscreen: true, locale: undefined })

const emit = defineEmits<{ rename: [title: string]; share: []; settings: []; fullscreen: []; 'reset-filter': []; 'filter-change': [patch: Partial<KanbanFilterState>] }>()
const { t } = useI18n(kanbanMessages, () => props.locale)
const editing = ref(false)
const draft = ref('')
const input = ref<HTMLInputElement | null>(null)
const search = ref<InstanceType<typeof FaTextField> | null>(null)

async function startRename(): Promise<void> {
  if (!props.canRename) return
  draft.value = props.title
  editing.value = true
  await nextTick()
  input.value?.select()
}

function commitRename(): void {
  if (!editing.value) return
  editing.value = false
  const value = draft.value.trim()
  if (value && value !== props.title) emit('rename', value)
}

function focusSearch(): void {
  ;(search.value?.$el as HTMLElement | undefined)?.querySelector('input')?.focus()
}

defineExpose({ focusSearch })
</script>

<template>
  <div class="fa-kanban-toolbar">
    <div class="fa-kanban-toolbar__title">
      <input
        v-if="editing"
        ref="input"
        v-model="draft"
        class="fa-kanban-toolbar__title-input"
        :aria-label="t('renameLabel')"
        @blur="commitRename"
        @keydown.enter.prevent="commitRename"
        @keydown.esc.prevent="editing = false"
      />
      <h1 v-else class="fa-kanban-toolbar__heading">
        <button v-if="canRename" type="button" class="fa-kanban-toolbar__rename" :title="t('renameHint')" @click="startRename">{{ title }}</button>
        <template v-else>{{ title }}</template>
      </h1>
      <div v-if="stats" class="fa-kanban-toolbar__progress">
        <span>{{ t('progress', { done: stats.done, total: stats.total }) }}</span>
        <span class="fa-kanban-toolbar__bar" role="progressbar" :aria-valuenow="stats.progress" aria-valuemin="0" aria-valuemax="100" :aria-label="t('progress', { done: stats.done, total: stats.total })">
          <span :style="{ width: `${stats.progress}%` }" />
        </span>
        <span>{{ stats.progress }} %</span>
      </div>
    </div>
    <div class="fa-kanban-toolbar__tools">
      <FaTextField ref="search" :model-value="filter.query" class="fa-kanban-toolbar__search" type="search" :label="t('search')" :placeholder="t('searchPlaceholder')" hide-label @update:model-value="emit('filter-change', { query: $event })" />
      <select :value="filter.priority" class="fa-kanban-select" :aria-label="t('priorityFilter')" @change="emit('filter-change', { priority: ($event.target as HTMLSelectElement).value as KanbanFilterState['priority'] })">
        <option value="">{{ t('allPriorities') }}</option>
        <option v-for="priority in PRIORITIES" :key="priority" :value="priority">{{ t(`priority_${priority}`) }}</option>
      </select>
      <select :value="filter.due" class="fa-kanban-select" :aria-label="t('dueFilter')" @change="emit('filter-change', { due: ($event.target as HTMLSelectElement).value as KanbanFilterState['due'] })">
        <option value="">{{ t('allDue') }}</option>
        <option v-for="state in DUE_STATES" :key="state" :value="state">{{ t(`due_${state}`) }}</option>
      </select>
      <FaButton v-if="filterActive" size="sm" variant="ghost" icon="close" @click="emit('reset-filter')">{{ t('resetFilter') }}</FaButton>
      <FaButton v-if="showFullscreen" variant="ghost" icon="expand" icon-only :label="t('fullscreen')" @click="emit('fullscreen')" />
      <FaButton v-if="canShare" variant="ghost" icon="share" icon-only :label="t('share')" @click="emit('share')" />
      <FaButton v-if="canConfigure" variant="ghost" icon="settings" icon-only :label="t('settings')" @click="emit('settings')" />
    </div>
  </div>
</template>
