// packages-js/ui-react/src/synopsis/SynopsisCommands.tsx
import { Fragment } from 'react'
import type { SynopsisTranslate, SynopsisView } from '@flowaudit/ui-core'

function Consolidated({ view, t }: { view: SynopsisView; t: SynopsisTranslate }) {
  return (
    <details className="fa-synopsis-commands fa-synopsis-commands--consolidated">
      <summary>{t('consolidated')}</summary>
      <dl>
        {view.consolidated.map((entry) => (
          <Fragment key={`${entry.section}-${entry.paragraph}-${entry.inserted}`}>
            <dt>
              {t('consolidatedEntry', { section: entry.section, paragraph: entry.paragraph })}{' '}
              {entry.repealed ? <span>{t('repealed')}</span> : entry.inserted ? <span>{t('inserted')}</span> : null}
            </dt>
            <dd className={entry.repealed ? 'fa-synopsis-commands__repealed' : undefined}>{entry.text}</dd>
          </Fragment>
        ))}
      </dl>
    </details>
  )
}

/** Gesetzessynopse: offene Änderungsbefehle und konsolidierte Arbeitsfassung. */
export function SynopsisCommands({ view, t }: { view: SynopsisView; t: SynopsisTranslate }) {
  return (
    <>
      {view.openCommands.length ? (
        <section className="fa-synopsis-commands" aria-label={t('openCommands')}>
          <h3>{t('openCommands')}</h3>
          <ol>
            {view.openCommands.map((command) => <li key={command}>{command}</li>)}
          </ol>
        </section>
      ) : null}
      {view.consolidated.length ? <Consolidated view={view} t={t} /> : null}
    </>
  )
}

// packages-js/ui/src/synopsis/SynopsisCommands.vue
<script setup lang="ts">
import type { SynopsisTranslate, SynopsisView } from '@flowaudit/ui-core'

/** Gesetzessynopse: offene Änderungsbefehle und konsolidierte Arbeitsfassung. */
defineProps<{ view: SynopsisView; t: SynopsisTranslate }>()
</script>

<template>
  <section v-if="view.openCommands.length" class="fa-synopsis-commands" :aria-label="t('openCommands')">
    <h3>{{ t('openCommands') }}</h3>
    <ol>
      <li v-for="command in view.openCommands" :key="command">{{ command }}</li>
    </ol>
  </section>
  <details v-if="view.consolidated.length" class="fa-synopsis-commands fa-synopsis-commands--consolidated">
    <summary>{{ t('consolidated') }}</summary>
    <dl>
      <template v-for="entry in view.consolidated" :key="`${entry.section}-${entry.paragraph}-${entry.inserted}`">
        <dt>
          {{ t('consolidatedEntry', { section: entry.section, paragraph: entry.paragraph }) }}
          <span v-if="entry.repealed">{{ t('repealed') }}</span>
          <span v-else-if="entry.inserted">{{ t('inserted') }}</span>
        </dt>
        <dd :class="{ 'fa-synopsis-commands__repealed': entry.repealed }">{{ entry.text }}</dd>
      </template>
    </dl>
  </details>
</template>
