// packages-js/ui/src/benford/BenfordDigits.vue
<script setup lang="ts">
import { computed } from 'vue'
import { benfordDigitColumns, benfordDigitRows, benfordMessages, type Conformity } from '@auditcore/ui-core'
import { useI18n, type Locale } from '../i18n'
import FaTable from '../table/FaTable.vue'

const props = withDefaults(defineProps<{ conformity: Conformity; locale?: Locale }>(), { locale: undefined })
const { t, locale: active } = useI18n(benfordMessages, () => props.locale)
const columns = computed(() => benfordDigitColumns(t, active.value))
const rows = computed(() => benfordDigitRows(props.conformity))
</script>

<template>
  <details class="fa-benford__digits" :open="conformity.rows.length <= 10">
    <summary>{{ t('table') }}</summary>
    <FaTable :columns="columns" :rows="rows" :caption="t('table')" :locale="locale" data-testid="benford-table">
      <template #cell-exceeds="{ value }">
        <span v-if="value === true" class="fa-benford__flag">{{ t('yes') }}</span>
      </template>
    </FaTable>
  </details>
</template>

// packages-js/ui-react/src/benford/BenfordDigits.tsx
import { benfordDigitColumns, benfordDigitRows, type BenfordTranslate, type Conformity, type Locale } from '@auditcore/ui-core'
import { FlowauditTable } from '../table/FlowauditTable'

export interface BenfordDigitsProps {
  conformity: Conformity
  t: BenfordTranslate
  locale: Locale
  /** Sprache der Tabelle wie in Vue (Prop der Hauptkomponente). */
  tableLocale?: Locale
}

/** Zifferntabelle, bei bis zu zehn Ziffern aufgeklappt (wie `BenfordDigits.vue`). */
export function BenfordDigits({ conformity, t, locale, tableLocale }: BenfordDigitsProps) {
  return (
    <details className="fa-benford__digits" open={conformity.rows.length <= 10}>
      <summary>{t('table')}</summary>
      <FlowauditTable
        columns={benfordDigitColumns(t, locale)}
        rows={benfordDigitRows(conformity)}
        caption={t('table')}
        locale={tableLocale}
        testId="benford-table"
        renderCell={(column, _row, value) => (column.key === 'exceeds' ? (value === true ? <span className="fa-benford__flag">{t('yes')}</span> : <></>) : undefined)}
      />
    </details>
  )
}
