// packages-js/ui-react/src/tabular/TableImport.tsx
import { useState, type ChangeEvent } from 'react'
import type { DecimalSeparator } from '@auditcore/common'
import {
  createTableImportController,
  importDelimiterText,
  importOptionalColumn,
  importPreview,
  importRejectedLines,
  tabularMessages,
  type ImportedColumns,
  type Locale,
  type TableImportController,
  type TableImportData,
  type Translate,
  type TabularMessageKey,
} from '@auditcore/ui-core'
import { Button } from '../base/Button'
import { useTranslation } from '../i18n'
import { useElementId, useStoreState } from '../store'

export interface TableImportProps {
  /** `items`: zusätzlich Kennungs- und Schichtspalte wählbar. */
  mode?: 'values' | 'items'
  locale?: Locale
  onImport?: (columns: ImportedColumns) => void
}

type Select = ChangeEvent<HTMLSelectElement>

function ColumnSelect({ label, value, header, none, onChange }: { label: string; value: number | null; header: readonly string[]; none?: string; onChange: (value: string) => void }) {
  return (
    <label className="fa-import__field">
      <span>{label}</span>
      <select value={value ?? ''} onChange={(event: Select) => onChange(event.target.value)}>
        {none === undefined ? null : <option value="">{none}</option>}
        {header.map((name, index) => <option key={index} value={index}>{name}</option>)}
      </select>
    </label>
  )
}

function ImportFields({ state, controller, mode, t }: { state: TableImportData; controller: TableImportController; mode: 'values' | 'items'; t: Translate<TabularMessageKey> }) {
  const header = state.table?.header ?? []
  return (
    <div className="fa-import__grid">
      <label className="fa-import__check">
        <input type="checkbox" checked={state.hasHeader} onChange={(event) => { controller.setHasHeader(event.target.checked); controller.reparse() }} />
        {t('header')}
      </label>
      <ColumnSelect label={t('valueColumn')} value={state.valueColumn} header={header} onChange={(value) => controller.setValueColumn(Number(value))} />
      {mode === 'items' ? (
        <>
          <ColumnSelect label={t('idColumn')} value={state.idColumn} header={header} none={t('none')} onChange={(value) => controller.setIdColumn(importOptionalColumn(value))} />
          <ColumnSelect label={t('stratumColumn')} value={state.stratumColumn} header={header} none={t('none')} onChange={(value) => controller.setStratumColumn(importOptionalColumn(value))} />
        </>
      ) : null}
      <label className="fa-import__field">
        <span>{t('decimal')}</span>
        <select value={state.decimal} onChange={(event: Select) => controller.setDecimal(event.target.value as DecimalSeparator)}>
          <option value=",">{t('decimalComma')}</option>
          <option value=".">{t('decimalDot')}</option>
        </select>
      </label>
    </div>
  )
}

/** Datei-Import wie `TableImport` (Vue): CSV/TSV/Text lesen, Spalten zuordnen, Werte übernehmen. */
export function TableImport({ mode = 'values', locale, onImport }: TableImportProps) {
  const { t } = useTranslation(tabularMessages, locale)
  const [controller] = useState(createTableImportController)
  const state = useStoreState(controller.store)
  const id = useElementId('fa-import')
  const preview = importPreview(state)
  const onFile = async (event: ChangeEvent<HTMLInputElement>): Promise<void> => {
    const file = event.target.files?.[0]
    if (file) await controller.read(file)
  }
  return (
    <div className="fa-import">
      <label htmlFor={`${id}-file`} className="fa-import__label">{t('file')}</label>
      <input id={`${id}-file`} className="fa-import__file" type="file" accept=".csv,.tsv,.txt,text/csv,text/plain" onChange={(event) => void onFile(event)} />
      {state.table ? (
        <>
          <p className="fa-import__note" aria-live="polite">
            {t('summary', { file: state.filename, rows: state.table.rows.length, delimiter: importDelimiterText(state.table, t('tab')) })}
          </p>
          <ImportFields state={state} controller={controller} mode={mode} t={t} />
          {preview?.rejected.length ? (
            <p className="fa-import__warning" role="status">{t('rejected', { count: preview.rejected.length, lines: importRejectedLines(preview) })}</p>
          ) : null}
          <Button variant="secondary" label={t('apply')} testId="import-apply" onClick={() => preview && onImport?.(preview)}>{t('apply')}</Button>
        </>
      ) : null}
    </div>
  )
}

// packages-js/ui/src/tabular/TableImport.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { DecimalSeparator } from '@auditcore/common'
import { importDelimiterText, importOptionalColumn, importRejectedLines, tabularMessages, type ImportedColumns } from '@auditcore/ui-core'
import { useId } from '../composables/useId'
import FaButton from '../base/FaButton.vue'
import { useI18n, type Locale } from '../i18n'
import { useTableImport } from './useTableImport'

const props = withDefaults(defineProps<{
  /** `items`: zusätzlich Kennungs- und Schichtspalte wählbar. */
  mode?: 'values' | 'items'
  locale?: Locale
}>(), { mode: 'values', locale: undefined })

const emit = defineEmits<{ import: [columns: ImportedColumns] }>()
const { t } = useI18n(tabularMessages, () => props.locale)
const { controller, state, preview } = useTableImport()
const id = useId('fa-import')
const delimiterLabel = computed(() => importDelimiterText(state.value.table, t('tab')))
const rejectedLines = computed(() => importRejectedLines(preview.value))

async function onFile(event: Event): Promise<void> {
  const file = (event.target as HTMLInputElement).files?.[0]
  if (file) await controller.read(file)
}

function onHeader(event: Event): void {
  controller.setHasHeader((event.target as HTMLInputElement).checked)
  controller.reparse()
}

const selected = (event: Event): string => (event.target as HTMLSelectElement).value

function apply(): void {
  if (preview.value) emit('import', preview.value)
}
</script>

<template>
  <div class="fa-import">
    <label :for="`${id}-file`" class="fa-import__label">{{ t('file') }}</label>
    <input :id="`${id}-file`" class="fa-import__file" type="file" accept=".csv,.tsv,.txt,text/csv,text/plain" @change="onFile" />
    <template v-if="state.table">
      <p class="fa-import__note" aria-live="polite">
        {{ t('summary', { file: state.filename, rows: state.table.rows.length, delimiter: delimiterLabel }) }}
      </p>
      <div class="fa-import__grid">
        <label class="fa-import__check">
          <input type="checkbox" :checked="state.hasHeader" @change="onHeader" />
          {{ t('header') }}
        </label>
        <label class="fa-import__field">
          <span>{{ t('valueColumn') }}</span>
          <select :value="state.valueColumn" @change="controller.setValueColumn(Number(selected($event)))">
            <option v-for="(name, index) in state.table.header" :key="index" :value="index">{{ name }}</option>
          </select>
        </label>
        <template v-if="mode === 'items'">
          <label class="fa-import__field">
            <span>{{ t('idColumn') }}</span>
            <select :value="state.idColumn ?? ''" @change="controller.setIdColumn(importOptionalColumn(selected($event)))">
              <option value="">{{ t('none') }}</option>
              <option v-for="(name, index) in state.table.header" :key="index" :value="index">{{ name }}</option>
            </select>
          </label>
          <label class="fa-import__field">
            <span>{{ t('stratumColumn') }}</span>
            <select :value="state.stratumColumn ?? ''" @change="controller.setStratumColumn(importOptionalColumn(selected($event)))">
              <option value="">{{ t('none') }}</option>
              <option v-for="(name, index) in state.table.header" :key="index" :value="index">{{ name }}</option>
            </select>
          </label>
        </template>
        <label class="fa-import__field">
          <span>{{ t('decimal') }}</span>
          <select :value="state.decimal" @change="controller.setDecimal(selected($event) as DecimalSeparator)">
            <option value=",">{{ t('decimalComma') }}</option>
            <option value=".">{{ t('decimalDot') }}</option>
          </select>
        </label>
      </div>
      <p v-if="preview?.rejected.length" class="fa-import__warning" role="status">
        {{ t('rejected', { count: preview.rejected.length, lines: rejectedLines }) }}
      </p>
      <FaButton variant="secondary" :label="t('apply')" data-testid="import-apply" @click="apply">{{ t('apply') }}</FaButton>
    </template>
  </div>
</template>
