// packages-js/bpmn-react/src/views/IssueList.tsx
/** Validation issues grouped by severity with jump to the element. */

import { useState } from 'react'
import { issueMessage, severityLabel, type Severity, type ValidationIssue } from '@auditcore/bpmn-flowaudit'
import { countSeverity, filterIssues, ISSUE_ICONS, SEVERITIES } from '@auditcore/bpmn-flowaudit/ui'
import { FaIcon } from '../base/FaIcon'
import { useI18n } from '../i18n'

export interface IssueListProps {
  issues: ValidationIssue[]
  running?: boolean
  error?: string | null
  onJump?: (elementId: string) => void
}

export function IssueList({ issues, running, error, onJump }: IssueListProps) {
  const { t, locale } = useI18n()
  const [filter, setFilter] = useState<Severity | 'alle'>('alle')
  return (
    <section className="fa-issues" aria-label={t('issues.label')} aria-busy={Boolean(running)}>
      <div className="fa-issues__filter" role="group">
        <button type="button" className="fa-chip" aria-pressed={filter === 'alle'} onClick={() => setFilter('alle')}>{t('issues.filter.all')} {issues.length}</button>
        {SEVERITIES.map((severity) => (
          <button key={severity} type="button" className="fa-chip" aria-pressed={filter === severity} onClick={() => setFilter(severity)}>
            <FaIcon name={ISSUE_ICONS[severity]} size={14} />
            {severityLabel(severity, locale)} {countSeverity(issues, severity)}
          </button>
        ))}
      </div>
      {error ? <p className="fa-badge fa-badge--danger">{error}</p> : null}
      {!issues.length ? <p className="fa-help">{t('issues.none')}</p> : null}
      <ol className="fa-issues__list">
        {filterIssues(issues, filter).map((item, index) => (
          <li key={index} className={`fa-issue fa-issue--${item.severity}`}>
            <FaIcon name={ISSUE_ICONS[item.severity]} size={16} label={severityLabel(item.severity, locale)} />
            <div className="fa-issue__body">
              <p>{issueMessage(item, locale)}</p>
              <span className="fa-help">{item.ruleId}</span>
            </div>
            {item.elementId ? <button type="button" className="fa-btn fa-btn--ghost" onClick={() => onJump?.(item.elementId as string)}>{t('issues.jump')}</button> : null}
          </li>
        ))}
      </ol>
    </section>
  )
}

// packages-js/bpmn-vue/src/components/views/IssueList.vue
<script setup lang="ts">
/** Validation issues grouped by severity with jump to the element. */
import { computed, ref } from 'vue'
import { issueMessage, severityLabel, type Severity, type ValidationIssue } from '@auditcore/bpmn-flowaudit'
import { countSeverity, filterIssues, ISSUE_ICONS as ICONS, SEVERITIES } from '@auditcore/bpmn-flowaudit/ui'
import FaIcon from '../base/FaIcon.vue'
import { useI18n } from '../../i18n/useI18n'

const props = defineProps<{ issues: ValidationIssue[]; running?: boolean; error?: string | null }>()
const emit = defineEmits<{ (e: 'jump', elementId: string): void }>()
const { t, locale } = useI18n()
const filter = ref<Severity | 'alle'>('alle')

const shown = computed(() => filterIssues(props.issues, filter.value))
const count = (severity: Severity) => countSeverity(props.issues, severity)
</script>

<template>
  <section class="fa-issues" :aria-label="t('issues.label')" :aria-busy="running">
    <div class="fa-issues__filter" role="group">
      <button type="button" class="fa-chip" :aria-pressed="filter === 'alle'" @click="filter = 'alle'">{{ t('issues.filter.all') }} {{ issues.length }}</button>
      <button v-for="severity in SEVERITIES" :key="severity" type="button" class="fa-chip" :aria-pressed="filter === severity" @click="filter = severity">
        <FaIcon :name="ICONS[severity]" :size="14" />{{ severityLabel(severity, locale) }} {{ count(severity) }}
      </button>
    </div>
    <p v-if="error" class="fa-badge fa-badge--danger">{{ error }}</p>
    <p v-if="!issues.length" class="fa-help">{{ t('issues.none') }}</p>
    <ol class="fa-issues__list">
      <li v-for="(item, index) in shown" :key="index" class="fa-issue" :class="`fa-issue--${item.severity}`">
        <FaIcon :name="ICONS[item.severity]" :size="16" :label="severityLabel(item.severity, locale)" />
        <div class="fa-issue__body">
          <p>{{ issueMessage(item, locale) }}</p>
          <span class="fa-help">{{ item.ruleId }}</span>
        </div>
        <button v-if="item.elementId" type="button" class="fa-btn fa-btn--ghost" @click="emit('jump', item.elementId)">{{ t('issues.jump') }}</button>
      </li>
    </ol>
  </section>
</template>
