// packages-js/ui/src/extrapolation/ExtrapolationSettings.vue
<script setup lang="ts">
import { computed } from 'vue'
import {
  confidenceChoices,
  extrapolationConfidenceLabel,
  extrapolationIssueText,
  extrapolationMessages,
  extrapolationMethodGroups,
  type ExtrapolationController,
  type ExtrapolationData,
  type ExtrapolationMethod,
} from '@auditcore/ui-core'
import { useId } from '../composables/useId'
import { useI18n, type Locale } from '../i18n'

const props = withDefaults(defineProps<{
  controller: ExtrapolationController
  state: ExtrapolationData
  method: ExtrapolationMethod | null
  locale?: Locale
}>(), { locale: undefined })
const { t, locale: active } = useI18n(extrapolationMessages, () => props.locale)
const id = useId('fa-extrapolation-settings')
const catalogue = computed(() => props.state.catalogue)
const groups = computed(() => (catalogue.value ? extrapolationMethodGroups(catalogue.value, t) : []))
const levels = computed(() => (catalogue.value ? confidenceChoices(catalogue.value, props.method) : []))
const issue = (key: string): string => extrapolationIssueText(props.state.issues, key, t)
const value = (event: Event): string => (event.target as HTMLInputElement | HTMLSelectElement).value
const level = (text: string): number | null => (text === '' ? null : Number(text))
</script>

<template>
  <section class="fa-extrapolation__card" :aria-labelledby="`${id}-title`">
    <h3 :id="`${id}-title`" class="fa-extrapolation__heading">{{ t('settings') }}</h3>
    <div class="fa-extrapolation__settings">
      <label class="fa-extrapolation__field">
        <span class="fa-extrapolation__label">{{ t('method') }}</span>
        <select class="fa-extrapolation__select" :value="state.form.methodId" data-testid="extrapolation-method" @change="controller.selectMethod(value($event))">
          <option value="">{{ t('choose') }}</option>
          <optgroup v-for="group in groups" :key="group.label" :label="group.label">
            <option v-for="entry in group.methods" :key="entry.id" :value="entry.id">{{ entry.label }}</option>
          </optgroup>
        </select>
      </label>
      <template v-if="method?.statistical">
        <label class="fa-extrapolation__field">
          <span class="fa-extrapolation__label">{{ t('confidence') }}</span>
          <select class="fa-extrapolation__select" :value="state.form.confidence === null ? '' : String(state.form.confidence)" data-testid="extrapolation-confidence" @change="controller.setConfidence(level(value($event)))">
            <option value="">{{ t('choose') }}</option>
            <option v-for="entry in levels" :key="entry" :value="String(entry)">{{ extrapolationConfidenceLabel(entry, active) }}</option>
          </select>
        </label>
        <label class="fa-extrapolation__field">
          <span class="fa-extrapolation__label">{{ t('factorProfile') }}</span>
          <select class="fa-extrapolation__select" :value="state.form.profileId ?? ''" data-testid="extrapolation-profile" @change="controller.setProfile(value($event) || null)">
            <option value="">{{ t('choose') }}</option>
            <option v-for="entry in catalogue?.factor_profiles ?? []" :key="entry.id" :value="entry.id">{{ entry.label }}</option>
          </select>
        </label>
      </template>
      <label v-if="method?.needs_sample_size" class="fa-extrapolation__field">
        <span class="fa-extrapolation__label">{{ t('sampleSize') }}</span>
        <input class="fa-extrapolation__input fa-extrapolation__input--number" inputmode="numeric" :value="state.form.sampleSize" :aria-invalid="issue('sampleSize') ? 'true' : undefined" data-testid="extrapolation-sample-size" @input="controller.setSampleSize(value($event))" />
        <span v-if="issue('sampleSize')" class="fa-extrapolation__error">{{ issue('sampleSize') }}</span>
        <span class="fa-extrapolation__hint">{{ t('sampleSizeHint') }}</span>
      </label>
      <label class="fa-extrapolation__field">
        <span class="fa-extrapolation__label">{{ t('materiality') }} (%)</span>
        <input class="fa-extrapolation__input fa-extrapolation__input--number" inputmode="decimal" :value="state.form.materiality" :aria-invalid="issue('materiality') ? 'true' : undefined" data-testid="extrapolation-materiality" @input="controller.setMateriality(value($event))" />
        <span v-if="issue('materiality')" class="fa-extrapolation__error">{{ issue('materiality') }}</span>
        <span class="fa-extrapolation__hint">{{ t('materialityHint') }}</span>
      </label>
    </div>
    <details v-if="method" class="fa-extrapolation__source">
      <summary>{{ t('methodSource') }}</summary>
      <p>{{ method.source }}</p>
      <code>{{ method.formula }}</code>
    </details>
  </section>
</template>

// packages-js/ui-react/src/extrapolation/ExtrapolationSettings.tsx
import { confidenceChoices, extrapolationConfidenceLabel, extrapolationIssueText, extrapolationMethodGroups } from '@auditcore/ui-core'
import { classes, useElementId } from '../store'
import type { UseExtrapolation } from './useExtrapolation'

function NumberField({ view, field, label, hint, testId }: { view: UseExtrapolation; field: 'sampleSize' | 'materiality'; label: string; hint: string; testId: string }) {
  const { state, controller, t } = view
  const issue = extrapolationIssueText(state.issues, field, t)
  const change = field === 'sampleSize' ? controller.setSampleSize : controller.setMateriality
  return (
    <label className="fa-extrapolation__field">
      <span className="fa-extrapolation__label">{label}</span>
      <input className={classes('fa-extrapolation__input', 'fa-extrapolation__input--number')} inputMode={field === 'sampleSize' ? 'numeric' : 'decimal'} value={state.form[field]} aria-invalid={issue ? 'true' : undefined} data-testid={testId} onChange={(event) => change(event.target.value)} />
      {issue ? <span className="fa-extrapolation__error">{issue}</span> : null}
      <span className="fa-extrapolation__hint">{hint}</span>
    </label>
  )
}

function StatisticalFields({ view }: { view: UseExtrapolation }) {
  const { state, controller, t, method } = view
  const catalogue = state.catalogue
  if (!catalogue || !method?.statistical) return null
  return (
    <>
      <label className="fa-extrapolation__field">
        <span className="fa-extrapolation__label">{t('confidence')}</span>
        <select className="fa-extrapolation__select" value={state.form.confidence === null ? '' : String(state.form.confidence)} data-testid="extrapolation-confidence" onChange={(event) => controller.setConfidence(event.target.value === '' ? null : Number(event.target.value))}>
          <option value="">{t('choose')}</option>
          {confidenceChoices(catalogue, method).map((level) => <option key={level} value={String(level)}>{extrapolationConfidenceLabel(level, view.locale)}</option>)}
        </select>
      </label>
      <label className="fa-extrapolation__field">
        <span className="fa-extrapolation__label">{t('factorProfile')}</span>
        <select className="fa-extrapolation__select" value={state.form.profileId ?? ''} data-testid="extrapolation-profile" onChange={(event) => controller.setProfile(event.target.value || null)}>
          <option value="">{t('choose')}</option>
          {catalogue.factor_profiles.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}
        </select>
      </label>
    </>
  )
}

/** Methode, Konfidenzniveau, Faktorprofil, Umfang und Wesentlichkeit (wie `ExtrapolationSettings.vue`). */
export function ExtrapolationSettings({ view }: { view: UseExtrapolation }) {
  const { state, controller, t, method } = view
  const id = useElementId('fa-extrapolation-settings')
  if (!state.catalogue) return null
  const groups = extrapolationMethodGroups(state.catalogue, t)
  return (
    <section className="fa-extrapolation__card" aria-labelledby={`${id}-title`}>
      <h3 id={`${id}-title`} className="fa-extrapolation__heading">{t('settings')}</h3>
      <div className="fa-extrapolation__settings">
        <label className="fa-extrapolation__field">
          <span className="fa-extrapolation__label">{t('method')}</span>
          <select className="fa-extrapolation__select" value={state.form.methodId} data-testid="extrapolation-method" onChange={(event) => controller.selectMethod(event.target.value)}>
            <option value="">{t('choose')}</option>
            {groups.map((group) => (
              <optgroup key={group.label} label={group.label}>
                {group.methods.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}
              </optgroup>
            ))}
          </select>
        </label>
        <StatisticalFields view={view} />
        {method?.needs_sample_size ? <NumberField view={view} field="sampleSize" label={t('sampleSize')} hint={t('sampleSizeHint')} testId="extrapolation-sample-size" /> : null}
        <NumberField view={view} field="materiality" label={`${t('materiality')} (%)`} hint={t('materialityHint')} testId="extrapolation-materiality" />
      </div>
      {method ? (
        <details className="fa-extrapolation__source">
          <summary>{t('methodSource')}</summary>
          <p>{method.source}</p>
          <code>{method.formula}</code>
        </details>
      ) : null}
    </section>
  )
}
