// packages-js/bpmn-vue/src/components/collection/DiagramInfoColumn.vue
<script setup lang="ts">
/**
 * Info column of the selected diagram: key info, tags, approvals and the
 * keyboard-accessible alternative to drag-and-drop („move to …“).
 */
import { computed, ref } from 'vue'
import type { DiagramEntry, Folder } from '@auditcore/bpmn-flowaudit'
import { infoRows, toggledTags } from '@auditcore/bpmn-flowaudit/ui'
import FaIcon from '../base/FaIcon.vue'
import PromptDialog from '../base/PromptDialog.vue'
import { useI18n } from '../../i18n/useI18n'
import type { CollectionStore } from '../../stores/collectionStore'

const props = defineProps<{ store: CollectionStore; entry: DiagramEntry }>()
const emit = defineEmits<{ (e: 'open', id: string): void; (e: 'deleted'): void }>()
const { t, locale } = useI18n()
const renaming = ref(false)
const tagging = ref(false)

const folders = computed<Folder[]>(() => [...props.store.collection.value.folders.values()])
const tags = computed(() => [...props.store.collection.value.tags.values()])
const rows = computed(() => infoRows(props.entry, t, locale.value))
const toggleTag = (id: string) => void props.store.setTags(props.entry.id, toggledTags(props.entry, id))

async function remove(): Promise<void> {
  if (!window.confirm(t('common.confirmDelete', { name: props.entry.name }))) return
  await props.store.removeDiagram(props.entry.id)
  emit('deleted')
}
</script>

<template>
  <section class="fa-info-column" :aria-label="t('collection.info')">
    <header class="fa-info-column__head">
      <h3>{{ entry.name }}</h3>
      <button type="button" class="fa-btn fa-btn--primary" @click="emit('open', entry.id)"><FaIcon name="folder-open" :size="16" />{{ t('collection.open') }}</button>
    </header>
    <dl class="fa-info-column__list">
      <template v-for="[term, value] in rows" :key="term">
        <dt>{{ term }}</dt>
        <dd>{{ value }}</dd>
      </template>
    </dl>
    <div class="fa-info-column__tags">
      <span v-for="tag in tags.filter((item) => entry.tags.includes(item.id))" :key="tag.id" class="fa-chip" :style="{ borderColor: tag.color }"><FaIcon name="tag" :size="12" />{{ tag.name }}</span>
    </div>
    <details class="fa-info-column__more">
      <summary>{{ t('collection.tags') }}</summary>
      <div class="fa-info-column__tags">
        <button v-for="tag in tags" :key="tag.id" type="button" class="fa-chip" :aria-pressed="entry.tags.includes(tag.id)" @click="toggleTag(tag.id)">{{ tag.name }}</button>
        <button type="button" class="fa-chip" @click="tagging = true"><FaIcon name="plus" :size="12" />{{ t('collection.newTag') }}</button>
      </div>
    </details>
    <label class="fa-field">
      <span class="fa-label">{{ t('collection.moveTo') }}</span>
      <select class="fa-select" :value="entry.folderId ?? ''" @change="store.moveDiagram(entry.id, ($event.target as HTMLSelectElement).value || null)">
        <option value="">{{ t('collection.topLevel') }}</option>
        <option v-for="folder in folders" :key="folder.id" :value="folder.id">{{ folder.name }}</option>
      </select>
    </label>
    <div v-if="entry.approvals.length" class="fa-info-column__approvals">
      <span class="fa-label">{{ t('collection.approvals') }}</span>
      <p v-for="approval in entry.approvals" :key="approval.version" class="fa-help"><FaIcon name="lock" :size="12" /> {{ approval.version }} · {{ approval.approvedOn }} · <code>{{ approval.sha256.slice(0, 16) }}…</code></p>
    </div>
    <div class="fa-info-column__actions">
      <button type="button" class="fa-btn" @click="renaming = true"><FaIcon name="new" :size="16" />{{ t('collection.rename') }}</button>
      <button type="button" class="fa-btn fa-btn--danger" @click="remove"><FaIcon name="delete" :size="16" />{{ t('common.delete') }}</button>
    </div>
    <PromptDialog v-model:open="renaming" :title="t('collection.rename')" :label="t('collection.diagramName')" :value="entry.name" @confirm="store.renameDiagram(entry.id, $event)" />
    <PromptDialog v-model:open="tagging" :title="t('collection.newTag')" :label="t('collection.tags')" @confirm="store.createTag($event)" />
  </section>
</template>

// packages-js/bpmn-react/src/collection/DiagramInfoColumn.tsx
/**
 * Info column of the selected diagram: key info, tags, approvals and the
 * keyboard-accessible alternative to drag-and-drop („move to …“).
 */

import { Fragment, useState } from 'react'
import type { DiagramEntry, Tag } from '@auditcore/bpmn-flowaudit'
import { infoRows, toggledTags } from '@auditcore/bpmn-flowaudit/ui'
import { FaIcon } from '../base/FaIcon'
import { PromptDialog } from '../base/PromptDialog'
import { classes } from '../hooks'
import { useI18n } from '../i18n'
import type { CollectionBinding } from '../useCollection'

export interface DiagramInfoColumnProps {
  /** Collection binding from `useCollection` / `useCollectionBinding`. */
  store: CollectionBinding
  entry: DiagramEntry
  className?: string
  onOpen?: (id: string) => void
  onDeleted?: () => void
}

function Tags({ store, entry, tags, onNewTag }: { store: CollectionBinding; entry: DiagramEntry; tags: Tag[]; onNewTag: () => void }) {
  const { t } = useI18n()
  const toggleTag = (id: string) => void store.setTags(entry.id, toggledTags(entry, id))
  return (
    <>
      <div className="fa-info-column__tags">
        {tags.filter((item) => entry.tags.includes(item.id)).map((tag) => (
          <span key={tag.id} className="fa-chip" style={{ borderColor: tag.color }}><FaIcon name="tag" size={12} />{tag.name}</span>
        ))}
      </div>
      <details className="fa-info-column__more">
        <summary>{t('collection.tags')}</summary>
        <div className="fa-info-column__tags">
          {tags.map((tag) => (
            <button key={tag.id} type="button" className="fa-chip" aria-pressed={entry.tags.includes(tag.id)} onClick={() => toggleTag(tag.id)}>{tag.name}</button>
          ))}
          <button type="button" className="fa-chip" onClick={onNewTag}><FaIcon name="plus" size={12} />{t('collection.newTag')}</button>
        </div>
      </details>
    </>
  )
}

function Location({ store, entry }: { store: CollectionBinding; entry: DiagramEntry }) {
  const { t } = useI18n()
  return (
    <>
      <label className="fa-field">
        <span className="fa-label">{t('collection.moveTo')}</span>
        <select className="fa-select" value={entry.folderId ?? ''} onChange={(event) => void store.moveDiagram(entry.id, event.target.value || null)}>
          <option value="">{t('collection.topLevel')}</option>
          {[...store.state.collection.folders.values()].map((folder) => (
            <option key={folder.id} value={folder.id}>{folder.name}</option>
          ))}
        </select>
      </label>
      {entry.approvals.length ? (
        <div className="fa-info-column__approvals">
          <span className="fa-label">{t('collection.approvals')}</span>
          {entry.approvals.map((approval) => (
            <p key={approval.version} className="fa-help"><FaIcon name="lock" size={12} /> {approval.version} · {approval.approvedOn} · <code>{approval.sha256.slice(0, 16)}…</code></p>
          ))}
        </div>
      ) : null}
    </>
  )
}

export function DiagramInfoColumn({ store, entry, className, onOpen, onDeleted }: DiagramInfoColumnProps) {
  const { t, locale } = useI18n()
  const [renaming, setRenaming] = useState(false)
  const [tagging, setTagging] = useState(false)
  const tags = [...store.state.collection.tags.values()]

  const remove = async () => {
    if (!window.confirm(t('common.confirmDelete', { name: entry.name }))) return
    await store.removeDiagram(entry.id)
    onDeleted?.()
  }

  return (
    <section className={classes('fa-info-column', className)} aria-label={t('collection.info')}>
      <header className="fa-info-column__head">
        <h3>{entry.name}</h3>
        <button type="button" className="fa-btn fa-btn--primary" onClick={() => onOpen?.(entry.id)}><FaIcon name="folder-open" size={16} />{t('collection.open')}</button>
      </header>
      <dl className="fa-info-column__list">
        {infoRows(entry, t, locale).map(([term, value]) => (
          <Fragment key={term}>
            <dt>{term}</dt>
            <dd>{value}</dd>
          </Fragment>
        ))}
      </dl>
      <Tags store={store} entry={entry} tags={tags} onNewTag={() => setTagging(true)} />
      <Location store={store} entry={entry} />
      <div className="fa-info-column__actions">
        <button type="button" className="fa-btn" onClick={() => setRenaming(true)}><FaIcon name="new" size={16} />{t('collection.rename')}</button>
        <button type="button" className="fa-btn fa-btn--danger" onClick={() => void remove()}><FaIcon name="delete" size={16} />{t('common.delete')}</button>
      </div>
      <PromptDialog open={renaming} title={t('collection.rename')} label={t('collection.diagramName')} value={entry.name} onOpenChange={setRenaming} onConfirm={(name) => void store.renameDiagram(entry.id, name)} />
      <PromptDialog open={tagging} title={t('collection.newTag')} label={t('collection.tags')} onOpenChange={setTagging} onConfirm={(name) => void store.createTag(name)} />
    </section>
  )
}
