// packages-js/bpmn-react/src/EditorDialogs.tsx
/** All dialogs of the editor, driven by the editor session and actions (Vue: `EditorDialogs.vue`). */

import { useEffect, useMemo, useState } from 'react'
import { collectExportData, type Approval, type ProcessModel, type ProfileSummary } from '@auditcore/bpmn-flowaudit'
import { dialogPatch, elementNames, EMPTY_EXPORT_DATA, type DialogId, type EditorPorts } from '@auditcore/bpmn-flowaudit/ui'
import { DiagramInfoDialog } from './dialogs/DiagramInfoDialog'
import { ElementSearch } from './dialogs/ElementSearch'
import { EnrichmentDialog } from './dialogs/EnrichmentDialog'
import { EsiDialog } from './dialogs/EsiDialog'
import { ExportDialog } from './dialogs/ExportDialog'
import { ShortcutHelp } from './dialogs/ShortcutHelp'
import { XmlDialog } from './dialogs/XmlDialog'
import { useStoreState } from './hooks'
import type { EditorRuntime } from './useEditorSession'

export interface EditorDialogsProps {
  runtime: EditorRuntime
  name: string
  diagramId?: string
  profiles: ProfileSummary[]
  approvals: Approval[]
  ports: EditorPorts
  onApplyXml: (xml: string) => void
}

/** Model snapshot for search/export/enrichment and XML for the XML view, taken when a dialog opens. */
function useDialogData(runtime: EditorRuntime) {
  const { dialogs } = useStoreState(runtime.ui)
  const { editor } = runtime.session
  const [model, setModel] = useState<ProcessModel | null>(null)
  const [xml, setXml] = useState('')
  const modelWanted = dialogs.search || dialogs.export || dialogs.enrich

  useEffect(() => {
    if (modelWanted && editor.store.get().ready) setModel(editor.model())
  }, [modelWanted, editor])

  useEffect(() => {
    if (dialogs.xml) void editor.exportXml().then(setXml)
  }, [dialogs.xml, editor])

  return { dialogs, model, xml }
}

export function EditorDialogs({ runtime, name, diagramId, profiles, approvals, ports, onApplyXml }: EditorDialogsProps) {
  const { dialogs, model, xml } = useDialogData(runtime)
  const { info } = useStoreState(runtime.session.editor.store)
  const { suggestions } = useStoreState(runtime.actions.store)
  const { editor } = runtime.session
  const { actions, ui } = runtime
  const exportData = useMemo(() => (model ? collectExportData(model) : EMPTY_EXPORT_DATA), [model])
  const names = useMemo(() => elementNames(model), [model])
  const setOpen = (id: DialogId) => (open: boolean) => ui.set(dialogPatch(ui.get(), id, open))
  const jump = (id: string) => void editor.select(id)

  return (
    <>
      <DiagramInfoDialog open={dialogs.info} info={info} profiles={profiles} approvals={approvals} fallbackTitle={name} onOpenChange={setOpen('info')} onApply={actions.applyInfo} onApprove={actions.approve} onNewVersion={actions.newVersion} />
      <ExportDialog open={dialogs.export} defaultTitle={info?.title || name} subtitle={info?.subtitle} data={exportData} confidentiality={info?.confidentiality} excel onOpenChange={setOpen('export')} onExport={(choice) => void actions.runExport(choice)} />
      <EnrichmentDialog open={dialogs.enrich} suggestions={suggestions} names={names} onOpenChange={setOpen('enrich')} onApply={actions.applyEnrichment} />
      <EsiDialog open={dialogs.esi} port={ports.esi} xml={editor.exportXml} diagramId={diagramId} onOpenChange={setOpen('esi')} onJump={jump} />
      <ElementSearch open={dialogs.search} model={model} onOpenChange={setOpen('search')} onJump={jump} />
      <ShortcutHelp open={dialogs.shortcuts} onOpenChange={setOpen('shortcuts')} />
      <XmlDialog open={dialogs.xml} xml={xml} readonly={runtime.isReadonly()} onOpenChange={setOpen('xml')} onApply={onApplyXml} />
    </>
  )
}

// packages-js/bpmn-vue/src/components/EditorDialogs.vue
<script setup lang="ts">
/** All dialogs of the editor, driven by the editor setup and actions. */
import { computed, ref, shallowRef, watch } from 'vue'
import { collectExportData, type Approval, type DiagramInfo, type ProcessModel, type ProfileSummary } from '@auditcore/bpmn-flowaudit'
import { elementNames, EMPTY_EXPORT_DATA } from '@auditcore/bpmn-flowaudit/ui'
import DiagramInfoDialog from './dialogs/DiagramInfoDialog.vue'
import ElementSearch from './dialogs/ElementSearch.vue'
import EnrichmentDialog from './dialogs/EnrichmentDialog.vue'
import EsiDialog from './dialogs/EsiDialog.vue'
import ExportDialog from './dialogs/ExportDialog.vue'
import ShortcutHelp from './dialogs/ShortcutHelp.vue'
import XmlDialog from './dialogs/XmlDialog.vue'
import type { useEditorActions } from '../composables/useEditorActions'
import type { useEditorSetup } from '../composables/useEditorSetup'
import type { EditorPorts } from '../stores/context'

const props = defineProps<{
  setup: ReturnType<typeof useEditorSetup>
  actions: ReturnType<typeof useEditorActions>
  name: string
  diagramId?: string
  profiles: ProfileSummary[]
  approvals: Approval[]
  ports: EditorPorts
}>()
const emit = defineEmits<{ (e: 'apply-xml', xml: string): void }>()

const dialogs = computed(() => props.setup.ui.dialogs)
const editor = props.setup.editor
const model = shallowRef<ProcessModel | null>(null)
const xml = ref('')

watch(
  () => [dialogs.value.search, dialogs.value.export, dialogs.value.enrich],
  (open) => {
    if (open.some(Boolean) && editor.state.ready) model.value = editor.model()
  },
)
watch(
  () => dialogs.value.xml,
  async (open) => {
    if (open) xml.value = await editor.exportXml()
  },
)

const exportData = computed(() => (model.value ? collectExportData(model.value) : EMPTY_EXPORT_DATA))
const names = computed(() => elementNames(model.value))
const info = computed(() => editor.state.info as DiagramInfo | null)
</script>

<template>
  <DiagramInfoDialog
    v-model:open="dialogs.info"
    :info="info"
    :profiles="profiles"
    :approvals="approvals"
    :fallback-title="name"
    @apply="actions.applyInfo"
    @approve="actions.approve"
    @new-version="actions.newVersion"
  />
  <ExportDialog
    v-model:open="dialogs.export"
    :default-title="info?.title || name"
    :subtitle="info?.subtitle"
    :data="exportData"
    :confidentiality="info?.confidentiality"
    excel
    @export="actions.runExport"
  />
  <EnrichmentDialog v-model:open="dialogs.enrich" :suggestions="actions.suggestions.value" :names="names" @apply="actions.applyEnrichment" />
  <EsiDialog v-model:open="dialogs.esi" :port="ports.esi" :xml="() => editor.exportXml()" :diagram-id="diagramId" @jump="editor.select" />
  <ElementSearch v-model:open="dialogs.search" :model="model" @jump="editor.select" />
  <ShortcutHelp v-model:open="dialogs.shortcuts" />
  <XmlDialog v-model:open="dialogs.xml" :xml="xml" :readonly="setup.readonlyNow.value" @apply="emit('apply-xml', $event)" />
</template>
