// packages-js/ui/src/sampling/SamplingDraw.vue
<script setup lang="ts">
import FaButton from '../base/FaButton.vue'
import { useId } from '../composables/useId'
import { useI18n, type Locale } from '../i18n'
import { samplingMessages, selectionErrorKey as errorKey, type AllocationMethod, type MethodProfile, type NamedOption, type SelectionError, type SelectionVariant } from '@auditcore/ui-core'

const props = withDefaults(defineProps<{
  profile: MethodProfile
  variants: readonly NamedOption<SelectionVariant>[]
  allocations: readonly NamedOption<AllocationMethod>[]
  stratified: boolean
  error: SelectionError | null
  busy?: boolean
  canRedraw?: boolean
  locale?: Locale
}>(), { busy: false, canRedraw: false, locale: undefined })

const sampleSize = defineModel<string>('sampleSize', { required: true })
const seed = defineModel<string>('seed', { required: true })
const variant = defineModel<SelectionVariant | null>('variant', { required: true })
const allocation = defineModel<AllocationMethod | null>('allocation', { required: true })
const emit = defineEmits<{ draw: [fresh: boolean] }>()
const { t } = useI18n(samplingMessages, () => props.locale)
const id = useId('fa-sampling-draw')

function onAllocation(event: Event): void {
  const value = (event.target as HTMLSelectElement).value
  allocation.value = value === '' ? null : (value as AllocationMethod)
}
</script>

<template>
  <form class="fa-sampling__form" novalidate :aria-labelledby="`${id}-title`" @submit.prevent="emit('draw', false)">
    <h3 :id="`${id}-title`" class="fa-sampling__heading">{{ t('selection') }}</h3>
    <div class="fa-sampling__draw-fields">
      <label class="fa-sampling__field">
        <span class="fa-sampling__label">{{ t('sampleSize') }}</span>
        <input v-model="sampleSize" class="fa-sampling__input" inputmode="numeric" data-testid="sampling-sample-size" />
      </label>
      <label v-if="profile.kind === 'mus'" class="fa-sampling__field">
        <span class="fa-sampling__label">{{ t('variant') }}</span>
        <select v-model="variant" class="fa-sampling__select" data-testid="sampling-variant">
          <option v-for="option in variants" :key="option.id" :value="option.id" :title="option.description">{{ option.label }}</option>
        </select>
      </label>
      <label v-if="stratified" class="fa-sampling__field">
        <span class="fa-sampling__label">{{ t('allocation') }}</span>
        <select class="fa-sampling__select" data-testid="sampling-allocation" :value="allocation ?? ''" @change="onAllocation">
          <option value="">{{ t('choose') }}</option>
          <option v-for="option in allocations" :key="option.id" :value="option.id">{{ option.label }} ({{ option.formula }})</option>
        </select>
      </label>
      <label class="fa-sampling__field">
        <span class="fa-sampling__label">{{ t('seed') }}</span>
        <input v-model="seed" class="fa-sampling__input fa-sampling__input--mono" inputmode="numeric" data-testid="sampling-seed" :aria-describedby="`${id}-seed-hint`" />
        <span :id="`${id}-seed-hint`" class="fa-sampling__hint">{{ t('seedHint') }}</span>
      </label>
    </div>
    <p v-if="error" class="fa-sampling__error" role="alert">{{ t(errorKey(error)) }}</p>
    <div class="fa-sampling__actions">
      <FaButton variant="primary" type="submit" :loading="busy" data-testid="sampling-draw">{{ t('draw') }}</FaButton>
      <FaButton v-if="canRedraw" variant="secondary" :disabled="busy" data-testid="sampling-redraw" @click="emit('draw', true)">{{ t('redraw') }}</FaButton>
    </div>
  </form>
</template>

// packages-js/ui-react/src/sampling/SamplingDraw.tsx
import type { FormEvent } from 'react'
import {
  selectionErrorKey,
  type AllocationMethod,
  type MethodProfile,
  type NamedOption,
  type SamplingTranslate,
  type SelectionError,
  type SelectionVariant,
} from '@auditcore/ui-core'
import { Button } from '../base/Button'
import { useElementId } from '../store'

export interface SamplingDrawProps {
  profile: MethodProfile
  variants: readonly NamedOption<SelectionVariant>[]
  allocations: readonly NamedOption<AllocationMethod>[]
  stratified: boolean
  error: SelectionError | null
  busy?: boolean
  canRedraw?: boolean
  sampleSize: string
  seed: string
  variant: SelectionVariant | null
  allocation: AllocationMethod | null
  t: SamplingTranslate
  onSampleSizeChange: (value: string) => void
  onSeedChange: (value: string) => void
  onVariantChange: (value: SelectionVariant | null) => void
  onAllocationChange: (value: AllocationMethod | null) => void
  onDraw: (fresh: boolean) => void
}

function Choices(props: SamplingDrawProps) {
  const { t } = props
  return (
    <>
      {props.profile.kind === 'mus' ? (
        <label className="fa-sampling__field">
          <span className="fa-sampling__label">{t('variant')}</span>
          <select className="fa-sampling__select" data-testid="sampling-variant" value={props.variant ?? ''} onChange={(event) => props.onVariantChange(event.target.value as SelectionVariant)}>
            {props.variants.map((option) => <option key={option.id} value={option.id} title={option.description}>{option.label}</option>)}
          </select>
        </label>
      ) : null}
      {props.stratified ? (
        <label className="fa-sampling__field">
          <span className="fa-sampling__label">{t('allocation')}</span>
          <select className="fa-sampling__select" data-testid="sampling-allocation" value={props.allocation ?? ''} onChange={(event) => props.onAllocationChange(event.target.value === '' ? null : (event.target.value as AllocationMethod))}>
            <option value="">{t('choose')}</option>
            {props.allocations.map((option) => <option key={option.id} value={option.id}>{`${option.label} (${option.formula})`}</option>)}
          </select>
        </label>
      ) : null}
    </>
  )
}

/** Auswahl mit Umfang, Variante, Aufteilung und Seed (wie `SamplingDraw.vue`). */
export function SamplingDraw(props: SamplingDrawProps) {
  const { t } = props
  const id = useElementId('fa-sampling-draw')
  const submit = (event: FormEvent): void => {
    event.preventDefault()
    props.onDraw(false)
  }
  return (
    <form className="fa-sampling__form" noValidate aria-labelledby={`${id}-title`} onSubmit={submit}>
      <h3 id={`${id}-title`} className="fa-sampling__heading">{t('selection')}</h3>
      <div className="fa-sampling__draw-fields">
        <label className="fa-sampling__field">
          <span className="fa-sampling__label">{t('sampleSize')}</span>
          <input className="fa-sampling__input" inputMode="numeric" data-testid="sampling-sample-size" value={props.sampleSize} onChange={(event) => props.onSampleSizeChange(event.target.value)} />
        </label>
        <Choices {...props} />
        <label className="fa-sampling__field">
          <span className="fa-sampling__label">{t('seed')}</span>
          <input className="fa-sampling__input fa-sampling__input--mono" inputMode="numeric" data-testid="sampling-seed" aria-describedby={`${id}-seed-hint`} value={props.seed} onChange={(event) => props.onSeedChange(event.target.value)} />
          <span id={`${id}-seed-hint`} className="fa-sampling__hint">{t('seedHint')}</span>
        </label>
      </div>
      {props.error ? <p className="fa-sampling__error" role="alert">{t(selectionErrorKey(props.error))}</p> : null}
      <div className="fa-sampling__actions">
        <Button variant="primary" type="submit" loading={props.busy} testId="sampling-draw">{t('draw')}</Button>
        {props.canRedraw ? <Button variant="secondary" disabled={props.busy} testId="sampling-redraw" onClick={() => props.onDraw(true)}>{t('redraw')}</Button> : null}
      </div>
    </form>
  )
}
