// packages-js/ui/src/sampling/SamplingResult.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useId } from '../composables/useId'
import { derivationColumns, derivationRows, samplingMessages, sizeTexts, type SizeResult } from '@auditcore/ui-core'
import { useI18n, type Locale } from '../i18n'
import FaTable from '../table/FaTable.vue'

const props = withDefaults(defineProps<{ result: SizeResult; locale?: Locale }>(), { locale: undefined })
const { t, locale: active } = useI18n(samplingMessages, () => props.locale)
const id = useId('fa-sampling-result')
const columns = computed(() => derivationColumns(t, active.value))
const rows = computed(() => derivationRows(props.result))
const texts = computed(() => sizeTexts(props.result, t, active.value))
</script>

<template>
  <section class="fa-sampling__card fa-sampling__card--result" :aria-labelledby="`${id}-title`" aria-live="polite">
    <h3 :id="`${id}-title`" class="fa-sampling__heading">{{ t('result') }}</h3>
    <p class="fa-sampling__size" data-testid="sampling-size">{{ texts.size }}</p>
    <p v-if="result.kind === 'mus'" class="fa-sampling__muted">{{ texts.interval }}</p>
    <ul v-if="result.warnings.length" class="fa-sampling__warnings">
      <li v-for="warning in result.warnings" :key="warning">{{ warning }}</li>
    </ul>
    <FaTable v-if="rows.length" :columns="columns" :rows="rows" :caption="t('derivation')" :locale="locale" />
  </section>
</template>

// packages-js/ui-react/src/sampling/SamplingResult.tsx
import { derivationColumns, derivationRows, sizeTexts, type Locale, type SamplingTranslate, type SizeResult } from '@auditcore/ui-core'
import { FlowauditTable } from '../table/FlowauditTable'
import { useElementId } from '../store'

export interface SamplingResultProps {
  result: SizeResult
  t: SamplingTranslate
  locale: Locale
  /** Sprache der Tabelle wie in Vue (Prop der Hauptkomponente). */
  tableLocale?: Locale
}

/** Stichprobenumfang mit Intervall, Warnungen und Herleitung (wie `SamplingResult.vue`). */
export function SamplingResult({ result, t, locale, tableLocale }: SamplingResultProps) {
  const id = useElementId('fa-sampling-result')
  const texts = sizeTexts(result, t, locale)
  const rows = derivationRows(result)
  return (
    <section className="fa-sampling__card fa-sampling__card--result" aria-labelledby={`${id}-title`} aria-live="polite">
      <h3 id={`${id}-title`} className="fa-sampling__heading">{t('result')}</h3>
      <p className="fa-sampling__size" data-testid="sampling-size">{texts.size}</p>
      {result.kind === 'mus' ? <p className="fa-sampling__muted">{texts.interval}</p> : null}
      {result.warnings.length ? (
        <ul className="fa-sampling__warnings">
          {result.warnings.map((warning) => <li key={warning}>{warning}</li>)}
        </ul>
      ) : null}
      {rows.length ? <FlowauditTable columns={derivationColumns(t, locale)} rows={rows} caption={t('derivation')} locale={tableLocale} /> : null}
    </section>
  )
}
