// packages-js/ui-react/src/risk/RiskProfileInfo.tsx
import type { ReactNode } from 'react'
import type { TableColumn, TableRow } from '@flowaudit/common'
import {
  formatValue,
  pairs,
  parameterLabel,
  profileHintText,
  profileStatusText,
  requirementKey,
  riskMessages,
  whenMissingKey,
  type FieldEntry,
  type Locale,
  type ProfileDetail,
  type RiskTranslate,
  type RuleView,
} from '@flowaudit/ui-core'
import { Badge } from '../base/Badge'
import { useTranslation } from '../i18n'
import { FlowauditTable } from '../table/FlowauditTable'
import { displayValue } from './display'

export interface RiskProfileInfoProps {
  profile?: ProfileDetail | null
  locale?: Locale
}

function ruleColumns(t: RiskTranslate): TableColumn[] {
  return [
    { key: 'code', label: t('colCode') },
    { key: 'label', label: t('colLabel') },
    { key: 'inputs', label: t('inputs') },
    { key: 'parameters', label: t('parameters') },
    { key: 'when_missing_columns', label: t('colWhenMissing'), format: (value) => t(whenMissingKey(String(value))) },
  ]
}

function fieldColumns(t: RiskTranslate): TableColumn[] {
  return [
    { key: 'name', label: t('field'), sortable: true },
    { key: 'meaning', label: t('colMeaning') },
    { key: 'requirement', label: t('colRequirement'), sortable: true },
    { key: 'uses', label: t('colMissing') },
  ]
}

function ruleCell(column: TableColumn, row: TableRow, t: RiskTranslate, active: Locale): ReactNode {
  const rule = row as unknown as RuleView
  if (column.key === 'code') return <code>{rule.code}</code>
  if (column.key === 'inputs') return <span>{rule.inputs.map((name) => <code key={name} className="fa-risk-profile__chip">{name}</code>)}</span>
  if (column.key !== 'parameters') return undefined
  return (
    <span>
      {pairs(rule.parameters).map(([name, value]) => (
        <span key={name} className="fa-risk-profile__param">{parameterLabel(name, active)}: {formatValue(value, active, t('emptyValue'))}</span>
      ))}
    </span>
  )
}

function fieldCell(column: TableColumn, row: TableRow, t: RiskTranslate): ReactNode {
  const field = row as unknown as FieldEntry
  if (column.key === 'name') return <code>{field.name}</code>
  if (column.key === 'meaning') return field.meaning ?? t('undocumented')
  if (column.key === 'requirement') return <Badge tone={field.requirement === 'optional' ? 'neutral' : 'accent'}>{t(requirementKey(field.requirement))}</Badge>
  if (column.key !== 'uses') return undefined
  return (
    <span>
      {field.uses.map((use) => (
        <span key={use.code} className="fa-risk-profile__use"><code>{use.code}</code> ({use.role}): {use.absent} / {use.empty}</span>
      ))}
    </span>
  )
}

function Identity({ profile, t, status, hint }: { profile: ProfileDetail; t: RiskTranslate; status: string; hint: string }) {
  const source = profile.source
  return (
    <dl className="fa-risk-profile__identity">
      <dt>{t('profile')}</dt><dd><code>{profile.id}</code></dd>
      <dt>{t('version')}</dt><dd><code>{profile.version}</code></dd>
      <dt>{t('status')}</dt><dd><Badge tone={hint ? 'warning' : 'success'}>{status}</Badge></dd>
      <dt>{t('fingerprint')}</dt><dd><code className="fa-risk-profile__hash">{profile.fingerprint}</code></dd>
      {source.repository ? <dt>{t('source')}</dt> : null}
      {source.repository ? <dd>{displayValue(source.repository)} · {displayValue(source.path)} · {displayValue(source.commit)}</dd> : null}
    </dl>
  )
}

/** Profil, Regeln und Eingabefelder (Pflicht/optional, Folge bei Fehlen), wie `RiskProfileInfo`. */
export function RiskProfileInfo({ profile = null, locale }: RiskProfileInfoProps) {
  const { t, locale: active } = useTranslation(riskMessages, locale)
  if (!profile) return null
  const hint = profileHintText(profile, t)
  return (
    <section className="fa-risk-profile" aria-label={t('profileInfo')}>
      <Identity profile={profile} t={t} status={profileStatusText(profile, t)} hint={hint} />
      {hint ? <p className="fa-risk-profile__hint" role="note">{hint}</p> : null}
      <p className="fa-risk-profile__legal">{profile.legal_status}</p>
      {profile.open_decisions.length ? (
        <div>
          <h4>{t('openDecisions')}</h4>
          <ul>{profile.open_decisions.map((decision) => <li key={decision}>{decision}</li>)}</ul>
        </div>
      ) : null}
      <FlowauditTable columns={ruleColumns(t)} rows={profile.rules.map((rule) => ({ ...rule, id: rule.code }))} rowKey="code" caption={t('rulesTitle')} locale={locale} renderCell={(column, row) => ruleCell(column, row, t, active)} />
      <FlowauditTable columns={fieldColumns(t)} rows={profile.fields.map((field) => ({ ...field, id: field.name }))} rowKey="name" caption={t('fieldsTitle')} locale={locale} renderCell={(column, row) => fieldCell(column, row, t)} />
    </section>
  )
}

// packages-js/ui/src/risk/RiskProfileInfo.vue
<script setup lang="ts">
import { computed } from 'vue'
import FaBadge from '../base/FaBadge.vue'
import { useI18n, type Locale } from '../i18n'
import FaTable from '../table/FaTable.vue'
import type { TableColumn, TableRow } from '../table'
import { riskMessages, type FieldEntry, type ProfileDetail, type RuleView, formatValue, parameterLabel, requirementKey, profileHintText, profileStatusText, whenMissingKey, pairs } from '@flowaudit/ui-core'

const props = withDefaults(defineProps<{ profile?: ProfileDetail | null; locale?: Locale }>(), { profile: null, locale: undefined })
const { t, locale: active } = useI18n(riskMessages, () => props.locale)

const status = computed(() => profileStatusText(props.profile, t))
const hint = computed(() => profileHintText(props.profile, t))
const ruleColumns = computed<TableColumn[]>(() => [
  { key: 'code', label: t('colCode') },
  { key: 'label', label: t('colLabel') },
  { key: 'inputs', label: t('inputs') },
  { key: 'parameters', label: t('parameters') },
  { key: 'when_missing_columns', label: t('colWhenMissing'), format: (value) => t(whenMissingKey(String(value))) },
])
const fieldColumns = computed<TableColumn[]>(() => [
  { key: 'name', label: t('field'), sortable: true },
  { key: 'meaning', label: t('colMeaning') },
  { key: 'requirement', label: t('colRequirement'), sortable: true },
  { key: 'uses', label: t('colMissing') },
])
const ruleRows = computed<TableRow[]>(() => (props.profile?.rules ?? []).map((rule) => ({ ...rule, id: rule.code })))
const fieldRows = computed<TableRow[]>(() => (props.profile?.fields ?? []).map((field) => ({ ...field, id: field.name })))

const asRule = (row: TableRow): RuleView => row as unknown as RuleView
const asField = (row: TableRow): FieldEntry => row as unknown as FieldEntry
</script>

<template>
  <section v-if="profile" class="fa-risk-profile" :aria-label="t('profileInfo')">
    <dl class="fa-risk-profile__identity">
      <dt>{{ t('profile') }}</dt><dd><code>{{ profile.id }}</code></dd>
      <dt>{{ t('version') }}</dt><dd><code>{{ profile.version }}</code></dd>
      <dt>{{ t('status') }}</dt><dd><FaBadge :tone="hint ? 'warning' : 'success'">{{ status }}</FaBadge></dd>
      <dt>{{ t('fingerprint') }}</dt><dd><code class="fa-risk-profile__hash">{{ profile.fingerprint }}</code></dd>
      <dt v-if="profile.source.repository">{{ t('source') }}</dt>
      <dd v-if="profile.source.repository">{{ profile.source.repository }} · {{ profile.source.path }} · {{ profile.source.commit }}</dd>
    </dl>
    <p v-if="hint" class="fa-risk-profile__hint" role="note">{{ hint }}</p>
    <p class="fa-risk-profile__legal">{{ profile.legal_status }}</p>
    <div v-if="profile.open_decisions.length">
      <h4>{{ t('openDecisions') }}</h4>
      <ul><li v-for="decision in profile.open_decisions" :key="decision">{{ decision }}</li></ul>
    </div>
    <FaTable :columns="ruleColumns" :rows="ruleRows" row-key="code" :caption="t('rulesTitle')" :locale="locale">
      <template #cell-code="{ row }"><code>{{ row.code }}</code></template>
      <template #cell-inputs="{ row }">
        <span><code v-for="name in asRule(row).inputs" :key="name" class="fa-risk-profile__chip">{{ name }}</code></span>
      </template>
      <template #cell-parameters="{ row }">
        <span>
          <span v-for="[name, value] in pairs(asRule(row).parameters)" :key="name" class="fa-risk-profile__param">
            {{ parameterLabel(name, active) }}: {{ formatValue(value, active, t('emptyValue')) }}
          </span>
        </span>
      </template>
    </FaTable>
    <FaTable :columns="fieldColumns" :rows="fieldRows" row-key="name" :caption="t('fieldsTitle')" :locale="locale">
      <template #cell-name="{ row }"><code>{{ row.name }}</code></template>
      <template #cell-meaning="{ row }">{{ asField(row).meaning ?? t('undocumented') }}</template>
      <template #cell-requirement="{ row }">
        <FaBadge :tone="asField(row).requirement === 'optional' ? 'neutral' : 'accent'">{{ t(requirementKey(asField(row).requirement)) }}</FaBadge>
      </template>
      <template #cell-uses="{ row }">
        <span>
          <span v-for="use in asField(row).uses" :key="use.code" class="fa-risk-profile__use">
            <code>{{ use.code }}</code> ({{ use.role }}): {{ use.absent }} / {{ use.empty }}
          </span>
        </span>
      </template>
    </FaTable>
  </section>
</template>
