// packages-js/ui-react/src/geo/GeoAreaSelect.tsx
import { displayName } from '@auditcore/ui-core'
import { useGeo } from './context'

export function GeoAreaSelect({ testid }: { testid: string }) {
  const { state, selection, controller, t } = useGeo()
  return (
    <label className="fa-geo__field fa-geo__grow">
      <span className="fa-geo__label">{t('area')}</span>
      <select className="fa-geo__input" data-testid={testid} value={state.areaId ?? ''} onChange={(event) => controller.selectArea(event.target.value || null)}>
        <option value="">{t('choose')}</option>
        {selection.areas.map((area) => (
          <option key={area.id} value={area.id}>{displayName(area)}</option>
        ))}
      </select>
    </label>
  )
}

// packages-js/ui/src/geo/GeoAreaSelect.vue
<script setup lang="ts">
import { useGeoContext } from './context'
import { displayName } from '@auditcore/ui-core'

defineProps<{ testid: string }>()
const { state, t } = useGeoContext()
</script>

<template>
  <label class="fa-geo__field fa-geo__grow">
    <span class="fa-geo__label">{{ t('area') }}</span>
    <select v-model="state.areaId.value" class="fa-geo__input" :data-testid="testid">
      <option :value="null">{{ t('choose') }}</option>
      <option v-for="area in state.areas.value" :key="area.id" :value="area.id">{{ displayName(area) }}</option>
    </select>
  </label>
</template>
