// packages-js/ui-react/src/geo/GeoMapCanvas.tsx
import { useEffect, useRef } from 'react'
import { createLeafletView, displayName, type LatLon, type MapLayers, type MapView, type TileSource } from '@flowaudit/ui-core'
import { Button } from '../base/Button'
import { useGeo } from './context'

export interface GeoMapCanvasProps {
  layers: MapLayers
  tiles: TileSource | null
  center: LatLon
  zoom: number
  onPick: (point: LatLon) => void
}

function useMapView(container: React.RefObject<HTMLDivElement | null>, props: GeoMapCanvasProps) {
  const view = useRef<MapView | null>(null)
  const latest = useRef(props)
  latest.current = props
  useEffect(() => {
    let unmounted = false
    const element = container.current
    if (!element) return undefined
    const { center, zoom, tiles, layers } = latest.current
    void createLeafletView(element, { center, zoom, tiles, onPick: (point) => latest.current.onPick(point), label: displayName }).then((created) => {
      if (unmounted) {
        created.destroy()
        return
      }
      view.current = created
      created.update(latest.current.layers)
      if (layers.points.length + layers.areas.length > 0) created.fit()
    })
    return () => {
      unmounted = true
      view.current?.destroy()
      view.current = null
    }
  }, [container])
  return view
}

/** Leaflet-Karte (erst beim Anzeigen geladen) mit Punkten, Flächen, Bezugspunkt und Umkreis. */
export function GeoMapCanvas(props: GeoMapCanvasProps) {
  const { t } = useGeo()
  const container = useRef<HTMLDivElement | null>(null)
  const view = useMapView(container, props)
  const { layers, tiles } = props
  const count = layers.points.length + layers.areas.length
  useEffect(() => {
    view.current?.update(layers)
  }, [view, layers])
  useEffect(() => {
    view.current?.fit()
  }, [view, count])
  useEffect(() => {
    view.current?.setTiles(tiles)
  }, [view, tiles])
  return (
    <div className="fa-geo__canvas-wrap">
      <div ref={container} className="fa-geo__canvas" role="application" aria-label={t('mapLabel', { points: layers.points.length, areas: layers.areas.length })} data-testid="geo-map" />
      <div className="fa-geo__map-bar">
        {tiles?.url ? (
          <p className="fa-geo__muted" data-testid="geo-attribution">{t('attribution', { text: tiles.attribution })}</p>
        ) : (
          <p className="fa-geo__muted" data-testid="geo-no-tiles">{t('noTiles')}</p>
        )}
        <Button size="sm" icon="expand" testId="geo-fit" onClick={() => view.current?.fit()}>{t('fit')}</Button>
      </div>
    </div>
  )
}

// packages-js/ui/src/geo/GeoMapCanvas.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import FaButton from '../base/FaButton.vue'
import { useGeoContext } from './context'
import { createLeafletView, type MapLayers, type MapView } from '@flowaudit/ui-core'
import { displayName } from '@flowaudit/ui-core'
import type { LatLon, TileSource } from '@flowaudit/ui-core'

const props = defineProps<{ layers: MapLayers; tiles: TileSource | null; center: LatLon; zoom: number }>()
const emit = defineEmits<{ pick: [point: LatLon] }>()
const { t } = useGeoContext()
const container = ref<HTMLElement | null>(null)
let view: MapView | null = null
let unmounted = false

function fit(): void {
  view?.fit()
}

onMounted(async () => {
  if (!container.value) return
  const created = await createLeafletView(container.value, {
    center: props.center,
    zoom: props.zoom,
    tiles: props.tiles,
    onPick: (point) => emit('pick', point),
    label: displayName,
  })
  if (unmounted) {
    created.destroy()
    return
  }
  view = created
  view.update(props.layers)
  if (props.layers.points.length + props.layers.areas.length > 0) fit()
})

watch(() => props.layers, (layers) => view?.update(layers))
watch(() => props.layers.points.length + props.layers.areas.length, fit)
watch(() => props.tiles, (tiles) => view?.setTiles(tiles))

onBeforeUnmount(() => {
  unmounted = true
  view?.destroy()
  view = null
})
</script>

<template>
  <div class="fa-geo__canvas-wrap">
    <div
      ref="container"
      class="fa-geo__canvas"
      role="application"
      :aria-label="t('mapLabel', { points: layers.points.length, areas: layers.areas.length })"
      data-testid="geo-map"
    />
    <div class="fa-geo__map-bar">
      <p v-if="tiles?.url" class="fa-geo__muted" data-testid="geo-attribution">{{ t('attribution', { text: tiles.attribution }) }}</p>
      <p v-else class="fa-geo__muted" data-testid="geo-no-tiles">{{ t('noTiles') }}</p>
      <FaButton size="sm" icon="expand" data-testid="geo-fit" @click="fit">{{ t('fit') }}</FaButton>
    </div>
  </div>
</template>
