// packages-js/ui-react/src/geo/GeoUtmInput.tsx
import type { FormEvent } from 'react'
import { utmErrorKey } from '@auditcore/ui-core'
import { Button } from '../base/Button'
import { useElementId } from '../store'
import { useGeo } from './context'

/** Bezugspunkt aus UTM (Zone, Halbkugel, Ost-/Nordwert) über `POST /utm/geographisch` (wie `GeoUtmInput.vue`). */
export function GeoUtmInput() {
  const { state, selection, controller, t } = useGeo()
  const id = useElementId('fa-geo-utm')
  if (!selection.canFromUtm) return null
  const submit = (event: FormEvent): void => {
    event.preventDefault()
    void controller.applyUtm()
  }
  return (
    <details className="fa-geo__utm" data-testid="geo-utm-input">
      <summary>{t('utmInput')}</summary>
      <p id={`${id}-help`} className="fa-geo__muted">{t('utmInputHelp')}</p>
      <form className="fa-geo__row" noValidate aria-describedby={`${id}-help`} onSubmit={submit}>
        <label className="fa-geo__field">
          <span className="fa-geo__label">{t('utmZone')}</span>
          <input className="fa-geo__input fa-geo__input--short" inputMode="numeric" aria-invalid={state.utmError === 'zone'} data-testid="geo-utm-zone" value={state.zoneText} onChange={(event) => controller.setField('zoneText', event.target.value)} />
        </label>
        <label className="fa-geo__field">
          <span className="fa-geo__label">{t('utmHemisphere')}</span>
          <select value={state.northern ? 'N' : 'S'} className="fa-geo__input" data-testid="geo-utm-hemisphere" onChange={(event) => controller.setField('northern', event.target.value === 'N')}>
            <option value="N">{t('hemisphereNorth')}</option>
            <option value="S">{t('hemisphereSouth')}</option>
          </select>
        </label>
        <label className="fa-geo__field">
          <span className="fa-geo__label">{t('utmEast')}</span>
          <input className="fa-geo__input" inputMode="decimal" aria-invalid={state.utmError === 'east'} data-testid="geo-utm-east" value={state.eastText} onChange={(event) => controller.setField('eastText', event.target.value)} />
        </label>
        <label className="fa-geo__field">
          <span className="fa-geo__label">{t('utmNorth')}</span>
          <input className="fa-geo__input" inputMode="decimal" aria-invalid={state.utmError === 'north'} data-testid="geo-utm-north" value={state.northText} onChange={(event) => controller.setField('northText', event.target.value)} />
        </label>
        <Button type="submit" loading={state.busy === 'utm'} testId="geo-utm-apply">{t('apply')}</Button>
      </form>
      {state.utmError ? <p className="fa-geo__error" role="alert">{t(utmErrorKey(state.utmError))}</p> : null}
    </details>
  )
}

// packages-js/ui/src/geo/GeoUtmInput.vue
<script setup lang="ts">
import FaButton from '../base/FaButton.vue'
import { useId } from '../composables/useId'
import { utmErrorKey } from '@auditcore/ui-core'
import { useGeoContext } from './context'

const { state, t } = useGeoContext()
const id = useId('fa-geo-utm')
const selected = (event: Event): string => (event.target as HTMLSelectElement).value
</script>

<template>
  <details v-if="state.canFromUtm.value" class="fa-geo__utm" data-testid="geo-utm-input">
    <summary>{{ t('utmInput') }}</summary>
    <p :id="`${id}-help`" class="fa-geo__muted">{{ t('utmInputHelp') }}</p>
    <form class="fa-geo__row" novalidate :aria-describedby="`${id}-help`" @submit.prevent="state.applyUtm">
      <label class="fa-geo__field">
        <span class="fa-geo__label">{{ t('utmZone') }}</span>
        <input v-model="state.zoneText.value" class="fa-geo__input fa-geo__input--short" inputmode="numeric" :aria-invalid="state.utmError.value === 'zone'" data-testid="geo-utm-zone" />
      </label>
      <label class="fa-geo__field">
        <span class="fa-geo__label">{{ t('utmHemisphere') }}</span>
        <select :value="state.northern.value ? 'N' : 'S'" class="fa-geo__input" data-testid="geo-utm-hemisphere" @change="state.northern.value = selected($event) === 'N'">
          <option value="N">{{ t('hemisphereNorth') }}</option>
          <option value="S">{{ t('hemisphereSouth') }}</option>
        </select>
      </label>
      <label class="fa-geo__field">
        <span class="fa-geo__label">{{ t('utmEast') }}</span>
        <input v-model="state.eastText.value" class="fa-geo__input" inputmode="decimal" :aria-invalid="state.utmError.value === 'east'" data-testid="geo-utm-east" />
      </label>
      <label class="fa-geo__field">
        <span class="fa-geo__label">{{ t('utmNorth') }}</span>
        <input v-model="state.northText.value" class="fa-geo__input" inputmode="decimal" :aria-invalid="state.utmError.value === 'north'" data-testid="geo-utm-north" />
      </label>
      <FaButton type="submit" :loading="state.busy.value === 'utm'" data-testid="geo-utm-apply">{{ t('apply') }}</FaButton>
    </form>
    <p v-if="state.utmError.value" class="fa-geo__error" role="alert">{{ t(utmErrorKey(state.utmError.value)) }}</p>
  </details>
</template>
