// packages-js/bpmn-react/src/base/PromptDialog.tsx
/** Small dialog asking for one name (replaces `window.prompt`). */

import { useEffect, useState } from 'react'
import { useI18n } from '../i18n'
import { BaseDialog } from './BaseDialog'

export interface PromptDialogProps {
  open: boolean
  title: string
  label: string
  value?: string
  onOpenChange: (open: boolean) => void
  onConfirm: (value: string) => void
}

export function PromptDialog({ open, title, label, value, onOpenChange, onConfirm }: PromptDialogProps) {
  const { t } = useI18n()
  const [text, setText] = useState(value ?? '')

  useEffect(() => {
    if (open) setText(value ?? '')
  }, [open, value])

  const confirm = () => {
    if (!text.trim()) return
    onConfirm(text.trim())
    onOpenChange(false)
  }

  const footer = (
    <>
      <button type="button" className="fa-btn" onClick={() => onOpenChange(false)}>{t('common.cancel')}</button>
      <button type="button" className="fa-btn fa-btn--primary" disabled={!text.trim()} onClick={confirm}>{t('common.apply')}</button>
    </>
  )

  return (
    <BaseDialog open={open} title={title} width="420px" onOpenChange={onOpenChange} footer={footer}>
      <label className="fa-field">
        <span className="fa-label">{label}</span>
        <input className="fa-input" value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && (event.preventDefault(), confirm())} />
      </label>
    </BaseDialog>
  )
}

// packages-js/bpmn-vue/src/components/base/PromptDialog.vue
<script setup lang="ts">
/** Small dialog asking for one name (replaces `window.prompt`). */
import { ref, watch } from 'vue'
import BaseDialog from './BaseDialog.vue'
import { useI18n } from '../../i18n/useI18n'

const props = defineProps<{ open: boolean; title: string; label: string; value?: string }>()
const emit = defineEmits<{ (e: 'update:open', value: boolean): void; (e: 'confirm', value: string): void }>()
const { t } = useI18n()
const text = ref(props.value ?? '')

watch(
  () => props.open,
  (open) => {
    if (open) text.value = props.value ?? ''
  },
)

function confirm(): void {
  if (!text.value.trim()) return
  emit('confirm', text.value.trim())
  emit('update:open', false)
}
</script>

<template>
  <BaseDialog :open="open" :title="title" width="420px" @update:open="emit('update:open', $event)">
    <label class="fa-field">
      <span class="fa-label">{{ label }}</span>
      <input v-model="text" class="fa-input" @keydown.enter.prevent="confirm" />
    </label>
    <template #footer>
      <button type="button" class="fa-btn" @click="emit('update:open', false)">{{ t('common.cancel') }}</button>
      <button type="button" class="fa-btn fa-btn--primary" :disabled="!text.trim()" @click="confirm">{{ t('common.apply') }}</button>
    </template>
  </BaseDialog>
</template>
