// packages-js/bpmn-react/src/base/ToolbarMenu.tsx
/**
 * Button with a popover menu: opens on click, closes on Escape, on click
 * outside and after choosing an item (`children` receives `close`).
 */

import { useEffect, useRef, useState, type KeyboardEvent, type ReactNode } from 'react'
import { classes } from '../hooks'
import { FaIcon } from './FaIcon'

export interface ToolbarMenuProps {
  label: string
  icon: string
  showLabel?: boolean
  align?: 'left' | 'right'
  children: (close: () => void) => ReactNode
}

export function ToolbarMenu({ label, icon, showLabel, align, children }: ToolbarMenuProps) {
  const [open, setOpen] = useState(false)
  const root = useRef<HTMLDivElement | null>(null)
  const close = () => setOpen(false)

  useEffect(() => {
    const onDocument = (event: MouseEvent) => {
      if (root.current && !root.current.contains(event.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDocument)
    return () => document.removeEventListener('mousedown', onDocument)
  }, [])

  const onKey = (event: KeyboardEvent) => {
    if (event.key !== 'Escape' || !open) return
    close()
    root.current?.querySelector<HTMLElement>('button')?.focus()
  }

  return (
    <div ref={root} className="fa-toolbar-menu" onKeyDown={onKey}>
      <button type="button" className={showLabel ? 'fa-btn fa-btn--ghost' : 'fa-icon-btn'} aria-label={label} title={label} aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen(!open)}>
        <FaIcon name={icon} />
        {showLabel ? <span>{label}</span> : null}
        {showLabel ? <FaIcon name="chevron-down" size={14} /> : null}
      </button>
      {open ? (
        <div className={classes('fa-menu', align === 'right' && 'fa-menu--right')} role="menu">
          {children(close)}
        </div>
      ) : null}
    </div>
  )
}

// packages-js/bpmn-vue/src/components/base/ToolbarMenu.vue
<script setup lang="ts">
/**
 * Button with a popover menu: opens on click, closes on Escape, on click
 * outside and after choosing an item (`close` slot prop).
 */
import { onBeforeUnmount, onMounted, ref } from 'vue'
import FaIcon from './FaIcon.vue'

defineProps<{ label: string; icon: string; showLabel?: boolean; align?: 'left' | 'right' }>()
const open = ref(false)
const root = ref<HTMLElement | null>(null)

function close(): void {
  open.value = false
}

function onDocument(event: MouseEvent): void {
  if (open.value && root.value && !root.value.contains(event.target as Node)) close()
}

function onKey(event: KeyboardEvent): void {
  if (event.key === 'Escape' && open.value) {
    close()
    root.value?.querySelector<HTMLElement>('button')?.focus()
  }
}

onMounted(() => document.addEventListener('mousedown', onDocument))
onBeforeUnmount(() => document.removeEventListener('mousedown', onDocument))
</script>

<template>
  <div ref="root" class="fa-toolbar-menu" @keydown="onKey">
    <button
      type="button"
      :class="showLabel ? 'fa-btn fa-btn--ghost' : 'fa-icon-btn'"
      :aria-label="label"
      :title="label"
      aria-haspopup="menu"
      :aria-expanded="open"
      @click="open = !open"
    >
      <FaIcon :name="icon" />
      <span v-if="showLabel">{{ label }}</span>
      <FaIcon v-if="showLabel" name="chevron-down" :size="14" />
    </button>
    <div v-if="open" class="fa-menu" :class="{ 'fa-menu--right': align === 'right' }" role="menu">
      <slot :close="close" />
    </div>
  </div>
</template>
