// packages-js/bpmn-vue/src/components/FlowauditWorkbench.vue
<script setup lang="ts">
/**
 * Workbench: diagram collection (folder tree, info column, group overview)
 * plus editor – the successor of the audit_designer view `BpmnEditor.vue`.
 * Persistence goes through the storage port.
 */
import { computed, onMounted, reactive, ref, toRaw, watch } from 'vue'
import type { Comment, ProfileData, ProfileSummary, RoleAlias, StoragePort, ValidationPort } from '@auditcore/bpmn-flowaudit'
import type { EditorPorts } from '../stores/context'
import { createI18n, provideI18n, type Locale } from '../i18n/useI18n'
import { createCollectionStore } from '../stores/collectionStore'
import { COLLECTION_PANEL, createSvgThumbnailRenderer, createThumbnails, readPanel, writePanel, type EditorFactory, type FolderAction, type HostAction } from '@auditcore/bpmn-flowaudit/ui'
import { defaultEditorFactory } from '../editor/defaultFactory'
import PanelResizer from './base/PanelResizer.vue'
import CollectionTree from './collection/CollectionTree.vue'
import DiagramInfoColumn from './collection/DiagramInfoColumn.vue'
import GroupOverview from './collection/GroupOverview.vue'
import FlowauditEditor from './FlowauditEditor.vue'
import '@auditcore/bpmn-flowaudit/ui.css'

const props = withDefaults(
  defineProps<{
    storage: StoragePort
    profile?: ProfileData | null
    profiles?: ProfileSummary[]
    ports?: EditorPorts & { validation?: ValidationPort }
    locale?: Locale
    author?: string
    roleAliases?: RoleAlias[]
    editorFactory?: EditorFactory
    hostActions?: HostAction[]
    folderActions?: FolderAction[]
  }>(),
  { profile: null, editorFactory: undefined, profiles: () => [], ports: () => ({}), locale: 'de', author: '', roleAliases: () => [], hostActions: () => [], folderActions: () => [] },
)
const emit = defineEmits<{
  (e: 'open', id: string): void
  (e: 'error', message: string): void
  (e: 'host-action', id: string, diagramId: string): void
  (e: 'folder-action', id: string, folderId: string, diagramIds: string[]): void
}>()
const { t } = provideI18n(createI18n(props.locale))
// Ports are plain objects; a reactive proxy (e.g. from `reactive()`) would break cloning in the ports.
const storage = toRaw(props.storage)
const thumbnails = createThumbnails({ storage, render: createSvgThumbnailRenderer(props.editorFactory ?? defaultEditorFactory, props.locale) })
const store = createCollectionStore(storage, { onDiagramSaved: thumbnails.invalidate })
// Width and visibility of the collection column are kept per browser.
const sidePanel = reactive(readPanel('collection', COLLECTION_PANEL))
watch(sidePanel, (state) => writePanel('collection', state))

const selected = ref<string | null>(null)
const openId = ref<string | null>(null)
const xml = ref('')
const comments = ref<Comment[]>([])
const saving = ref(false)
const dirty = ref(false)

const selectedEntry = computed(() => (selected.value ? store.entry(selected.value) : undefined))
const openEntry = computed(() => (openId.value ? store.entry(openId.value) : undefined))
const compareSources = computed(() =>
  [...store.collection.value.diagrams.values()].filter((entry) => entry.id !== openId.value).map((entry) => ({ id: entry.id, name: entry.name, load: () => storage.loadDiagram(entry.id) })),
)
const folderTitle = computed(() => (store.selectedFolder.value ? store.collection.value.folders.get(store.selectedFolder.value)?.name ?? '' : t('collection.topLevel')))

async function open(id: string): Promise<void> {
  if (dirty.value && !window.confirm(t('workbench.discard'))) return
  xml.value = await storage.loadDiagram(id)
  comments.value = (await storage.loadComments?.(id)) ?? []
  openId.value = id
  selected.value = id
  dirty.value = false
  emit('open', id)
}

async function save(payload: { xml: string }): Promise<void> {
  if (!openId.value) return
  saving.value = true
  await store.saveDiagram(openId.value, payload.xml)
  await storage.saveComments?.(openId.value, comments.value)
  saving.value = false
  dirty.value = false
}

async function approve(payload: { xml: string; info: { version?: string; approvedBy?: string; approvedOn?: string; systemCutoffDate?: string } }): Promise<void> {
  if (!openId.value) return
  await save(payload)
  await store.approveDiagram(openId.value, payload.xml, payload.info.version ?? '1', { approvedBy: payload.info.approvedBy, approvedOn: payload.info.approvedOn, cutoffDate: payload.info.systemCutoffDate })
}

async function createAndOpen(): Promise<void> {
  const id = await store.createDiagram(t('collection.newDiagram'), store.selectedFolder.value)
  if (id) await open(id)
}

function onDeleted(): void {
  if (openId.value === selected.value) openId.value = null
  selected.value = null
}

function onXml(value: string): void {
  if (value !== xml.value) dirty.value = true
  xml.value = value
}

watch(store.error, (message) => message && emit('error', message))
onMounted(() => store.load())
</script>

<template>
  <div class="fa-root fa-workbench" :lang="locale">
    <aside v-if="sidePanel.open" class="fa-workbench__side" :style="{ width: `${sidePanel.width}px` }">
      <CollectionTree :store="store" :selected-diagram="selected" :open-diagram="openId" @select-diagram="selected = $event" @open-diagram="open" />
    </aside>
    <PanelResizer v-model:width="sidePanel.width" v-model:open="sidePanel.open" :bounds="COLLECTION_PANEL" edge="left" :name="t('panel.collection')" />
    <main class="fa-workbench__main">
      <FlowauditEditor
        v-if="openEntry"
        :key="openEntry.id"
        :xml="xml"
        :name="openEntry.name"
        :diagram-id="openEntry.id"
        :profile="profile"
        :profiles="profiles"
        :ports="ports"
        :locale="locale"
        :comments="comments"
        :approvals="openEntry.approvals"
        :author="author"
        :compare-sources="compareSources"
        :role-aliases="roleAliases"
        :saving="saving"
        :editor-factory="editorFactory"
        :host-actions="hostActions"
        @host-action="openEntry && emit('host-action', $event, openEntry.id)"
        @update:xml="onXml"
        @update:name="store.renameDiagram(openEntry.id, $event)"
        @update:comments="comments = $event"
        @save="save"
        @approve="approve"
        @new="createAndOpen"
      />
      <div v-else class="fa-workbench__overview">
        <GroupOverview
          :overview="store.overview.value"
          :profile="profile"
          :issues="store.issues.value"
          :title="folderTitle"
          :cards="store.cards.value"
          :top-level="!store.selectedFolder.value"
          :folder-actions="folderActions"
          :thumbnails="thumbnails"
          @open="open"
          @folder-action="(id, folderId, diagramIds) => emit('folder-action', id, folderId, diagramIds)"
          @describe-folder="store.describeFolder"
          @rename-folder="store.renameFolder"
          @describe-diagram="store.describeDiagram"
        />
        <DiagramInfoColumn v-if="selectedEntry" class="fa-workbench__info" :store="store" :entry="selectedEntry" @open="open" @deleted="onDeleted" />
      </div>
    </main>
  </div>
</template>

// packages-js/bpmn-react/src/FlowauditWorkbench.tsx
/**
 * Workbench: diagram collection (folder tree, info column, group overview)
 * plus editor – React counterpart of the Vue `FlowauditWorkbench`.
 * Persistence goes through the storage port.
 */

import { useEffect, useMemo, useRef, useState } from 'react'
import type { Comment, DiagramInfo, ProfileData, ProfileSummary, RoleAlias, StoragePort, ValidationPort } from '@auditcore/bpmn-flowaudit'
import { COLLECTION_PANEL, createSvgThumbnailRenderer, createThumbnails, readPanel, writePanel, type EditorFactory, type EditorPorts, type FolderAction, type HostAction, type Locale, type PanelState, type Thumbnails } from '@auditcore/bpmn-flowaudit/ui'
import { PanelResizer } from './base/PanelResizer'
import { defaultEditorFactory } from './editorFactory'
import { CollectionTree } from './collection/CollectionTree'
import { DiagramInfoColumn } from './collection/DiagramInfoColumn'
import { GroupOverview } from './collection/GroupOverview'
import { FlowauditEditor } from './FlowauditEditor'
import { classes } from './hooks'
import { I18nProvider, useI18n } from './i18n'
import { useCollection, type CollectionBinding } from './useCollection'
import '@auditcore/bpmn-flowaudit/ui.css'

export interface FlowauditWorkbenchProps {
  storage: StoragePort
  profile?: ProfileData | null
  profiles?: ProfileSummary[]
  ports?: EditorPorts & { validation?: ValidationPort }
  locale?: Locale
  author?: string
  roleAliases?: RoleAlias[]
  editorFactory?: EditorFactory
  hostActions?: HostAction[]
  folderActions?: FolderAction[]
  className?: string
  onOpen?: (id: string) => void
  onError?: (message: string) => void
  onHostAction?: (id: string, diagramId: string) => void
  onFolderAction?: (id: string, folderId: string, diagramIds: string[]) => void
}

interface OpenDiagram {
  id: string
  xml: string
  comments: Comment[]
}

/** Open, save and approve diagrams of the collection. */
function useWorkbench(store: CollectionBinding, props: FlowauditWorkbenchProps) {
  const { t } = useI18n()
  const [selected, setSelected] = useState<string | null>(null)
  const [opened, setOpened] = useState<OpenDiagram | null>(null)
  const [saving, setSaving] = useState(false)
  const dirty = useRef(false)

  const open = async (id: string) => {
    if (dirty.current && !window.confirm(t('workbench.discard'))) return
    const xml = await props.storage.loadDiagram(id)
    const comments = (await props.storage.loadComments?.(id)) ?? []
    dirty.current = false
    setOpened({ id, xml, comments })
    setSelected(id)
    props.onOpen?.(id)
  }

  const save = async (payload: { xml: string }) => {
    if (!opened) return
    setSaving(true)
    await store.saveDiagram(opened.id, payload.xml)
    await props.storage.saveComments?.(opened.id, opened.comments)
    setSaving(false)
    dirty.current = false
  }

  const approve = async (payload: { xml: string; info: DiagramInfo }) => {
    if (!opened) return
    await save(payload)
    await store.approveDiagram(opened.id, payload.xml, payload.info.version ?? '1', { approvedBy: payload.info.approvedBy, approvedOn: payload.info.approvedOn, cutoffDate: payload.info.systemCutoffDate })
  }

  const createAndOpen = async () => {
    const id = await store.createDiagram(t('collection.newDiagram'), store.state.selectedFolder)
    if (id) await open(id)
  }

  const onXml = (xml: string) => {
    if (!opened || xml === opened.xml) return
    dirty.current = true
    setOpened({ ...opened, xml })
  }

  const onDeleted = () => {
    if (opened?.id === selected) setOpened(null)
    setSelected(null)
  }

  return { selected, setSelected, opened, setOpened, saving, open, save, approve, createAndOpen, onXml, onDeleted }
}

type Bench = ReturnType<typeof useWorkbench>

function EditorPane({ store, bench, props, opened }: { store: CollectionBinding; bench: Bench; props: FlowauditWorkbenchProps; opened: OpenDiagram }) {
  const entry = store.entry(opened.id)
  const { collection, revision } = store.state
  const { storage } = props
  const compareSources = useMemo(
    () => (void revision, [...collection.diagrams.values()].filter((item) => item.id !== opened.id).map((item) => ({ id: item.id, name: item.name, load: () => storage.loadDiagram(item.id) }))),
    [collection, revision, opened.id, storage],
  )
  if (!entry) return null
  return (
    <FlowauditEditor
      key={entry.id}
      xml={opened.xml}
      name={entry.name}
      diagramId={entry.id}
      profile={props.profile ?? null}
      profiles={props.profiles ?? []}
      ports={props.ports ?? {}}
      locale={props.locale ?? 'de'}
      comments={opened.comments}
      approvals={entry.approvals}
      author={props.author ?? ''}
      compareSources={compareSources}
      roleAliases={props.roleAliases ?? []}
      saving={bench.saving}
      editorFactory={props.editorFactory}
      onXmlChange={bench.onXml}
      onNameChange={(name) => void store.renameDiagram(entry.id, name)}
      onCommentsChange={(comments) => bench.setOpened({ ...opened, comments })}
      onSave={(payload) => void bench.save(payload)}
      onApprove={(payload) => void bench.approve(payload)}
      onNew={() => void bench.createAndOpen()}
      hostActions={props.hostActions}
      onHostAction={(id) => props.onHostAction?.(id, opened.id)}
    />
  )
}

function OverviewPane({ store, bench, props, thumbnails }: { store: CollectionBinding; bench: Bench; props: FlowauditWorkbenchProps; thumbnails: Thumbnails }) {
  const profile = props.profile ?? null
  const { t } = useI18n()
  const { collection, selectedFolder } = store.state
  const selectedEntry = bench.selected ? store.entry(bench.selected) : undefined
  const folderTitle = selectedFolder ? (collection.folders.get(selectedFolder)?.name ?? '') : t('collection.topLevel')
  return (
    <div className="fa-workbench__overview">
      <GroupOverview
        overview={store.overview}
        profile={profile}
        issues={store.issues}
        title={folderTitle}
        cards={store.cards}
        topLevel={!selectedFolder}
        onOpen={(id) => void bench.open(id)}
        onDescribeFolder={(id, text) => void store.describeFolder(id, text)}
        onRenameFolder={(id, name) => void store.renameFolder(id, name)}
        onDescribeDiagram={(id, text) => void store.describeDiagram(id, text)}
        folderActions={props.folderActions}
        onFolderAction={props.onFolderAction}
        thumbnails={thumbnails}
      />
      {selectedEntry ? <DiagramInfoColumn className="fa-workbench__info" store={store} entry={selectedEntry} onOpen={(id) => void bench.open(id)} onDeleted={bench.onDeleted} /> : null}
    </div>
  )
}

/** Reports collection errors to `onError`. */
function useErrorReport(error: string | null, onError?: (message: string) => void): void {
  const latest = useRef(onError)
  useEffect(() => {
    latest.current = onError
  })
  useEffect(() => {
    if (error) latest.current?.(error)
  }, [error])
}

/** Width and visibility of the collection column, kept per browser. */
function useCollectionPanel() {
  const [panel, setPanel] = useState<PanelState>(() => readPanel('collection', COLLECTION_PANEL))
  useEffect(() => writePanel('collection', panel), [panel])
  return { panel, setWidth: (width: number) => setPanel((current) => ({ ...current, width })), setOpen: (open: boolean) => setPanel((current) => ({ ...current, open })) }
}

function Workbench(props: FlowauditWorkbenchProps) {
  const { t } = useI18n()
  const [thumbnails] = useState(() => createThumbnails({ storage: props.storage, render: createSvgThumbnailRenderer(props.editorFactory ?? defaultEditorFactory, props.locale ?? 'de') }))
  const store = useCollection(props.storage, { onDiagramSaved: thumbnails.invalidate })
  const side = useCollectionPanel()
  const bench = useWorkbench(store, props)
  const { opened } = bench
  useErrorReport(store.state.error, props.onError)
  const openEntry = opened ? store.entry(opened.id) : undefined

  return (
    <div className={classes('fa-root fa-workbench', props.className)} lang={props.locale ?? 'de'}>
      {side.panel.open ? (
        <aside className="fa-workbench__side" style={{ width: side.panel.width }}>
          <CollectionTree store={store} selectedDiagram={bench.selected} openDiagram={opened?.id ?? null} onSelectDiagram={bench.setSelected} onOpenDiagram={(id) => void bench.open(id)} />
        </aside>
      ) : null}
      <PanelResizer width={side.panel.width} open={side.panel.open} bounds={COLLECTION_PANEL} edge="left" name={t('panel.collection')} onWidthChange={side.setWidth} onOpenChange={side.setOpen} />
      <main className="fa-workbench__main">
        {opened && openEntry ? <EditorPane store={store} bench={bench} props={props} opened={opened} /> : <OverviewPane store={store} bench={bench} props={props} thumbnails={thumbnails} />}
      </main>
    </div>
  )
}

export function FlowauditWorkbench(props: FlowauditWorkbenchProps) {
  return (
    <I18nProvider locale={props.locale ?? 'de'}>
      <Workbench {...props} />
    </I18nProvider>
  )
}
