// packages-js/bpmn-vue/src/panels/tabs/ListsTab.vue
<script setup lang="ts">
/**
 * Generic tab for FlowAudit lists (controls, risks, evidence, deadlines,
 * findings, audit steps, sources, references) – from the descriptors.
 */
import { computed } from 'vue'
import type { Extensions, ListExtensionKey } from '@auditcore/bpmn-flowaudit'
import { useI18n } from '../../i18n/useI18n'
import { useEditorContext } from '../../stores/context'
import ListEditor from '../ListEditor.vue'
import { isDescribedList, LISTS } from '@auditcore/bpmn-flowaudit/ui'
import { useOptions } from '../useOptions'

const props = defineProps<{ lists: ListExtensionKey[] }>()
const { selection, profile, ports, readonly } = useEditorContext()
const { locale } = useI18n()
const { optionsFor } = useOptions({ profile, catalogue: ports.catalogue, locale })

const descriptors = computed(() => props.lists.filter(isDescribedList).map((key) => LISTS[key]))

function items(key: ListExtensionKey): Record<string, unknown>[] {
  return selection.extensions.value[key] as unknown as Record<string, unknown>[]
}

function update(key: ListExtensionKey, value: Record<string, unknown>[]): void {
  selection.write({ [key]: value } as Partial<Extensions>)
}
</script>

<template>
  <div class="fa-tab-lists">
    <ListEditor
      v-for="descriptor in descriptors"
      :key="descriptor.key"
      :descriptor="descriptor"
      :items="items(descriptor.key)"
      :options-for="optionsFor"
      :disabled="readonly()"
      @update="update(descriptor.key, $event)"
    />
  </div>
</template>

// packages-js/bpmn-react/src/panels/tabs/ListsTab.tsx
/**
 * Generic tab for FlowAudit lists (controls, risks, evidence, deadlines,
 * findings, audit steps, sources, references) – from the descriptors.
 */

import type { Extensions, ListExtensionKey } from '@auditcore/bpmn-flowaudit'
import { isDescribedList, LISTS } from '@auditcore/bpmn-flowaudit/ui'
import { useEditorContext, useSelectionState } from '../../context'
import { ListEditor } from '../ListEditor'
import { useOptions } from '../useOptions'

export function ListsTab({ lists }: { lists: ListExtensionKey[] }) {
  const { selection, readonly } = useEditorContext()
  const { extensions } = useSelectionState()
  const optionsFor = useOptions()
  return (
    <div className="fa-tab-lists">
      {lists.filter(isDescribedList).map((key) => (
        <ListEditor
          key={key}
          descriptor={LISTS[key]}
          items={extensions[key] as unknown as Record<string, unknown>[]}
          optionsFor={optionsFor}
          disabled={readonly()}
          onUpdate={(value) => selection.write({ [key]: value } as Partial<Extensions>)}
        />
      ))}
    </div>
  )
}
