// packages-js/bpmn-vue/src/panels/tabs/NotesTab.vue
<script setup lang="ts">
/**
 * Notes: internal note in the XML (`flowaudit:interneNotiz`) and comments
 * per element (legacy `comments` of the audit_designer, kept by the app).
 */
import { computed, ref } from 'vue'
import type { Comment } from '@auditcore/bpmn-flowaudit'
import { commentsOf, newComment, toggleResolved as toggled } from '@auditcore/bpmn-flowaudit/ui'
import FaIcon from '../../components/base/FaIcon.vue'
import { useI18n } from '../../i18n/useI18n'
import { useEditorContext } from '../../stores/context'

const props = defineProps<{ comments: Comment[]; author: string }>()
const emit = defineEmits<{ (e: 'update:comments', value: Comment[]): void }>()
const { selection, readonly } = useEditorContext()
const { t } = useI18n()
const draft = ref('')

const elementId = computed(() => selection.element.value?.id ?? '')
const own = computed(() => commentsOf(props.comments, elementId.value))

function addComment(): void {
  if (!draft.value.trim() || !elementId.value) return
  emit('update:comments', [...props.comments, newComment(elementId.value, draft.value, props.author)])
  draft.value = ''
}

const toggleResolved = (id: string) => emit('update:comments', toggled(props.comments, id))
</script>

<template>
  <div class="fa-tab-notes">
    <label class="fa-field">
      <span class="fa-label">{{ t('props.internalNote') }}</span>
      <textarea
        class="fa-textarea"
        rows="4"
        :value="selection.extensions.value.internalNote ?? ''"
        :disabled="readonly()"
        @change="selection.write({ internalNote: ($event.target as HTMLTextAreaElement).value })"
      />
      <span class="fa-help">{{ t('props.internalNoteHelp') }}</span>
    </label>
    <section class="fa-section">
      <h3 class="fa-section__title">{{ t('props.comments') }}</h3>
      <ul class="fa-comments">
        <li v-for="comment in own" :key="comment.id" class="fa-card fa-comment" :class="{ 'fa-comment--resolved': comment.resolved }">
          <p>{{ comment.text }}</p>
          <footer>
            <span class="fa-help">{{ comment.author }} · {{ new Date(comment.timestamp).toLocaleString() }}</span>
            <label class="fa-check"><input type="checkbox" :checked="comment.resolved" @change="toggleResolved(comment.id)" />{{ t('props.commentResolved') }}</label>
          </footer>
        </li>
      </ul>
      <div class="fa-comments__new">
        <input v-model="draft" class="fa-input" :placeholder="t('props.commentAdd')" @keydown.enter.prevent="addComment" />
        <button type="button" class="fa-btn" :disabled="!draft.trim()" @click="addComment"><FaIcon name="comment" :size="16" />{{ t('common.add') }}</button>
      </div>
    </section>
  </div>
</template>

// packages-js/bpmn-react/src/panels/tabs/NotesTab.tsx
/**
 * Notes: internal note in the XML (`flowaudit:interneNotiz`) and comments
 * per element (kept by the application).
 */

import { useState } from 'react'
import type { Comment } from '@auditcore/bpmn-flowaudit'
import { commentsOf, newComment, toggleResolved } from '@auditcore/bpmn-flowaudit/ui'
import { FaIcon } from '../../base/FaIcon'
import { useEditorContext, useSelectionState } from '../../context'
import { classes } from '../../hooks'
import { useI18n } from '../../i18n'
import { CommitField } from '../CommitField'

export interface NotesTabProps {
  comments: Comment[]
  author: string
  onCommentsChange: (comments: Comment[]) => void
}

export function NotesTab({ comments, author, onCommentsChange }: NotesTabProps) {
  const { t } = useI18n()
  const { selection, readonly } = useEditorContext()
  const { element, extensions } = useSelectionState()
  const [draft, setDraft] = useState('')
  const elementId = element?.id ?? ''

  const addComment = () => {
    if (!draft.trim() || !elementId) return
    onCommentsChange([...comments, newComment(elementId, draft, author)])
    setDraft('')
  }

  return (
    <div className="fa-tab-notes">
      <label className="fa-field">
        <span className="fa-label">{t('props.internalNote')}</span>
        <CommitField multiline className="fa-textarea" rows={4} value={extensions.internalNote ?? ''} disabled={readonly()} onCommit={(internalNote) => selection.write({ internalNote })} />
        <span className="fa-help">{t('props.internalNoteHelp')}</span>
      </label>
      <section className="fa-section">
        <h3 className="fa-section__title">{t('props.comments')}</h3>
        <ul className="fa-comments">
          {commentsOf(comments, elementId).map((comment) => (
            <li key={comment.id} className={classes('fa-card fa-comment', comment.resolved && 'fa-comment--resolved')}>
              <p>{comment.text}</p>
              <footer>
                <span className="fa-help">
                  {comment.author} · {new Date(comment.timestamp).toLocaleString()}
                </span>
                <label className="fa-check">
                  <input type="checkbox" checked={comment.resolved} onChange={() => onCommentsChange(toggleResolved(comments, comment.id))} />
                  {t('props.commentResolved')}
                </label>
              </footer>
            </li>
          ))}
        </ul>
        <div className="fa-comments__new">
          <input className="fa-input" value={draft} placeholder={t('props.commentAdd')} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && (event.preventDefault(), addComment())} />
          <button type="button" className="fa-btn" disabled={!draft.trim()} onClick={addComment}>
            <FaIcon name="comment" size={16} />
            {t('common.add')}
          </button>
        </div>
      </section>
    </div>
  )
}
