// packages-js/ui-react/src/extrapolation/ExtrapolationStrata.tsx
import { extrapolationCellLabel, extrapolationIssueText, STRATUM_FIELDS, type StratumRow } from '@auditcore/ui-core'
import { Button } from '../base/Button'
import { classes, useElementId } from '../store'
import type { UseExtrapolation } from './useExtrapolation'

function StratumLine({ view, row, index }: { view: UseExtrapolation; row: StratumRow; index: number }) {
  const { state, controller, t } = view
  const part = state.form.design === 'periods' ? 'period' : 'group'
  const partIssue = extrapolationIssueText(state.issues, `strata.${index}.part`, t)
  return (
    <tr>
      {state.form.design !== 'single' ? (
        <td>
          <input className="fa-extrapolation__input" value={row.part} aria-label={extrapolationCellLabel(t, part, index + 1)} aria-invalid={partIssue ? 'true' : undefined} title={partIssue || undefined} onChange={(event) => controller.updateStratum(index, { part: event.target.value })} />
        </td>
      ) : null}
      {STRATUM_FIELDS.map((field) => {
        const issue = extrapolationIssueText(state.issues, `strata.${index}.${field.key}`, t)
        return (
          <td key={field.key}>
            <input
              className={classes('fa-extrapolation__input', field.numeric && 'fa-extrapolation__input--number')}
              inputMode={field.numeric ? 'decimal' : undefined}
              value={row[field.key]}
              aria-label={extrapolationCellLabel(t, field.label, index + 1)}
              aria-invalid={issue ? 'true' : undefined}
              title={issue || undefined}
              onChange={(event) => controller.updateStratum(index, { [field.key]: event.target.value })}
            />
          </td>
        )
      })}
      <td>
        <Button size="sm" variant="ghost" icon="trash" iconOnly label={t('removeRow', { what: t('stratumName'), row: index + 1 })} disabled={state.form.strata.length <= 1} onClick={() => controller.removeStratum(index)} />
      </td>
    </tr>
  )
}

/** Schichten der Grundgesamtheit als bearbeitbare Tabelle (wie `ExtrapolationStrata.vue`). */
export function ExtrapolationStrata({ view }: { view: UseExtrapolation }) {
  const { state, controller, t } = view
  const id = useElementId('fa-extrapolation-strata')
  return (
    <section className="fa-extrapolation__card" aria-labelledby={`${id}-title`}>
      <h3 id={`${id}-title`} className="fa-extrapolation__heading">{t('strata')}</h3>
      <p className="fa-extrapolation__hint">{t('strataHint')}</p>
      <div className="fa-extrapolation__scroll">
        <table className="fa-extrapolation__grid" data-testid="extrapolation-strata">
          <thead>
            <tr>
              {state.form.design !== 'single' ? <th scope="col">{t(state.form.design === 'periods' ? 'period' : 'group')}</th> : null}
              {STRATUM_FIELDS.map((field) => <th key={field.key} scope="col">{t(field.label)}</th>)}
              <th scope="col">{t('remove')}</th>
            </tr>
          </thead>
          <tbody>
            {state.form.strata.map((row, index) => <StratumLine key={row.key} view={view} row={row} index={index} />)}
          </tbody>
        </table>
      </div>
      <div className="fa-extrapolation__actions">
        <Button size="sm" icon="plus" testId="extrapolation-add-stratum" onClick={controller.addStratum}>{t('addStratum')}</Button>
      </div>
    </section>
  )
}

// packages-js/ui/src/extrapolation/ExtrapolationStrata.vue
<script setup lang="ts">
import { computed } from 'vue'
import {
  extrapolationCellLabel,
  extrapolationIssueText,
  extrapolationMessages,
  STRATUM_FIELDS,
  type ExtrapolationController,
  type ExtrapolationData,
} from '@auditcore/ui-core'
import FaButton from '../base/FaButton.vue'
import { useId } from '../composables/useId'
import { useI18n, type Locale } from '../i18n'

const props = withDefaults(defineProps<{ controller: ExtrapolationController; state: ExtrapolationData; locale?: Locale }>(), { locale: undefined })
const { t } = useI18n(extrapolationMessages, () => props.locale)
const id = useId('fa-extrapolation-strata')
const issue = (index: number, key: string): string => extrapolationIssueText(props.state.issues, `strata.${index}.${key}`, t)
const partLabel = computed(() => (props.state.form.design === 'periods' ? 'period' : 'group') as 'period' | 'group')
const value = (event: Event): string => (event.target as HTMLInputElement).value
</script>

<template>
  <section class="fa-extrapolation__card" :aria-labelledby="`${id}-title`">
    <h3 :id="`${id}-title`" class="fa-extrapolation__heading">{{ t('strata') }}</h3>
    <p class="fa-extrapolation__hint">{{ t('strataHint') }}</p>
    <div class="fa-extrapolation__scroll">
      <table class="fa-extrapolation__grid" data-testid="extrapolation-strata">
        <thead>
          <tr>
            <th v-if="state.form.design !== 'single'" scope="col">{{ t(partLabel) }}</th>
            <th v-for="field in STRATUM_FIELDS" :key="field.key" scope="col">{{ t(field.label) }}</th>
            <th scope="col">{{ t('remove') }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(row, index) in state.form.strata" :key="row.key">
            <td v-if="state.form.design !== 'single'">
              <input class="fa-extrapolation__input" :value="row.part" :aria-label="extrapolationCellLabel(t, partLabel, index + 1)" :aria-invalid="issue(index, 'part') ? 'true' : undefined" :title="issue(index, 'part') || undefined" @input="controller.updateStratum(index, { part: value($event) })" />
            </td>
            <td v-for="field in STRATUM_FIELDS" :key="field.key">
              <input
                class="fa-extrapolation__input"
                :class="{ 'fa-extrapolation__input--number': field.numeric }"
                :inputmode="field.numeric ? 'decimal' : undefined"
                :value="row[field.key]"
                :aria-label="extrapolationCellLabel(t, field.label, index + 1)"
                :aria-invalid="issue(index, field.key) ? 'true' : undefined"
                :title="issue(index, field.key) || undefined"
                @input="controller.updateStratum(index, { [field.key]: value($event) })"
              />
            </td>
            <td>
              <FaButton size="sm" variant="ghost" icon="trash" icon-only :label="t('removeRow', { what: t('stratumName'), row: index + 1 })" :disabled="state.form.strata.length <= 1" @click="controller.removeStratum(index)" />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="fa-extrapolation__actions">
      <FaButton size="sm" icon="plus" data-testid="extrapolation-add-stratum" @click="controller.addStratum">{{ t('addStratum') }}</FaButton>
    </div>
  </section>
</template>
