// packages-js/ui-react/src/samplesize/SampleSizeResult.tsx
import { samplesizeAllocation, samplesizeDerivation, samplesizeSummary, type Locale, type SampleSizePlan, type SamplesizeMessageKey, type Translate } from '@auditcore/ui-core'

function Table({ testId, caption, head, rows }: { testId: string; caption: string; head: string[]; rows: string[][] }) {
  return (
    <table className="fa-samplesize__table" data-testid={testId}>
      <caption>{caption}</caption>
      <thead><tr>{head.map((cell) => <th key={cell} scope="col">{cell}</th>)}</tr></thead>
      <tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, column) => <td key={column}>{cell}</td>)}</tr>)}</tbody>
    </table>
  )
}

/** Ergebnis des Planers (wie `SampleSizeResult.vue`). */
export function SampleSizeResult({ plan, t, locale }: { plan: SampleSizePlan; t: Translate<SamplesizeMessageKey>; locale: Locale }) {
  const allocation = samplesizeAllocation(plan, t, locale)
  return (
    <section className="fa-samplesize__result" aria-label={t('result')} data-testid="samplesize-result">
      <h3 className="fa-samplesize__heading">{t('result')} <span className="fa-samplesize__badge">{plan.status_label}</span></h3>
      <dl className="fa-samplesize__summary">
        {samplesizeSummary(plan, t, locale).map((row) => (
          <div key={row.key}>
            <dt>{row.key}</dt>
            <dd>{row.text}</dd>
          </div>
        ))}
      </dl>
      {allocation.length ? <Table testId="samplesize-allocation" caption={t('allocation')} head={[t('stratumName'), t('allocationSize'), t('allocationShare'), t('allocationCutOff'), t('stratumExhaustive')]} rows={allocation} /> : null}
      <Table testId="samplesize-derivation" caption={t('derivation')} head={[t('stepLabel'), t('stepFormula'), t('stepValue'), t('stepSource')]} rows={samplesizeDerivation(plan, locale)} />
      {plan.warnings.length ? (
        <ul className="fa-samplesize__warnings" aria-label={t('warnings')}>
          {plan.warnings.map((warning) => <li key={warning}>{warning}</li>)}
        </ul>
      ) : null}
    </section>
  )
}

// packages-js/ui/src/samplesize/SampleSizeResult.vue
<!-- Ergebnis des Planers: Umfang, Aufteilung, Herleitung mit Fundstellen, Hinweise. -->
<script setup lang="ts">
import { computed } from 'vue'
import { samplesizeAllocation, samplesizeDerivation, samplesizeMessages, samplesizeSummary, type SampleSizePlan } from '@auditcore/ui-core'
import { useI18n, type Locale } from '../i18n'

const props = withDefaults(defineProps<{
  plan: SampleSizePlan
  locale?: Locale
}>(), { locale: undefined })
const { t, locale: active } = useI18n(samplesizeMessages, () => props.locale)
const summary = computed(() => samplesizeSummary(props.plan, t, active.value))
const allocation = computed(() => samplesizeAllocation(props.plan, t, active.value))
const derivation = computed(() => samplesizeDerivation(props.plan, active.value))
const allocationHead = computed(() => [t('stratumName'), t('allocationSize'), t('allocationShare'), t('allocationCutOff'), t('stratumExhaustive')])
const derivationHead = computed(() => [t('stepLabel'), t('stepFormula'), t('stepValue'), t('stepSource')])
</script>

<template>
  <section class="fa-samplesize__result" :aria-label="t('result')" data-testid="samplesize-result">
    <h3 class="fa-samplesize__heading">{{ t('result') }} <span class="fa-samplesize__badge">{{ plan.status_label }}</span></h3>
    <dl class="fa-samplesize__summary">
      <div v-for="row in summary" :key="row.key">
        <dt>{{ row.key }}</dt>
        <dd>{{ row.text }}</dd>
      </div>
    </dl>
    <table v-if="allocation.length" class="fa-samplesize__table" data-testid="samplesize-allocation">
      <caption>{{ t('allocation') }}</caption>
      <thead><tr><th v-for="head in allocationHead" :key="head" scope="col">{{ head }}</th></tr></thead>
      <tbody><tr v-for="(row, index) in allocation" :key="index"><td v-for="(cell, column) in row" :key="column">{{ cell }}</td></tr></tbody>
    </table>
    <table class="fa-samplesize__table" data-testid="samplesize-derivation">
      <caption>{{ t('derivation') }}</caption>
      <thead><tr><th v-for="head in derivationHead" :key="head" scope="col">{{ head }}</th></tr></thead>
      <tbody><tr v-for="(row, index) in derivation" :key="index"><td v-for="(cell, column) in row" :key="column">{{ cell }}</td></tr></tbody>
    </table>
    <ul v-if="plan.warnings.length" class="fa-samplesize__warnings" :aria-label="t('warnings')">
      <li v-for="warning in plan.warnings" :key="warning">{{ warning }}</li>
    </ul>
  </section>
</template>
