// packages-js/ui/src/reporttemplates/TemplateContract.vue
<!-- Datenvertrag und Textbausteine einer Vorlage (Teil von ReportTemplates). -->
<script setup lang="ts">
import { computed } from 'vue'
import { reporttemplatesMessages, schemaFields, textBlockRows, type TemplateDetail } from '@auditcore/ui-core'
import { useI18n, type Locale } from '../i18n'

const props = defineProps<{ detail: TemplateDetail; locale?: Locale }>()
const { t } = useI18n(reporttemplatesMessages, () => props.locale)
const fields = computed(() => schemaFields(props.detail))
const blocks = computed(() => textBlockRows(props.detail))
</script>

<template>
  <details class="fa-reporttemplates__card" data-testid="template-contract">
    <summary class="fa-reporttemplates__heading">{{ t('contract') }}</summary>
    <div class="fa-reporttemplates__scroll">
      <table class="fa-reporttemplates__table">
        <thead>
          <tr><th scope="col">{{ t('field') }}</th><th scope="col">{{ t('fieldType') }}</th><th scope="col">{{ t('fieldRequired') }}</th></tr>
        </thead>
        <tbody>
          <tr v-for="field in fields" :key="field.name">
            <td><code>{{ field.name }}</code><span v-if="field.title"> – {{ field.title }}</span></td>
            <td>{{ field.type }}</td>
            <td>{{ field.required ? t('yes') : t('no') }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <template v-if="blocks.length">
      <h4 class="fa-reporttemplates__heading">{{ t('textBlocks') }}</h4>
      <ul class="fa-reporttemplates__blocks">
        <li v-for="block in blocks" :key="block.id">
          <strong>{{ block.title }}</strong>
          <span v-if="block.required"> · {{ t('required') }}</span>
          <span v-if="block.conditional"> · {{ t('conditional') }}</span>
          <span v-if="block.legalBasis" class="fa-reporttemplates__muted"> · {{ t('legalBasis', { basis: block.legalBasis }) }}</span>
        </li>
      </ul>
    </template>
  </details>
</template>

// packages-js/ui-react/src/reporttemplates/TemplateContract.tsx
import { schemaFields, textBlockRows, type ReporttemplatesMessageKey, type TemplateDetail, type Translate } from '@auditcore/ui-core'

/** Datenvertrag und Textbausteine einer Vorlage (Markup wie `TemplateContract.vue`). */
export function TemplateContract({ detail, t }: { detail: TemplateDetail; t: Translate<ReporttemplatesMessageKey> }) {
  const blocks = textBlockRows(detail)
  return (
    <details className="fa-reporttemplates__card" data-testid="template-contract">
      <summary className="fa-reporttemplates__heading">{t('contract')}</summary>
      <div className="fa-reporttemplates__scroll">
        <table className="fa-reporttemplates__table">
          <thead>
            <tr><th scope="col">{t('field')}</th><th scope="col">{t('fieldType')}</th><th scope="col">{t('fieldRequired')}</th></tr>
          </thead>
          <tbody>
            {schemaFields(detail).map((field) => (
              <tr key={field.name}>
                <td><code>{field.name}</code>{field.title ? <span> – {field.title}</span> : null}</td>
                <td>{field.type}</td>
                <td>{field.required ? t('yes') : t('no')}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {blocks.length ? (
        <>
          <h4 className="fa-reporttemplates__heading">{t('textBlocks')}</h4>
          <ul className="fa-reporttemplates__blocks">
            {blocks.map((block) => (
              <li key={block.id}>
                <strong>{block.title}</strong>
                {block.required ? <span> · {t('required')}</span> : null}
                {block.conditional ? <span> · {t('conditional')}</span> : null}
                {block.legalBasis ? <span className="fa-reporttemplates__muted"> · {t('legalBasis', { basis: block.legalBasis })}</span> : null}
              </li>
            ))}
          </ul>
        </>
      ) : null}
    </details>
  )
}
