// packages-js/ui-react/src/reporttemplates/TemplatePreviewPane.tsx
import type { ReporttemplatesMessageKey, TemplatePreview, Translate } from '@auditcore/ui-core'

interface Props {
  preview: TemplatePreview
  stale: boolean
  t: Translate<ReporttemplatesMessageKey>
}

/** Ergebnis der Vorlagenvorschau (Markup wie `TemplatePreviewPane.vue`). */
export function TemplatePreviewPane({ preview, stale, t }: Props) {
  return (
    <section className="fa-reporttemplates__card" aria-live="polite" data-testid="template-preview">
      <h3 className="fa-reporttemplates__heading">{t('preview')}</h3>
      {stale ? <p className="fa-reporttemplates__notice">{t('previewStale')}</p> : null}
      {preview.valid ? (
        <>
          <p className="fa-reporttemplates__muted">{t('valid')}</p>
          <p className="fa-reporttemplates__muted">{preview.text_blocks.length ? t('usedBlocks', { blocks: preview.text_blocks.join(', ') }) : t('noBlocks')}</p>
          {preview.html ? <iframe className="fa-reporttemplates__frame" sandbox="" referrerPolicy="no-referrer" title={t('previewFrame')} srcDoc={preview.html} /> : null}
        </>
      ) : (
        <>
          <p className="fa-reporttemplates__failure" role="alert">{t('invalid', { count: preview.issues.length })}</p>
          <ul className="fa-reporttemplates__issues">
            {preview.issues.map((issue) => <li key={issue.path + issue.message}><code>{issue.path}</code>: {issue.message}</li>)}
          </ul>
        </>
      )}
      <p className="fa-reporttemplates__muted">{t('notice')}</p>
    </section>
  )
}

// packages-js/ui/src/reporttemplates/TemplatePreviewPane.vue
<!-- Ergebnis der Vorlagenvorschau: Prüfung des Datenvertrags und abgeschottete HTML-Ansicht. -->
<script setup lang="ts">
import { reporttemplatesMessages, type TemplatePreview } from '@auditcore/ui-core'
import { useI18n, type Locale } from '../i18n'

const props = defineProps<{ preview: TemplatePreview; stale: boolean; locale?: Locale }>()
const { t } = useI18n(reporttemplatesMessages, () => props.locale)
</script>

<template>
  <section class="fa-reporttemplates__card" aria-live="polite" data-testid="template-preview">
    <h3 class="fa-reporttemplates__heading">{{ t('preview') }}</h3>
    <p v-if="stale" class="fa-reporttemplates__notice">{{ t('previewStale') }}</p>
    <template v-if="preview.valid">
      <p class="fa-reporttemplates__muted">{{ t('valid') }}</p>
      <p class="fa-reporttemplates__muted">{{ preview.text_blocks.length ? t('usedBlocks', { blocks: preview.text_blocks.join(', ') }) : t('noBlocks') }}</p>
      <iframe v-if="preview.html" class="fa-reporttemplates__frame" sandbox="" referrerpolicy="no-referrer" :title="t('previewFrame')" :srcdoc="preview.html" />
    </template>
    <template v-else>
      <p class="fa-reporttemplates__failure" role="alert">{{ t('invalid', { count: preview.issues.length }) }}</p>
      <ul class="fa-reporttemplates__issues">
        <li v-for="issue in preview.issues" :key="issue.path + issue.message"><code>{{ issue.path }}</code>: {{ issue.message }}</li>
      </ul>
    </template>
    <p class="fa-reporttemplates__muted">{{ t('notice') }}</p>
  </section>
</template>
