// packages-js/bpmn-react/src/panels/FieldForm.tsx
/**
 * Renders one object from declarative field descriptions. Reports the whole
 * updated object on every committed change (blur/Enter for text fields).
 */

import { fieldText, inputType, isWide, parseFieldInput, unknownOption, withField, type FieldDescriptor, type Option } from '@auditcore/bpmn-flowaudit/ui'
import { useElementId } from '../hooks'
import { useI18n } from '../i18n'
import { CommitField } from './CommitField'

type Row = Record<string, unknown>

export interface FieldFormProps {
  value: Row
  fields: FieldDescriptor[]
  optionsFor: (field: FieldDescriptor) => Option[]
  disabled?: boolean
  onUpdate: (value: Row) => void
}

interface FieldProps extends Omit<FieldFormProps, 'fields'> {
  field: FieldDescriptor
  labelId: string
}

function SelectField({ value, field, optionsFor, disabled, onUpdate, labelId }: FieldProps) {
  const { t } = useI18n()
  const text = fieldText(value, field)
  const options = optionsFor(field)
  const unknown = unknownOption(options, text)
  return (
    <select className="fa-select" value={text} disabled={disabled} aria-labelledby={labelId} onChange={(event) => onUpdate(withField(value, field.key, event.target.value))}>
      <option value="">{t('common.none')}</option>
      {options.map((option) => (
        <option key={option.value} value={option.value}>{option.label}</option>
      ))}
      {unknown ? <option value={text}>{text}</option> : null}
    </select>
  )
}

function Field(props: FieldProps) {
  const { t } = useI18n()
  const { value, field, disabled, onUpdate, labelId } = props
  if (field.kind === 'checkbox') {
    return (
      <span className="fa-check">
        <input type="checkbox" checked={Boolean(value[field.key])} disabled={disabled} onChange={(event) => onUpdate(withField(value, field.key, event.target.checked))} />
        {t(field.label)}
      </span>
    )
  }
  const commit = (raw: string) => onUpdate(withField(value, field.key, parseFieldInput(field, raw)))
  const text = fieldText(value, field)
  return (
    <>
      <span id={labelId} className="fa-label">{t(field.label)}</span>
      {field.kind === 'select' ? (
        <SelectField {...props} />
      ) : field.kind === 'textarea' ? (
        <CommitField multiline className="fa-textarea" rows={3} value={text} disabled={disabled} placeholder={field.placeholder} onCommit={commit} />
      ) : (
        <CommitField className="fa-input" type={inputType(field)} value={text} disabled={disabled} placeholder={field.placeholder} onCommit={commit} />
      )}
    </>
  )
}

export function FieldForm({ fields, ...props }: FieldFormProps) {
  const uid = useElementId('fa-field')
  return (
    <div className="fa-grid-2 fa-field-form">
      {fields.map((field) => (
        <label key={field.key} className={isWide(field) ? 'fa-field fa-field--wide' : 'fa-field'}>
          <Field {...props} field={field} labelId={`${uid}-${field.key}`} />
        </label>
      ))}
    </div>
  )
}

// packages-js/bpmn-vue/src/panels/FieldForm.vue
<script setup lang="ts">
/**
 * Renders one object from declarative field descriptions. Emits the whole
 * updated object on every committed change (blur/enter for text fields).
 */
import { fieldText, inputType, isWide, parseFieldInput, unknownOption, withField, type FieldDescriptor, type Option } from '@auditcore/bpmn-flowaudit/ui'
import { useI18n } from '../i18n/useI18n'

const props = defineProps<{
  value: Record<string, unknown>
  fields: FieldDescriptor[]
  optionsFor: (field: FieldDescriptor) => Option[]
  disabled?: boolean
}>()
const emit = defineEmits<{ (e: 'update', value: Record<string, unknown>): void }>()
const { t } = useI18n()
const uid = Math.random().toString(36).slice(2, 8)

const set = (key: string, raw: unknown) => emit('update', withField(props.value, key, raw))
const text = (field: FieldDescriptor) => fieldText(props.value, field)
const onText = (field: FieldDescriptor, event: Event) => set(field.key, parseFieldInput(field, (event.target as HTMLInputElement).value))
</script>

<template>
  <div class="fa-grid-2 fa-field-form">
    <label v-for="field in fields" :key="field.key" class="fa-field" :class="{ 'fa-field--wide': isWide(field) }">
      <template v-if="field.kind === 'checkbox'">
        <span class="fa-check">
          <input type="checkbox" :checked="Boolean(value[field.key])" :disabled="disabled" @change="set(field.key, ($event.target as HTMLInputElement).checked)" />
          {{ t(field.label) }}
        </span>
      </template>
      <template v-else>
        <span :id="`${uid}-${field.key}`" class="fa-label">{{ t(field.label) }}</span>
        <select
          v-if="field.kind === 'select'"
          class="fa-select"
          :value="text(field)"
          :disabled="disabled"
          :aria-labelledby="`${uid}-${field.key}`"
          @change="set(field.key, ($event.target as HTMLSelectElement).value)"
        >
          <option value="">{{ t('common.none') }}</option>
          <option v-for="option in optionsFor(field)" :key="option.value" :value="option.value">{{ option.label }}</option>
          <option v-if="unknownOption(optionsFor(field), text(field))" :value="text(field)">{{ text(field) }}</option>
        </select>
        <textarea
          v-else-if="field.kind === 'textarea'"
          class="fa-textarea"
          rows="3"
          :value="text(field)"
          :disabled="disabled"
          :placeholder="field.placeholder"
          @change="onText(field, $event)"
        />
        <input
          v-else
          class="fa-input"
          :type="inputType(field)"
          :value="text(field)"
          :disabled="disabled"
          :placeholder="field.placeholder"
          @change="onText(field, $event)"
        />
      </template>
    </label>
  </div>
</template>
