// packages-js/bpmn-react/src/panels/PropertiesPanel.tsx
/**
 * Properties panel with tabs (General, Role, Legal bases, Audit attributes, Audit reference,
 * Control & risk, Evidence, Findings, Source, Notes, Colour). Tabs follow the
 * WAI-ARIA tabs pattern (arrow keys, Home/End).
 */

import { useEffect, useRef, useState, type KeyboardEvent } from 'react'
import type { Comment, PaletteColor } from '@auditcore/bpmn-flowaudit'
import { listsFor, tabMove, tabsFor, type TabDefinition, type TabId } from '@auditcore/bpmn-flowaudit/ui'
import { FaIcon } from '../base/FaIcon'
import { useEditorContext, useSelectionState } from '../context'
import { useI18n } from '../i18n'
import { ColorTab } from './tabs/ColorTab'
import { GeneralTab } from './tabs/GeneralTab'
import { LegalTab } from './tabs/LegalTab'
import { ListsTab } from './tabs/ListsTab'
import { NotesTab } from './tabs/NotesTab'
import { PropertiesTab } from './tabs/PropertiesTab'
import { RoleTab } from './tabs/RoleTab'

export interface PropertiesPanelProps {
  comments: Comment[]
  author: string
  palette?: readonly PaletteColor[]
  onCommentsChange: (comments: Comment[]) => void
}

function TabContent({ tab, type, props }: { tab: TabDefinition; type: string; props: PropertiesPanelProps }) {
  if (tab.id === 'general') return <GeneralTab />
  if (tab.id === 'role') return <RoleTab />
  if (tab.id === 'legal') return <LegalTab />
  if (tab.id === 'properties') return <PropertiesTab />
  if (tab.id === 'notes') return <NotesTab comments={props.comments} author={props.author} onCommentsChange={props.onCommentsChange} />
  if (tab.id === 'color') return <ColorTab palette={props.palette} />
  return <ListsTab lists={listsFor(tab, type)} />
}

export function PropertiesPanel(props: PropertiesPanelProps) {
  const { t } = useI18n()
  const { element, type } = useSelectionState()
  const { profile } = useEditorContext()
  const [active, setActive] = useState<TabId>('general')
  const tabRefs = useRef<(HTMLButtonElement | null)[]>([])
  const tabs = tabsFor(type, profile())
  const known = tabs.some((tab) => tab.id === active)
  const current = tabs.find((tab) => tab.id === (known ? active : 'general')) ?? tabs[0]

  useEffect(() => {
    if (!known) setActive('general')
  }, [known])

  const onKey = (event: KeyboardEvent, index: number) => {
    const next = tabMove(event.key, index, tabs.length)
    if (next === null) return
    event.preventDefault()
    const tab = tabs[next]
    if (tab) setActive(tab.id)
    tabRefs.current[next]?.focus()
  }

  return (
    <aside className="fa-props" aria-label={t('props.label')}>
      {!element ? (
        <p className="fa-props__empty">{t('editor.noSelection')}</p>
      ) : (
        <>
          <div className="fa-props__tabs" role="tablist" aria-orientation="vertical" aria-label={t('props.label')}>
            {tabs.map((tab, index) => (
              <button
                id={`fa-tab-${tab.id}`}
                key={tab.id}
                ref={(node) => void (tabRefs.current[index] = node)}
                type="button"
                role="tab"
                className="fa-props__tab"
                aria-selected={current?.id === tab.id}
                aria-controls={`fa-tabpanel-${tab.id}`}
                tabIndex={current?.id === tab.id ? 0 : -1}
                title={t(tab.label)}
                onClick={() => setActive(tab.id)}
                onKeyDown={(event) => onKey(event, index)}
              >
                <FaIcon name={tab.icon} size={18} />
                <span className="fa-props__tab-label">{t(tab.label)}</span>
              </button>
            ))}
          </div>
          {current ? (
            <section id={`fa-tabpanel-${current.id}`} className="fa-props__panel" role="tabpanel" aria-labelledby={`fa-tab-${current.id}`} tabIndex={0}>
              <h2 className="fa-props__title">{t(current.label)}</h2>
              <TabContent tab={current} type={type ?? ''} props={props} />
            </section>
          ) : null}
        </>
      )}
    </aside>
  )
}

// packages-js/bpmn-vue/src/panels/PropertiesPanel.vue
<script setup lang="ts">
/**
 * Properties panel with tabs (General, Role, Legal bases, Audit attributes, Audit reference,
 * Control & risk, Evidence, Findings, Source, Notes, Colour). Tabs follow the
 * WAI-ARIA tabs pattern (arrow keys, Home/End).
 */
import { computed, ref, watch } from 'vue'
import type { Comment, PaletteColor } from '@auditcore/bpmn-flowaudit'
import FaIcon from '../components/base/FaIcon.vue'
import { useI18n } from '../i18n/useI18n'
import { useEditorContext } from '../stores/context'
import { listsFor, tabMove, tabsFor, type TabId } from '@auditcore/bpmn-flowaudit/ui'
import ColorTab from './tabs/ColorTab.vue'
import GeneralTab from './tabs/GeneralTab.vue'
import LegalTab from './tabs/LegalTab.vue'
import ListsTab from './tabs/ListsTab.vue'
import NotesTab from './tabs/NotesTab.vue'
import PropertiesTab from './tabs/PropertiesTab.vue'
import RoleTab from './tabs/RoleTab.vue'

defineProps<{ comments: Comment[]; author: string; palette?: readonly PaletteColor[] }>()
const emit = defineEmits<{ (e: 'update:comments', value: Comment[]): void }>()
const { selection, profile } = useEditorContext()
const { t } = useI18n()

const active = ref<TabId>('general')
const type = computed(() => selection.type.value)
const tabs = computed(() => tabsFor(type.value, profile()))
const current = computed(() => tabs.value.find((tab) => tab.id === active.value) ?? tabs.value[0])
const tabRefs = ref<HTMLElement[]>([])

watch(tabs, (list) => {
  if (!list.some((tab) => tab.id === active.value)) active.value = 'general'
})

function onKey(event: KeyboardEvent, index: number): void {
  const next = tabMove(event.key, index, tabs.value.length)
  if (next === null) return
  event.preventDefault()
  const tab = tabs.value[next]
  if (tab) active.value = tab.id
  tabRefs.value[next]?.focus()
}
</script>

<template>
  <aside class="fa-props" :aria-label="t('props.label')">
    <p v-if="!selection.element.value" class="fa-props__empty">{{ t('editor.noSelection') }}</p>
    <template v-else>
      <div class="fa-props__tabs" role="tablist" aria-orientation="vertical" :aria-label="t('props.label')">
        <button
          v-for="(tab, index) in tabs"
          :id="`fa-tab-${tab.id}`"
          :key="tab.id"
          :ref="(el) => (tabRefs[index] = el as HTMLElement)"
          type="button"
          role="tab"
          class="fa-props__tab"
          :aria-selected="current?.id === tab.id"
          :aria-controls="`fa-tabpanel-${tab.id}`"
          :tabindex="current?.id === tab.id ? 0 : -1"
          :title="t(tab.label)"
          @click="active = tab.id"
          @keydown="onKey($event, index)"
        >
          <FaIcon :name="tab.icon" :size="18" />
          <span class="fa-props__tab-label">{{ t(tab.label) }}</span>
        </button>
      </div>
      <section v-if="current" :id="`fa-tabpanel-${current.id}`" class="fa-props__panel" role="tabpanel" :aria-labelledby="`fa-tab-${current.id}`" tabindex="0">
        <h2 class="fa-props__title">{{ t(current.label) }}</h2>
        <GeneralTab v-if="current.id === 'general'" />
        <RoleTab v-else-if="current.id === 'role'" />
        <LegalTab v-else-if="current.id === 'legal'" />
        <PropertiesTab v-else-if="current.id === 'properties'" />
        <NotesTab v-else-if="current.id === 'notes'" :comments="comments" :author="author" @update:comments="emit('update:comments', $event)" />
        <ColorTab v-else-if="current.id === 'color'" :palette="palette" />
        <ListsTab v-else :lists="listsFor(current, type ?? '')" />
      </section>
    </template>
  </aside>
</template>
