// packages-js/ui-react/src/documents/ComparisonList.tsx
import { useRef, type ChangeEvent } from 'react'
import type { ComparisonsTranslate, SummaryView } from '@auditcore/ui-core'
import { Badge } from '../base/Badge'
import { Button } from '../base/Button'
import { TextField } from '../base/TextField'
import { useElementId } from '../store'

export interface ComparisonListProps {
  rows?: readonly SummaryView[]
  query?: string
  countText?: string
  emptyText?: string | null
  busy?: boolean
  /** Löschen und Import anbieten. */
  editable?: boolean
  canImport?: boolean
  t: ComparisonsTranslate
  onQueryChange: (query: string) => void
  onComparisonOpen: (id: string) => void
  onComparisonRemove: (id: string) => void
  onResultImport: (text: string) => void
}

function Row({ row, props }: { row: SummaryView; props: ComparisonListProps }) {
  const { t, busy = false, editable = true } = props
  return (
    <li className="fa-comparisons-list__item" data-id={row.id}>
      <div className="fa-comparisons-list__main">
        <p className="fa-comparisons-list__title">{row.title}</p>
        <p className="fa-comparisons-list__meta">
          <Badge tone={row.kind === 'article_law' ? 'accent' : 'neutral'}>{row.kindLabel}</Badge>
          <time dateTime={row.createdIso}>{row.created}</time>
        </p>
        <p className="fa-comparisons-list__files">{row.files}</p>
        <p className="fa-comparisons-list__counts">{row.counts}</p>
      </div>
      <div className="fa-comparisons-list__actions">
        <Button size="sm" variant="primary" ariaLabel={t('openLabel', { title: row.title })} onClick={() => props.onComparisonOpen(row.id)}>{t('open')}</Button>
        {editable ? <Button size="sm" variant="ghost" icon="trash" iconOnly label={t('removeLabel', { title: row.title })} disabled={busy} onClick={() => props.onComparisonRemove(row.id)} /> : null}
      </div>
    </li>
  )
}

/** Gespeicherte Vergleiche mit Suche, Öffnen, Löschen und JSON-Import (wie `ComparisonList.vue`). */
export function ComparisonList(props: ComparisonListProps) {
  const { rows = [], t, emptyText = null, editable = true } = props
  const headingId = useElementId('fa-comparisons-list')
  const picker = useRef<HTMLInputElement | null>(null)
  const onImport = async (event: ChangeEvent<HTMLInputElement>): Promise<void> => {
    const input = event.target
    const chosen = input.files?.[0]
    input.value = ''
    if (chosen) props.onResultImport(await chosen.text())
  }
  return (
    <section className="fa-comparisons-list" aria-labelledby={headingId}>
      <div className="fa-comparisons-list__head">
        <h3 id={headingId} className="fa-comparisons__subheading">{t('listHeading')}</h3>
        {editable && props.canImport ? (
          <>
            <Button size="sm" icon="paperclip" disabled={props.busy} onClick={() => picker.current?.click()}>{t('importLabel')}</Button>
            <input ref={picker} className="fa-sr-only" type="file" accept=".json,application/json" tabIndex={-1} aria-hidden="true" data-testid="comparisons-import" onChange={(event) => void onImport(event)} />
          </>
        ) : null}
      </div>
      <TextField value={props.query ?? ''} type="search" label={t('searchLabel')} onChange={props.onQueryChange} />
      <p className="fa-comparisons-list__count">{props.countText}</p>
      {emptyText ? <p className="fa-comparisons__state">{emptyText}</p> : (
        <ul className="fa-comparisons-list__items">{rows.map((row) => <Row key={row.id} row={row} props={props} />)}</ul>
      )}
    </section>
  )
}

// packages-js/ui/src/documents/ComparisonList.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { SummaryView } from '@auditcore/ui-core'
import { comparisonsMessages } from '@auditcore/ui-core'
import FaBadge from '../base/FaBadge.vue'
import FaButton from '../base/FaButton.vue'
import FaTextField from '../base/FaTextField.vue'
import { useId } from '../composables/useId'
import { useI18n } from '../i18n'

withDefaults(defineProps<{
  rows?: SummaryView[]
  query?: string
  countText?: string
  emptyText?: string | null
  busy?: boolean
  /** Löschen und Import anbieten. */
  editable?: boolean
  canImport?: boolean
}>(), { rows: () => [], query: '', countText: '', emptyText: null, busy: false, editable: true, canImport: false })

const emit = defineEmits<{
  'update:query': [query: string]
  'comparison-open': [id: string]
  'comparison-remove': [id: string]
  'result-import': [text: string]
}>()

const { t } = useI18n(comparisonsMessages)
const headingId = useId('fa-comparisons-list')
const picker = ref<HTMLInputElement | null>(null)

async function onImport(event: Event): Promise<void> {
  const input = event.target as HTMLInputElement
  const chosen = input.files?.[0]
  input.value = ''
  if (chosen) emit('result-import', await chosen.text())
}
</script>

<template>
  <section class="fa-comparisons-list" :aria-labelledby="headingId">
    <div class="fa-comparisons-list__head">
      <h3 :id="headingId" class="fa-comparisons__subheading">{{ t('listHeading') }}</h3>
      <template v-if="editable && canImport">
        <FaButton size="sm" icon="paperclip" :disabled="busy" @click="picker?.click()">{{ t('importLabel') }}</FaButton>
        <input ref="picker" class="fa-sr-only" type="file" accept=".json,application/json" tabindex="-1" aria-hidden="true" data-testid="comparisons-import" @change="onImport" />
      </template>
    </div>
    <FaTextField :model-value="query" type="search" :label="t('searchLabel')" @update:model-value="emit('update:query', $event)" />
    <p class="fa-comparisons-list__count">{{ countText }}</p>
    <p v-if="emptyText" class="fa-comparisons__state">{{ emptyText }}</p>
    <ul v-else class="fa-comparisons-list__items">
      <li v-for="row in rows" :key="row.id" class="fa-comparisons-list__item" :data-id="row.id">
        <div class="fa-comparisons-list__main">
          <p class="fa-comparisons-list__title">{{ row.title }}</p>
          <p class="fa-comparisons-list__meta">
            <FaBadge :tone="row.kind === 'article_law' ? 'accent' : 'neutral'">{{ row.kindLabel }}</FaBadge>
            <time :datetime="row.createdIso">{{ row.created }}</time>
          </p>
          <p class="fa-comparisons-list__files">{{ row.files }}</p>
          <p class="fa-comparisons-list__counts">{{ row.counts }}</p>
        </div>
        <div class="fa-comparisons-list__actions">
          <FaButton size="sm" variant="primary" :aria-label="t('openLabel', { title: row.title })" @click="emit('comparison-open', row.id)">{{ t('open') }}</FaButton>
          <FaButton v-if="editable" size="sm" variant="ghost" icon="trash" icon-only :label="t('removeLabel', { title: row.title })" :disabled="busy" @click="emit('comparison-remove', row.id)" />
        </div>
      </li>
    </ul>
  </section>
</template>
