// packages-js/ui-react/src/sampling/SamplingPopulation.tsx
import { itemsFromImport, populationText, type Locale, type PopulationItem, type SamplingTranslate } from '@auditcore/ui-core'
import { TableImport } from '../tabular/TableImport'
import { useElementId } from '../store'

export interface SamplingPopulationProps {
  items: readonly PopulationItem[]
  t: SamplingTranslate
  locale: Locale
  /** Sprache des Datei-Imports wie in Vue (Prop der Hauptkomponente). */
  importLocale?: Locale
  onImport: (items: PopulationItem[]) => void
}

/** Grundgesamtheit mit Zusammenfassung und Datei-Import (wie `SamplingPopulation.vue`). */
export function SamplingPopulation({ items, t, locale, importLocale, onImport }: SamplingPopulationProps) {
  const id = useElementId('fa-sampling-population')
  return (
    <section className="fa-sampling__card" aria-labelledby={`${id}-title`}>
      <h3 id={`${id}-title`} className="fa-sampling__heading">{t('population')}</h3>
      {items.length ? (
        <p className="fa-sampling__muted" data-testid="sampling-population">{populationText(items, t, locale)}</p>
      ) : (
        <p className="fa-sampling__muted">{t('populationEmpty')}</p>
      )}
      <TableImport mode="items" locale={importLocale} onImport={(columns) => onImport(itemsFromImport(columns))} />
    </section>
  )
}

// packages-js/ui/src/sampling/SamplingPopulation.vue
<script setup lang="ts">
import { computed } from 'vue'
import { itemsFromImport, populationText, samplingMessages, type ImportedColumns, type PopulationItem } from '@auditcore/ui-core'
import { useId } from '../composables/useId'
import { useI18n, type Locale } from '../i18n'
import TableImport from '../tabular/TableImport.vue'

const props = withDefaults(defineProps<{ items: readonly PopulationItem[]; locale?: Locale }>(), { locale: undefined })
const emit = defineEmits<{ import: [items: PopulationItem[]] }>()
const { t, locale: active } = useI18n(samplingMessages, () => props.locale)
const id = useId('fa-sampling-population')
const summary = computed(() => populationText(props.items, t, active.value))

function onImport(columns: ImportedColumns): void {
  emit('import', itemsFromImport(columns))
}
</script>

<template>
  <section class="fa-sampling__card" :aria-labelledby="`${id}-title`">
    <h3 :id="`${id}-title`" class="fa-sampling__heading">{{ t('population') }}</h3>
    <p v-if="items.length" class="fa-sampling__muted" data-testid="sampling-population">{{ summary }}</p>
    <p v-else class="fa-sampling__muted">{{ t('populationEmpty') }}</p>
    <TableImport mode="items" :locale="locale" @import="onImport" />
  </section>
</template>
