// packages-js/ui-react/src/batchchecks/BatchChecksInput.tsx
import type { ChangeEvent, FormEvent } from 'react'
import type { DecimalSeparator } from '@auditcore/common'
import { batchchecksColumnFields, batchchecksHasTable, batchchecksSourceText, importOptionalColumn } from '@auditcore/ui-core'
import { Button } from '../base/Button'
import type { UseBatchChecks } from './useBatchChecks'

/** Spaltenzuordnung der Tabelle (wie der `fieldset` in `BatchChecksInput.vue`). */
function Columns({ view }: { view: UseBatchChecks }) {
  const { state, table, controller, t } = view
  const header = table.table?.header ?? []
  return (
    <fieldset className="fa-batchchecks__card">
      <legend className="fa-batchchecks__subheading">{t('columns')}</legend>
      <label className="fa-batchchecks__check">
        <input type="checkbox" checked={table.hasHeader} data-testid="batchchecks-header" onChange={(event) => controller.setHasHeader(event.target.checked)} />
        {t('header')}
      </label>
      <div className="fa-batchchecks__grid">
        <label className="fa-batchchecks__field">
          <span className="fa-batchchecks__label">{t('decimal')}</span>
          <select className="fa-batchchecks__input" value={table.decimal} data-testid="batchchecks-decimal" onChange={(event) => controller.setDecimal(event.target.value as DecimalSeparator)}>
            <option value=",">{t('decimalComma')}</option>
            <option value=".">{t('decimalDot')}</option>
          </select>
        </label>
        {batchchecksColumnFields(state).map((field) => (
          <label key={field.name} className="fa-batchchecks__field">
            <span className="fa-batchchecks__label">{field.label}</span>
            <select className="fa-batchchecks__input" value={field.value ?? ''} data-testid={`batchchecks-col-${field.name}`} onChange={(event) => controller.setColumn(field.name, importOptionalColumn(event.target.value))}>
              <option value="">{t('none')}</option>
              {header.map((name, index) => <option key={index} value={index}>{name}</option>)}
            </select>
          </label>
        ))}
      </div>
    </fieldset>
  )
}

/** Bestand einlesen: Datei, Zuordnung, Gesamtvolumen, Ergänzungsprüfungen (wie `BatchChecksInput.vue`). */
export function BatchChecksInput({ view, id }: { view: UseBatchChecks; id: string }) {
  const { state, table, controller, t } = view
  const max = state.catalogue?.limits.max_documents ?? 0
  const source = batchchecksSourceText(state, table, t)
  const onFile = async (event: ChangeEvent<HTMLInputElement>): Promise<void> => {
    const file = event.target.files?.[0]
    if (file) await controller.readFile(file)
  }
  const onSubmit = (event: FormEvent): void => {
    event.preventDefault()
    void controller.check()
  }
  return (
    <form className="fa-batchchecks__card" noValidate aria-labelledby={`${id}-input`} onSubmit={onSubmit}>
      <h3 id={`${id}-input`} className="fa-batchchecks__heading">{t('input')}</h3>
      <label className="fa-batchchecks__field">
        <span className="fa-batchchecks__label">{t('file')}</span>
        <input className="fa-batchchecks__file" type="file" accept=".csv,.tsv,.txt,.json,text/csv,text/plain,application/json" data-testid="batchchecks-file" onChange={(event) => void onFile(event)} />
      </label>
      <p className="fa-batchchecks__muted">{t('fileHelp', { max })}</p>
      {source ? <p className="fa-batchchecks__muted" aria-live="polite" data-testid="batchchecks-source">{source}</p> : null}
      {batchchecksHasTable(state, table) ? <Columns view={view} /> : null}
      <div className="fa-batchchecks__grid">
        <label className="fa-batchchecks__field">
          <span className="fa-batchchecks__label">{t('totalVolume')}</span>
          <input className="fa-batchchecks__input" type="text" inputMode="decimal" value={state.totalVolume} data-testid="batchchecks-total" onChange={(event) => controller.setTotalVolume(event.target.value)} />
        </label>
        <label className="fa-batchchecks__check">
          <input type="checkbox" checked={state.supplementary} data-testid="batchchecks-supplementary" onChange={(event) => controller.setSupplementary(event.target.checked)} />
          {t('supplementary')}
        </label>
      </div>
      <p className="fa-batchchecks__muted">{t('totalVolumeHelp')}</p>
      {state.validation ? <p className="fa-batchchecks__error" role="alert">{t(`error${state.validation}`, { max })}</p> : null}
      <div>
        <Button variant="primary" type="submit" loading={state.busy === 'run'} testId="batchchecks-run">{t('run')}</Button>
      </div>
    </form>
  )
}

// packages-js/ui/src/batchchecks/BatchChecksInput.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { DecimalSeparator } from '@auditcore/common'
import {
  batchchecksColumnFields,
  batchchecksHasTable,
  batchchecksSourceText,
  importOptionalColumn,
  type BatchchecksController,
  type BatchchecksData,
  type BatchchecksTranslate,
  type TableImportData,
} from '@auditcore/ui-core'
import FaButton from '../base/FaButton.vue'

const props = defineProps<{
  id: string
  controller: BatchchecksController
  state: BatchchecksData
  table: TableImportData
  t: BatchchecksTranslate
}>()

const hasTable = computed(() => batchchecksHasTable(props.state, props.table))
const columns = computed(() => batchchecksColumnFields(props.state))
const header = computed(() => props.table.table?.header ?? [])
const source = computed(() => batchchecksSourceText(props.state, props.table, props.t))
const max = computed(() => props.state.catalogue?.limits.max_documents ?? 0)

async function onFile(event: Event): Promise<void> {
  const file = (event.target as HTMLInputElement).files?.[0]
  if (file) await props.controller.readFile(file)
}

const value = (event: Event): string => (event.target as HTMLInputElement | HTMLSelectElement).value
const checked = (event: Event): boolean => (event.target as HTMLInputElement).checked
</script>

<template>
  <form class="fa-batchchecks__card" novalidate :aria-labelledby="`${id}-input`" @submit.prevent="controller.check">
    <h3 :id="`${id}-input`" class="fa-batchchecks__heading">{{ t('input') }}</h3>
    <label class="fa-batchchecks__field">
      <span class="fa-batchchecks__label">{{ t('file') }}</span>
      <input class="fa-batchchecks__file" type="file" accept=".csv,.tsv,.txt,.json,text/csv,text/plain,application/json" data-testid="batchchecks-file" @change="onFile" />
    </label>
    <p class="fa-batchchecks__muted">{{ t('fileHelp', { max }) }}</p>
    <p v-if="source" class="fa-batchchecks__muted" aria-live="polite" data-testid="batchchecks-source">{{ source }}</p>
    <fieldset v-if="hasTable" class="fa-batchchecks__card">
      <legend class="fa-batchchecks__subheading">{{ t('columns') }}</legend>
      <label class="fa-batchchecks__check">
        <input type="checkbox" :checked="table.hasHeader" data-testid="batchchecks-header" @change="controller.setHasHeader(checked($event))" />
        {{ t('header') }}
      </label>
      <div class="fa-batchchecks__grid">
        <label class="fa-batchchecks__field">
          <span class="fa-batchchecks__label">{{ t('decimal') }}</span>
          <select class="fa-batchchecks__input" :value="table.decimal" data-testid="batchchecks-decimal" @change="controller.setDecimal(value($event) as DecimalSeparator)">
            <option value=",">{{ t('decimalComma') }}</option>
            <option value=".">{{ t('decimalDot') }}</option>
          </select>
        </label>
        <label v-for="field in columns" :key="field.name" class="fa-batchchecks__field">
          <span class="fa-batchchecks__label">{{ field.label }}</span>
          <select class="fa-batchchecks__input" :value="field.value ?? ''" :data-testid="`batchchecks-col-${field.name}`" @change="controller.setColumn(field.name, importOptionalColumn(value($event)))">
            <option value="">{{ t('none') }}</option>
            <option v-for="(name, index) in header" :key="index" :value="index">{{ name }}</option>
          </select>
        </label>
      </div>
    </fieldset>
    <div class="fa-batchchecks__grid">
      <label class="fa-batchchecks__field">
        <span class="fa-batchchecks__label">{{ t('totalVolume') }}</span>
        <input class="fa-batchchecks__input" type="text" inputmode="decimal" :value="state.totalVolume" data-testid="batchchecks-total" @input="controller.setTotalVolume(value($event))" />
      </label>
      <label class="fa-batchchecks__check">
        <input type="checkbox" :checked="state.supplementary" data-testid="batchchecks-supplementary" @change="controller.setSupplementary(checked($event))" />
        {{ t('supplementary') }}
      </label>
    </div>
    <p class="fa-batchchecks__muted">{{ t('totalVolumeHelp') }}</p>
    <p v-if="state.validation" class="fa-batchchecks__error" role="alert">{{ t(`error${state.validation}`, { max }) }}</p>
    <div>
      <FaButton variant="primary" type="submit" :loading="state.busy === 'run'" data-testid="batchchecks-run">{{ t('run') }}</FaButton>
    </div>
  </form>
</template>
