// packages-js/ui/src/dataprotection/components/AssistantChecklist.vue
<script setup lang="ts">
import { reactive, watch } from 'vue'
import type { ChecklistChange, ChecklistItemView, ChecklistStatus } from '@auditcore/ui-core'
import { useI18n } from '../../i18n'
import { dataprotectionMessages, prefixedLabel } from '../core'

const emit = defineEmits<{ change: [itemId: string, change: ChecklistChange] }>()
const { t } = useI18n(dataprotectionMessages)

const STATUSES: ChecklistStatus[] = ['offen', 'in_bearbeitung', 'zur_pruefung', 'nachgewiesen', 'klaerungsbedarf', 'nicht_erfuellt', 'nicht_anwendbar', 'erneut_zu_pruefen']
interface Edit { status: ChecklistStatus; justification: string; evidence: string }
const props = defineProps<{ items: ChecklistItemView[]; busy: boolean }>()
const edits = reactive<Record<string, Edit>>({})

// Eingaben je Prüfpunkt; ein neuer Serverstand setzt sie zurück.
watch(() => props.items, (items) => {
  for (const item of items) edits[item.id] = { status: item.status, justification: item.justification, evidence: item.evidence_ids.join(', ') }
}, { immediate: true })

function edit(item: ChecklistItemView): Edit {
  return edits[item.id] ?? { status: item.status, justification: '', evidence: '' }
}

function save(item: ChecklistItemView): void {
  const current = edit(item)
  const evidence = current.evidence.split(',').map((entry) => entry.trim()).filter(Boolean)
  emit('change', item.id, { status: current.status, justification: current.justification, evidence_ids: evidence })
}
</script>

<template>
  <section class="fa-dataprotection__panel" data-testid="assistant-checklist" aria-labelledby="fa-assistant-checklist">
    <h3 id="fa-assistant-checklist">{{ t('checklistTitle') }}</h3>
    <table class="fa-dataprotection__table">
      <tbody>
        <tr v-for="item in items" :key="item.id" :data-item="item.id">
          <th scope="row">{{ item.id }}</th>
          <td>
            {{ item.titel }}
            <span v-if="item.sperrt" class="fa-assistant__badge">{{ t('itemBlocks', { gate: item.sperrt }) }}</span>
            <br /><span class="fa-dataprotection__muted">{{ prefixedLabel(t, 'item', item.status) }} · {{ item.zustaendig }}</span>
          </td>
          <td>
            <label>{{ t('checklistStatus', { id: item.id }) }}
              <select v-model="edit(item).status">
                <option v-for="status in STATUSES" :key="status" :value="status">{{ prefixedLabel(t, 'item', status) }}</option>
              </select>
            </label>
            <label>{{ t('evidenceIds') }} <input v-model="edit(item).evidence" type="text" /></label>
            <label>{{ t('answerJustification') }} <textarea v-model="edit(item).justification" rows="2"></textarea></label>
            <button type="button" :disabled="busy" @click="save(item)">{{ t('saveItem') }}</button>
          </td>
        </tr>
      </tbody>
    </table>
  </section>
</template>

// packages-js/ui-react/src/dataprotection/assistant/AssistantChecklist.tsx
import { useEffect, useState } from 'react'
import type { ChecklistChange, ChecklistItemView, ChecklistStatus } from '@auditcore/ui-core'
import { prefixedLabel, useDataProtectionText } from '../shared'

const STATUSES: ChecklistStatus[] = ['offen', 'in_bearbeitung', 'zur_pruefung', 'nachgewiesen', 'klaerungsbedarf', 'nicht_erfuellt', 'nicht_anwendbar', 'erneut_zu_pruefen']

interface Edit { status: ChecklistStatus; justification: string; evidence: string }

function Row({ item, busy, onChange }: { item: ChecklistItemView; busy: boolean; onChange: (itemId: string, change: ChecklistChange) => void }) {
  const { t } = useDataProtectionText()
  const initial = (): Edit => ({ status: item.status, justification: item.justification, evidence: item.evidence_ids.join(', ') })
  const [edit, setEdit] = useState<Edit>(initial)
  // Ein neuer Serverstand setzt die Eingaben zurück (wie in der Vue-Fassung).
  useEffect(() => setEdit({ status: item.status, justification: item.justification, evidence: item.evidence_ids.join(', ') }), [item])
  const save = (): void => {
    const evidence = edit.evidence.split(',').map((entry) => entry.trim()).filter(Boolean)
    onChange(item.id, { status: edit.status, justification: edit.justification, evidence_ids: evidence })
  }
  return (
    <tr data-item={item.id}>
      <th scope="row">{item.id}</th>
      <td>
        {item.titel} {item.sperrt ? <span className="fa-assistant__badge">{t('itemBlocks', { gate: item.sperrt })}</span> : null}
        <br />
        <span className="fa-dataprotection__muted">{prefixedLabel(t, 'item', item.status)} · {item.zustaendig}</span>
      </td>
      <td>
        <label>
          {t('checklistStatus', { id: item.id })}{' '}
          <select value={edit.status} onChange={(event) => setEdit({ ...edit, status: event.target.value as ChecklistStatus })}>
            {STATUSES.map((status) => <option key={status} value={status}>{prefixedLabel(t, 'item', status)}</option>)}
          </select>
        </label>
        <label>{t('evidenceIds')} <input type="text" value={edit.evidence} onChange={(event) => setEdit({ ...edit, evidence: event.target.value })} /></label>
        <label>{t('answerJustification')} <textarea rows={2} value={edit.justification} onChange={(event) => setEdit({ ...edit, justification: event.target.value })} /></label>
        <button type="button" disabled={busy} onClick={save}>{t('saveItem')}</button>
      </td>
    </tr>
  )
}

export function AssistantChecklist({ items, busy, onChange }: { items: ChecklistItemView[]; busy: boolean; onChange: (itemId: string, change: ChecklistChange) => void }) {
  const { t } = useDataProtectionText()
  return (
    <section className="fa-dataprotection__panel" data-testid="assistant-checklist" aria-labelledby="fa-assistant-checklist" role="tabpanel">
      <h3 id="fa-assistant-checklist">{t('checklistTitle')}</h3>
      <table className="fa-dataprotection__table">
        <tbody>
          {items.map((item) => <Row key={item.id} item={item} busy={busy} onChange={onChange} />)}
        </tbody>
      </table>
    </section>
  )
}
