// packages-js/ui/src/dataprotection/components/AssistantTable.vue
<script setup lang="ts">
import { computed } from 'vue'
import { tableRows, tableValue, type AssistantQuestion, type TableRow } from '@auditcore/ui-core'
import { useI18n } from '../../i18n'
import { dataprotectionMessages } from '../core'

const props = defineProps<{ question: AssistantQuestion; value: string }>()
const emit = defineEmits<{ change: [value: string] }>()
const { t } = useI18n(dataprotectionMessages)
const rows = computed(() => tableRows(props.question, props.value))

function update(next: TableRow[]): void {
  emit('change', tableValue(next) || JSON.stringify(next))
}
function setCell(index: number, key: string, cell: string): void {
  update(rows.value.map((row, i) => (i === index ? { ...row, [key]: cell } : row)))
}
function addRow(): void {
  update([...rows.value, Object.fromEntries(props.question.columns.map((c) => [c.key, '']))])
}
function removeRow(index: number): void {
  update(rows.value.filter((_, i) => i !== index))
}
</script>

<template>
  <table class="fa-assistant__table">
    <caption>{{ t('tableCaption', { question: question.text }) }}</caption>
    <thead>
      <tr>
        <th v-for="column in question.columns" :key="column.key" scope="col">{{ column.title }}{{ column.required ? ' *' : '' }}</th>
        <th scope="col"><span class="fa-dataprotection__muted">–</span></th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(row, index) in rows" :key="index">
        <td v-for="column in question.columns" :key="column.key">
          <select v-if="column.choices.length" :value="row[column.key]" :aria-label="`${column.title} ${index + 1}`" @change="setCell(index, column.key, ($event.target as HTMLSelectElement).value)">
            <option value="">{{ t('chooseValue') }}</option>
            <option v-for="choice in column.choices" :key="choice" :value="choice">{{ choice }}</option>
          </select>
          <input v-else :value="row[column.key]" type="text" :aria-label="`${column.title} ${index + 1}`" @input="setCell(index, column.key, ($event.target as HTMLInputElement).value)" />
        </td>
        <td><button type="button" @click="removeRow(index)">{{ t('removeRow', { row: index + 1 }) }}</button></td>
      </tr>
    </tbody>
  </table>
  <button type="button" @click="addRow">{{ t('addRow') }}</button>
</template>

// packages-js/ui-react/src/dataprotection/assistant/AssistantTable.tsx
import { tableRows, tableValue, type AssistantQuestion, type TableRow } from '@auditcore/ui-core'
import { useDataProtectionText } from '../shared'

export function AssistantTable({ question, value, onChange }: { question: AssistantQuestion; value: string; onChange: (value: string) => void }) {
  const { t } = useDataProtectionText()
  const rows = tableRows(question, value)
  const update = (next: TableRow[]): void => onChange(tableValue(next) || JSON.stringify(next))
  const setCell = (index: number, key: string, cell: string): void => update(rows.map((row, i) => (i === index ? { ...row, [key]: cell } : row)))
  const addRow = (): void => update([...rows, Object.fromEntries(question.columns.map((c) => [c.key, '']))])
  return (
    <>
      <table className="fa-assistant__table">
        <caption>{t('tableCaption', { question: question.text })}</caption>
        <thead>
          <tr>
            {question.columns.map((column) => (
              <th key={column.key} scope="col">{column.title}{column.required ? ' *' : ''}</th>
            ))}
            <th scope="col"><span className="fa-dataprotection__muted">–</span></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row, index) => (
            <tr key={index}>
              {question.columns.map((column) => (
                <td key={column.key}>
                  {column.choices.length ? (
                    <select value={row[column.key]} aria-label={`${column.title} ${index + 1}`} onChange={(event) => setCell(index, column.key, event.target.value)}>
                      <option value="">{t('chooseValue')}</option>
                      {column.choices.map((choice) => (
                        <option key={choice} value={choice}>{choice}</option>
                      ))}
                    </select>
                  ) : (
                    <input value={row[column.key]} type="text" aria-label={`${column.title} ${index + 1}`} onChange={(event) => setCell(index, column.key, event.target.value)} />
                  )}
                </td>
              ))}
              <td><button type="button" onClick={() => update(rows.filter((_, i) => i !== index))}>{t('removeRow', { row: index + 1 })}</button></td>
            </tr>
          ))}
        </tbody>
      </table>
      <button type="button" onClick={addRow}>{t('addRow')}</button>
    </>
  )
}
