// packages-js/ui-react/src/identifiers/IdentifierResultView.tsx
import { Fragment, type ReactNode } from 'react'
import { identifierFacts, identifierReasonText, identifierStatusText, identifierStatusTone, type IdentifierResult } from '@auditcore/ui-core'
import type { UseIdentifierCheck } from './useIdentifierCheck'

function Fact({ label, children }: { label: string; children: ReactNode }) {
  return (
    <>
      <dt>{label}</dt>
      <dd>{children}</dd>
    </>
  )
}

/** Ergebnis einer Einzelprüfung: Status, Begründung, Normalform, Einzelheiten (wie `IdentifierResultView.vue`). */
export function IdentifierResultView({ view, result }: { view: UseIdentifierCheck; result: IdentifierResult }) {
  const { state, t, profile } = view
  const facts = state.catalogue ? identifierFacts(state.catalogue, result, t) : []
  return (
    <div className="fa-ident__result" aria-live="polite" data-testid="ident-result">
      <p className="fa-ident__status">
        <span className={`fa-ident__badge fa-ident__badge--${identifierStatusTone(result.status)}`}>{identifierStatusText(result.status, t)}</span>
        <span>{result.kind_label}</span>
      </p>
      <dl className="fa-ident__facts">
        <Fact label={t('message')}>{identifierReasonText(result, profile?.title ?? result.profile, t)}</Fact>
        {result.reason_label ? <Fact label={t('reason')}>{result.reason_label}</Fact> : null}
        {result.normalized ? <Fact label={t('normalized')}><code>{result.normalized}</code></Fact> : null}
        {result.country ? <Fact label={t('countryFound')}>{result.country}</Fact> : null}
      </dl>
      {facts.length ? (
        <details className="fa-ident__details">
          <summary>{t('details')}</summary>
          <dl className="fa-ident__facts">
            {facts.map((fact) => (
              <Fragment key={fact.key}>
                <dt>{fact.label}</dt>
                <dd>{fact.value}</dd>
              </Fragment>
            ))}
          </dl>
        </details>
      ) : null}
    </div>
  )
}

// packages-js/ui/src/identifiers/IdentifierResultView.vue
<script setup lang="ts">
import { computed } from 'vue'
import { identifierFacts, identifierReasonText, identifierStatusText, identifierStatusTone, type IdentifierResult } from '@auditcore/ui-core'
import { useIdentifierContext } from './context'

const props = defineProps<{ result: IdentifierResult }>()
const { view, t } = useIdentifierContext()
const { state, profile } = view
const reason = computed(() => identifierReasonText(props.result, profile.value?.title ?? props.result.profile, t))
const facts = computed(() => (state.value.catalogue ? identifierFacts(state.value.catalogue, props.result, t) : []))
</script>

<template>
  <div class="fa-ident__result" aria-live="polite" data-testid="ident-result">
    <p class="fa-ident__status">
      <span :class="['fa-ident__badge', `fa-ident__badge--${identifierStatusTone(result.status)}`]">{{ identifierStatusText(result.status, t) }}</span>
      <span>{{ result.kind_label }}</span>
    </p>
    <dl class="fa-ident__facts">
      <dt>{{ t('message') }}</dt>
      <dd>{{ reason }}</dd>
      <template v-if="result.reason_label">
        <dt>{{ t('reason') }}</dt>
        <dd>{{ result.reason_label }}</dd>
      </template>
      <template v-if="result.normalized">
        <dt>{{ t('normalized') }}</dt>
        <dd><code>{{ result.normalized }}</code></dd>
      </template>
      <template v-if="result.country">
        <dt>{{ t('countryFound') }}</dt>
        <dd>{{ result.country }}</dd>
      </template>
    </dl>
    <details v-if="facts.length" class="fa-ident__details">
      <summary>{{ t('details') }}</summary>
      <dl class="fa-ident__facts">
        <template v-for="fact in facts" :key="fact.key">
          <dt>{{ fact.label }}</dt>
          <dd>{{ fact.value }}</dd>
        </template>
      </dl>
    </details>
  </div>
</template>
